README.md
-------
Adding product description to the README.md
It's docs I didn't
It's docs I didn't
@callumlawson
=> Adding product description to readme

ci/docs-build-verification.sh
-------
Harden against repo name changes.
Tested locally.
N/A
=> Docs Branch Verification Fix

docs/README.md
Removed product description from docs - now on frontpage
Just a docs removal.
This is.
@samiwh
=> Removed product description from docs - now on frontpage

workers/unity/Assets/Playground/Scripts/UI/UpdateUISystem.cs
Move UpdateUISystem to UpdateInGroup(Update)
Tested the change locally, UI now updates as expected.
N/A
=> BugFix: UTY-457 Move UpdateUISystem from Before FixedUpdate to SpatialOSUpdate.

docs/README.md
Also reordered doc table of content
Checked link manually.
@samiwh
=> Adding missing link to component docs

docs/content/custom-replication-system.md
@bethaitman copy-edited the `http://custom-replication-system.md` page.
@ElleEss
=> General cleanup & removal of passive voice.

code_generator/Templates/UnityCommandPayloadGenerator.tt, code_generator/Templates/UnityComponentConversionGenerator.tt, code_generator/Templates/UnityComponentDataConversionGenerator.tt
-------
Previously we only provided the attribute set, now we provide the id too!
Tested locally.
N/A. 
@jessicafalk
=> UTY-328: Add Caller Worker Id to Command Requests

README.md, docs/README.md, docs/latest-roadmap.md
-------
Description
Roadmap docs updates:
1. Added title and date.
2. Added definition and date to 'first look'.
3. Added formatting to the first column.
3. Added link to feedback information.
4. Renamed to standard lower-case docs naming convention - used a rename as changing case was confusing GitHub and git.
5. Did not update roadmap text.
Repo README  and docs/README updates
1. Set a link to the roadmap from the docs readme.
2. Updated the text and link to the roadmap from the …
=> Updated roadmap and associated files

README.md
Added link to email sign-up.
Clicked on link.
Is docs.
n/a
=> Added link to email sign-up.

README.md
=> Corrected full stop

workers/unity/Assets/Gdk/Core/Config/ScriptableWorkerConfiguration.asset
-------
Upgrading to the latest beta accidentally broke the worker config window due to loading an invalid configuration.
Ran a local deployment 
None needed 
=> Fixing the worker configuration window

ci/create-windows-image.ps1
This will be adapted to Ansible for the final version.
Testing on a blank instance provided by @petemounce 
@petemounce @DoomGerbil
=> Initial script to setup a Windows Buildkite agent

.gitattributes
-------
Add asmdefs as LF line endings.
=> Add asmdefs as LF line endings.

README.md
Updated the readme file according to the feedback received.
=> Updated README with better words

workers/unity/Assets/Generated/improbable/gdk/tests/ExhaustiveBlittableSingularTranslation.cs, workers/unity/Assets/Generated/improbable/gdk/tests/ExhaustiveMapKeyTranslation.cs, workers/unity/Assets/Generated/improbable/gdk/tests/ExhaustiveMapValueTranslation.cs, workers/unity/Assets/Generated/improbable/gdk/tests/ExhaustiveOptionalTranslation.cs, workers/unity/Assets/Generated/improbable/gdk/tests/ExhaustiveRepeatedTranslation.cs, workers/unity/Assets/Generated/improbable/gdk/tests/ExhaustiveSingularTranslation.cs, workers/unity/Assets/Generated/improbable/gdk/tests/NestedComponentTranslation.cs
-------
Some generated translations were not added. Here they are.
N/A
N/A
=> Add generated translations.

tools/DocsLinter/Tests/LinkCheckingTests.cs
-------
Fix the tests.
Yes
N/A
=> Use HTTP instead of HTTPS

workers/unity/Assets/Gdk/PlayerLifecycle/Systems/PlayerCreation/HandleCreatePlayerRequestSystem.cs, workers/unity/Assets/Gdk/PlayerLifecycle/Systems/PlayerCreation/SendCreatePlayerRequestSystem.cs, workers/unity/Assets/Gdk/PlayerLifecycle/Systems/PlayerHeartbeat/HandlePlayerHeartbeatRequestSystem.cs, workers/unity/Assets/Gdk/PlayerLifecycle/Systems/PlayerHeartbeat/HandlePlayerHeartbeatResponseSystem.cs, workers/unity/Assets/Gdk/PlayerLifecycle/Systems/PlayerHeartbeat/SendPlayerHeartbeatRequestSystem.cs, workers/unity/Assets/Gdk/TestUtils/Tests/Editmode/HybridGdkSystemTestBaseTests.cs, workers/unity/Assets/Gdk/TransformSynchronization/Systems/ApplyTransformUpdatesSystem.cs, workers/unity/Assets/Gdk/TransformSynchronization/Systems/InterpolateTransformSystem.cs, workers/unity/Assets/Gdk/TransformSynchronization/Systems/LocalTransformSyncSystem.cs, workers/unity/Assets/Gdk/TransformSynchronization/Systems/PositionSendSystem.cs, workers/unity/Assets/Gdk/TransformSynchronization/Systems/TransformSendSystem.cs, workers/unity/Assets/Playground/Scripts/Camera/FollowCameraSystem.cs, workers/unity/Assets/Playground/Scripts/Camera/InitCameraSystem.cs, workers/unity/Assets/Playground/Scripts/Cubes/CubeMovementSystem.cs, workers/unity/Assets/Playground/Scripts/Cubes/ProcessColorChangeSystem.cs, workers/unity/Assets/Playground/Scripts/Cubes/TriggerColorChangeSystem.cs, workers/unity/Assets/Playground/Scripts/DisconnectSystem.cs, workers/unity/Assets/Playground/Scripts/Player/LocalPlayerInputSync.cs, workers/unity/Assets/Playground/Scripts/Player/MoveLocalPlayerSystem.cs, workers/unity/Assets/Playground/Scripts/Player/PlayerCommandsSystem.cs, workers/unity/Assets/Playground/Scripts/Player/ProcessLaunchCommandSystem.cs, workers/unity/Assets/Playground/Scripts/Player/ProcessRechargeSystem.cs, workers/unity/Assets/Playground/Scripts/Spawning/ArchetypeInitializationSystem.cs, workers/unity/Assets/Playground/Scripts/Spawning/GameObjectInitializationSystem.cs, workers/unity/Assets/Playground/Scripts/UI/InitUISystem.cs, workers/unity/Assets/Playground/Scripts/UI/UpdateUISystem.cs, workers/unity/Packages/manifest.json
-------
Upgrading to latest entities package
Ran the tests in Unity
don't think this needs to be documented
=> Upgrading to Entities 0.0.12-preview.8

ci/build-client.sh, ci/build-gamelogic.sh, ci/includes/pinned-tools.sh, ci/test.sh
-------
adding some `rm` statements because Unity doesn't like building stuff after running tests without a clean up in between.
Also changed the log directory to `logs/` to make sure that TeamCity picks up the logs and we don't have to remotely connect everytime.
ran it on all agents multiple times to make sure nothing gets stuck anymore
no doc needed
=> Fixing our first flake

workers/unity/Packages/com.improbable.gdk.core/Logging/ForwardingDispatcher.cs
-------
Use error instead of fatal for exceptions.
N/A
N/A
=> Use error instead of fatal for exceptions.

ci/prepare-unity.sh
-------
Ensure that go files are cleaned up after a new Unity download.
N/A
=> Cleanup Go Files After Unity Install

docs/README.md, docs/content/logging.md
-------
Public logging docs.
N/A
N/A
=> UTY-713: Add docs for logging.

workers/unity/Packages/com.improbable.gdk.legacy/Editor/BuildSystem/WorkerBuilder.cs
Add check to build result instead of ignoring failure
N/A
N/A
N/A
=> Check build result and throw when failed.

code_generator/GdkCodeGenerator/Templates/UnityCommandPayloadGenerator.tt, code_generator/GdkCodeGenerator/Templates/UnityComponentConversionGenerator.tt, docs/README.md, docs/content/logging.md, workers/unity/Packages/com.improbable.gdk.core/Components/WorldCommandsTranslation.cs, workers/unity/Packages/com.improbable.gdk.legacy/Editor/BuildSystem/WorkerBuilder.cs
=> Rebase onto master

workers/unity/Assets/Playground/Scripts/Player/ConnectButtonClickSystem.cs
Last IP connected to is now remembered by the app.
=> Added IP caching to remember the last IP connected to

ci/build-test.sh, ci/test.sh, tools/RunUnity/Program.cs, workers/unity/Packages/manifest.json
-------
yeah, scripts were completely broken.  Fixing it and actually running codegen
ran it locally
no docs needed
=> fixing shell scripts

docs/content/authority.md, docs/content/commands.md, docs/content/component-data.md, docs/content/create-entity.md, docs/content/custom-replication-system.md, docs/content/events.md, docs/content/logging.md, docs/content/reactive-components.md, docs/setup-and-installing.md
-------
Minor doc fixes based.
N/A
N/A
=> Minor doc fixes.

workers/unity/Assets/Playground/Scenes/SampleScene.unity, workers/unity/Assets/Playground/Scripts/Camera/FollowCameraSystem.cs, workers/unity/Assets/Playground/Scripts/Camera/InitCameraSystem.cs, workers/unity/Assets/Playground/Scripts/Player/LocalPlayerInputSync.cs, workers/unity/Assets/Playground/Scripts/Player/VirtualJoystick.cs, workers/unity/Assets/Playground/Scripts/Player/VirtualJoystick.cs.meta, workers/unity/ProjectSettings/ProjectSettings.asset, workers/unity/ProjectSettings/TagManager.asset
Added 2 virtual sticks on screen to control player and camera.
=> UTY-700: Touch Screen Controls

docs/content/commands.md
-------
Fix small doc typos in commands.
N/A
N/A
=> Fix small doc typos in commands.

docs/setup-and-installing.md
Noted the specific version of .Net Core SDK that we know works and specified that its the x64 version.
N/A
YES
=> Amend Setup Guide

README.md, docs/README.md, docs/content/faqs/faqs.md, docs/content/faqs/key-features.md
* Added FAQ page
* Added Summary of key features page (linked to from FAQs)
* Put these two docs in a new `/docs/contents/faqs` directory
* Added to animated gifs for the Key Features page
* From /README.md - linked to the FAQ doc quite prominently
* From /docs/README.md - linked to the FAQ doc quite prominently
* From the /docs/README.md - linked to the FAQ doc and the summary of key features docs in the table of contents
Clicked the links.
Is documentation.
@ernopp (@anne-edwards )
=> Added FAQ page ++

docs/content/faqs/faqs.md
Add product name to title
N/A
N/A
N/A
=> Add product name to title

ci/includes/pinned-tools.sh, docs/content/logging.md, docs/setup-and-installing.md, workers/unity/Assets/Playground/Scripts/Cubes/ProcessColorChangeSystem.cs, workers/unity/Packages/com.improbable.gdk.core/Logging/ForwardingDispatcher.cs, workers/unity/Packages/com.improbable.gdk.core/Logging/LogEvent.cs, workers/unity/Packages/com.improbable.gdk.core/Logging/LoggingDispatcher.cs, workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/Logging.meta, workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/Logging/LoggingTests.cs, workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/Logging/LoggingTests.cs.meta
=> Merge master into feature/monobehaviour-support-shared

code_generator/GdkCodeGenerator/src/Generation/Model/Details/UnityComponentDetails.cs
Fix semantic merge error - forget I added this twice 😬
=> fix semantic merge

code_generator/GdkCodeGenerator/Templates/UnityComponentDataGenerator.tt
Extra parenthesis - didn't realise until things actually compiled properly
=> [Core C# SDK] - Extra Parenthesis 

workers/unity/ProjectSettings/ProjectSettings.asset
-------
Internet Access is now a strict requirement on Android, fixing weird cases where a game was only able to connect in the Development Build mode
=> Bugfix: Require Internet Access on Android

.gitignore, workers/unity/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponent.cs, workers/unity/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponentCommandPayloads.cs, workers/unity/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponentEvents.cs, workers/unity/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponentTranslation.cs, workers/unity/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/FirstCommandRequest.cs, workers/unity/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/FirstCommandResponse.cs, workers/unity/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/FirstEventPayload.cs, workers/unity/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/SecondCommandRequest.cs, workers/unity/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/SecondCommandResponse.cs, workers/unity/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/SecondEventPayload.cs, workers/unity/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/FirstCommandRequest.cs, workers/unity/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/FirstCommandResponse.cs, workers/unity/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/FirstEventPayload.cs, workers/unity/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponent.cs, workers/unity/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponentCommandPayloads.cs, workers/unity/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponentEvents.cs, workers/unity/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponentTranslation.cs, workers/unity/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/SecondCommandRequest.cs, workers/unity/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/SecondCommandResponse.cs, workers/unity/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/SecondEventPayload.cs
-------
Fixed 2 issues with gitignore:
1. Generated test types were only excluded from being ignored in the marked folder but not recursively
2. build/dependencies/schema/standard_library/target.spatialos_worker_packages.json.md5 was not ignored.
@firtina-improbable
=> Fixed issues with our .gitignore

.gitignore, README.md, docs/README.md, docs/content/faqs/faqs.md, docs/content/faqs/key-features.md, docs/setup-and-installing.md, workers/unity/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponent.cs, workers/unity/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponentCommandPayloads.cs, workers/unity/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponentEvents.cs, workers/unity/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponentTranslation.cs, workers/unity/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/FirstCommandRequest.cs, workers/unity/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/FirstCommandResponse.cs, workers/unity/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/FirstEventPayload.cs, workers/unity/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/SecondCommandRequest.cs, workers/unity/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/SecondCommandResponse.cs, workers/unity/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/SecondEventPayload.cs, workers/unity/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/FirstCommandRequest.cs, workers/unity/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/FirstCommandResponse.cs, workers/unity/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/FirstEventPayload.cs, workers/unity/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponent.cs, workers/unity/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponentCommandPayloads.cs, workers/unity/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponentEvents.cs, workers/unity/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponentTranslation.cs, workers/unity/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/SecondCommandRequest.cs, workers/unity/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/SecondCommandResponse.cs, workers/unity/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/SecondEventPayload.cs
=> Merging from master

README.md, docs/content/faqs/faqs.md, docs/known-issues.md
Add Known issues, remove Mac Support warnings.
None
=> Add Known issues, remove Mac Support warnings

workers/unity/Assets/Playground/Resources/Materials/BlackMaterial.mat, workers/unity/Assets/Playground/Resources/Materials/Cube.mat, workers/unity/Assets/Playground/Resources/Materials/CubeKinematic.mat, workers/unity/Assets/Playground/Resources/Shaders.meta, workers/unity/Assets/Playground/Resources/Shaders/Simple-Diffuse.shader, workers/unity/Assets/Playground/Resources/Shaders/Simple-Diffuse.shader.meta
-------
Created a simple coloured diffuse shader and changed materials to use it. Fixes weird mobile rendering problems.
=> UTY-851: Use a mobile-friendly shader

code_generator/GdkCodeGenerator/Templates/UnityComponentDataGenerator.tt, code_generator/GdkCodeGenerator/Templates/UnityComponentGenerator.tt, schema/improbable/gdk/tests/empty_component.schema, workers/unity/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFields.cs, workers/unity/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsTranslation.cs, workers/unity/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithCommands.cs, workers/unity/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithCommandsCommandPayloads.cs, workers/unity/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithCommandsTranslation.cs, workers/unity/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithEvents.cs, workers/unity/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithEventsEvents.cs, workers/unity/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithEventsTranslation.cs, workers/unity/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/Empty.cs
-------
This makes the implementations of reader/writers much simpler
This is because Readers/Writers without this PR need to do a lot of conditional code generation depending on whether this struct exists or not which adds a lot to the complexity
@samiwh @zeroZshadow
=>  Always create update structs for all components even if they have no fields

workers/unity/Assets/Playground/Scenes/SampleScene.unity
-------
Slightly bumped up the Virtual Stick size to make it easier to play the game
=> Playground Mobile Controls: Increased virtual stick size

code_generator/GdkCodeGenerator/Templates/UnityReaderWriterGenerator.tt, workers/unity/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsReaderWriter.cs, workers/unity/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithCommandsReaderWriter.cs, workers/unity/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithEventsReaderWriter.cs, workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Readers/IReader.cs, workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Readers/ReaderWriterBase.cs, workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Writers/IWriter.cs
-------
Accounts for #193 
Can review in commit order :)
All GDK tests pass
Local deployment still works with monobehaviours (the spinner spins!)
@zeroZshadow @MPeti01
=> Simplify reader/writer classes

README.md, docs/content/mobile/android-local.md, workers/unity/Packages/com.improbable.gdk.android/Editor/AndroidSpatialRunner.cs
-------
Documentation for Local Android workflow
Drive-by change: Changed menu item to say "Run SpatialOS for Android" instead of "Run Spatial for Android".
Docs linter
=> UTY-554: Local Android workflow docs

code_generator/GdkCodeGenerator/GdkCodeGenerator.csproj, code_generator/GdkCodeGenerator/Templates/UnityCommandComponentsGenerator.tt, code_generator/GdkCodeGenerator/Templates/UnityCommandPayloadGenerator.tt, code_generator/GdkCodeGenerator/Templates/UnityCommandStorageGenerator.tt, code_generator/GdkCodeGenerator/Templates/UnityComponentConversionGenerator.tt, code_generator/GdkCodeGenerator/Templates/UnityReferenceTypeProviderGenerator.tt, code_generator/GdkCodeGenerator/src/Generation/Generators/Parts/UnityCommandComponentsGeneratorPart.cs, code_generator/GdkCodeGenerator/src/Generation/Generators/Parts/UnityCommandStorageGeneratorPart.cs, code_generator/GdkCodeGenerator/src/Generation/Generators/Parts/UnityReferenceTypeProviderGeneratorPart.cs, code_generator/GdkCodeGenerator/src/Generation/Model/Details/UnityCommandDetails.cs, code_generator/GdkCodeGenerator/src/Generation/SingleGenerationJob.cs, workers/unity/Packages/com.improbable.gdk.core/CodegenAdapters/ComponentCleanupHandler.cs, workers/unity/Packages/com.improbable.gdk.core/CodegenAdapters/ComponentDispatcherHandler.cs, workers/unity/Packages/com.improbable.gdk.core/CodegenAdapters/ComponentReplicationHandler.cs, workers/unity/Packages/com.improbable.gdk.core/Commands/CommandStorage.cs, workers/unity/Packages/com.improbable.gdk.core/Commands/CommandStorage.cs.meta, workers/unity/Packages/com.improbable.gdk.core/MutableView/MutableView.cs, workers/unity/Packages/com.improbable.gdk.core/Systems/CleanReactiveComponentsSystem.cs, workers/unity/Packages/com.improbable.gdk.core/Systems/CommandBookkeepingSystem.cs, workers/unity/Packages/com.improbable.gdk.core/Systems/CommandBookkeepingSystem.cs.meta, workers/unity/Packages/com.improbable.gdk.core/Systems/CommandRequestTrackerSystem.cs, workers/unity/Packages/com.improbable.gdk.core/Systems/CommandRequestTrackerSystem.cs.meta, workers/unity/Packages/com.improbable.gdk.core/Systems/SpatialOSReceiveSystem.cs, workers/unity/Packages/com.improbable.gdk.core/Systems/SpatialOSSendSystem.cs, workers/unity/Packages/com.improbable.gdk.core/Worker/WorkerBase.cs
Alright big changes here:
1. Added command sending and receiving impl
2. Added components for each action as specified in the doc
3. Added storage for command requests in flight (owned by the `CommandBookkeepingSystem`)
4. Misc changes required to make it work.
This all compiles - once @zeroZshadow finishes the event generation we can change the playground to use the new API and fix any bugs that arise.
It compiled 🤷‍♂️
=> UTY-756: Commands API v2 Code Generation

code_generator/GdkCodeGenerator/Templates/UnityComponentConversionGenerator.tt
Minor codegen fixes to make updates and auth change lists actually work! 
Ran playground - actually works.
=> codegen fixes

code_generator/GdkCodeGenerator/Templates/UnityComponentDataGenerator.tt, code_generator/GdkCodeGenerator/Templates/UnityTypeContent.tt, code_generator/GdkCodeGenerator/src/Generation/Model/Details/UnityFieldDetails.cs, code_generator/GdkCodeGenerator/src/Generation/Model/SchemaFunctionMappings.cs, workers/unity/Packages/com.improbable.gdk.core/Systems/SpatialOSReceiveSystem.cs
Some trolls serialization bugs. Am also forwarding exceptions from dispatcher callbacks as they were being swallowed. 
It ran with no exceptions (from our side) 
=> Bugfixes - Serialization

workers/unity/Packages/com.improbable.gdk.core/Logging/ForwardingDispatcher.cs, workers/unity/Packages/com.improbable.gdk.core/Logging/ILogDispatcher.cs, workers/unity/Packages/com.improbable.gdk.core/Logging/LoggingDispatcher.cs, workers/unity/Packages/com.improbable.gdk.core/Worker/Worker.cs
-------
Making the `ILogDispatcher` abstract to be able to add the connection to all dispatcher types without having to check for the exact type.
ran it locally.
no docs
=> Store connection for all log dispatchers

workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/Utility/EntityBuilderTest.cs, workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/Utility/EntityBuilderTest.cs.meta, workers/unity/Packages/com.improbable.gdk.core/Utility/EntityBuilder.cs
Noticed `hasBuiltOnce` was never used - actually start using it.
Added tests for the EntityBuilder!
N/A
@zeroZshadow
=> Entity Builder Bugfix and Tests

workers/unity/Assets/Playground/Scripts/MonoBehaviours/FlashOnCollision.cs
-------
Not so eager now!
Unity doesn't like it when you create some types too eagerly. Especially material things.
Unity does not complain any more when these scripts are loaded or prefabs with these scripts are selected.
@MPeti01 @samiwh
=> Fixed eager MPB creation

code_generator/GdkCodeGenerator/Templates/UnityComponentConversionGenerator.tt, workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveBlittableSingularTranslation.cs, workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapKeyTranslation.cs, workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapValueTranslation.cs, workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveOptionalTranslation.cs, workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveRepeatedTranslation.cs, workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveSingularTranslation.cs, workers/unity/Assets/Generated/Source/improbable/gdk/tests/NestedComponentTranslation.cs, workers/unity/Assets/Generated/Source/improbable/gdk/tests/alternateschemasyntax/ConnectionTranslation.cs, workers/unity/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponentTranslation.cs, workers/unity/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsTranslation.cs, workers/unity/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithCommandsTranslation.cs, workers/unity/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithEventsTranslation.cs, workers/unity/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponentTranslation.cs
The Core merge missed a check to not apply component updates if you are authoritative (i.e. - sent them yourselves).
This PR fixes this behaviour
=> Bugfix: Fix Component Update Short Circuit Regression

workers/unity/Packages/manifest.json
-------
another upgrade
ran it locally. it worked
none needed
=> upgrading entities package

workers/unity/Assets/Playground/Scripts/Bootstrap.cs
-------
Launcher doesn't pass in the worker type, so we have to explicitly set it.
ran a cloud deployment
none needed
@jamiebrynes7
=> Fixing Client when starting through Launcher

docs/content/authority.md, docs/content/commands.md, docs/content/component-data.md, docs/content/create-entity.md, docs/content/custom-replication-system.md, docs/content/entity-checkout-process.md, docs/content/events.md, docs/content/reactive-components.md, docs/content/system-update-order.md
Updates all the docs to reflect the changes to the core. Some things have been omitted for now (reference type providers).
N/A
yes
@ElleEss
=> UTY-963: Core C# SDK Docs Changes

workers/unity/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponentTranslation.cs, workers/unity/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithCommandsTranslation.cs, workers/unity/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponentTranslation.cs, workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityComponentConversionGenerator.tt
Just some small changes to how we send commands to improve CPU usage.
This system really needs a re-design for proper performance!
=> Small optimization in SendCommands to decrease cpu usage.

workers/unity/Packages/com.improbable.gdk.tools/DownloadCoreSdk.cs
=> Fixed quoting

workers/unity/Packages/com.improbable.gdk.tools/LocalLaunch.cs
=> Stop the build configs from building twice when launching locally

workers/unity/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponentGameObjectComponentDispatcher.cs, workers/unity/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithCommandsGameObjectComponentDispatcher.cs, workers/unity/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponentGameObjectComponentDispatcher.cs, workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/GameObjectRepresentation/CommandSenders/CommandResponseHandlerTests.cs, workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityGameObjectComponentDispatcherGenerator.tt
-------
Fixes merge conflicts from #269 
Tested locally
=> Unbreak master

docs/content/temporary-components.md
-------
adding link to the system update order doc and fixing up code example
this is  the documentation :D
@ElleEss
=> fixing code example

workers/unity/Packages/com.improbable.gdk.core/Worker/Worker.cs
-------
Fixed log typo
Ran locally
Not required
=> Fixed log typo: create -> created a.

docs/README.md, workers/unity/Packages/com.improbable.gdk.core/Utility/EntityManagerExtensions.cs
-------
Added entities package version to doc and shortened error message
=> Added entities package version and shortened error message

workers/unity/Packages/com.improbable.gdk.core/Commands/WorldCommands.cs, workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/GameObjectDispatcherSystem.cs, workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/GameObjectWorldCommandSystem.cs, workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/GameObjectWorldCommandSystem.cs.meta, workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Injection/InjectableId.cs, workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Injection/WorldCommandRequestSender.cs, workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Injection/WorldCommandRequestSender.cs.meta, workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Injection/WorldCommandResponseHandler.cs, workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Injection/WorldCommandResponseHandler.cs.meta, workers/unity/Packages/com.improbable.gdk.core/Worker/Worker.cs
-------
Example usage (to be fleshed out more in next PR):
```cs
public class Terminator : MonoBehaviour
{
[Require] private WorldCommandsRequirables.WorldCommandRequestSender worldCommandRequestSender;
[Require] private WorldCommandsRequirables.WorldCommandResponseHandler worldCommandResponseHandler;
public void OnEnable()
{
worldCommandResponseHandler.OnDeleteEntityResponse += OnDeleteEntityResponse;
}
private void OnDeleteEntityResponse(WorldCommands.DeleteEntity.ReceivedResponse response)
{
if (response.Op.StatusCode != StatusCode.Success)
{
Debug.LogError("Could not …
```
=> Implement world command sending

workers/unity/Packages/com.improbable.gdk.tools/.DownloadCoreSdk/Program.cs
Escaped a path that previously wasn't.
=> escape potential path

workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/GameObjectWorldCommandSystem.cs, workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Injection/WorldCommandRequestSender.cs, workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Injection/WorldCommandResponseHandler.cs
-------
See title
Tested locally in playground, will be added in next PR
To come later
@jamiebrynes7 @MPeti01
=> Implement entity query sending and responses

test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveBlittableSingular.cs, test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveBlittableSingularTranslation.cs, test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapKey.cs, test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapKeyTranslation.cs, test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapValue.cs, test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapValueTranslation.cs, test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveOptional.cs, test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveOptionalTranslation.cs, test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveRepeated.cs, test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveRepeatedTranslation.cs, test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveSingular.cs, test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveSingularTranslation.cs, test-project/Assets/Generated/Source/improbable/gdk/tests/NestedComponent.cs, test-project/Assets/Generated/Source/improbable/gdk/tests/NestedComponentTranslation.cs, test-project/Assets/Generated/Source/improbable/gdk/tests/alternateschemasyntax/Connection.cs, test-project/Assets/Generated/Source/improbable/gdk/tests/alternateschemasyntax/ConnectionTranslation.cs, test-project/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponent.cs, test-project/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponentTranslation.cs, test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFields.cs, test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsTranslation.cs, test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithCommands.cs, test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithCommandsTranslation.cs, test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithEvents.cs, test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithEventsTranslation.cs, test-project/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponent.cs, test-project/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponentTranslation.cs, workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityComponentConversionGenerator.tt, workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityComponentDataGenerator.tt, workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/src/Generation/Model/Details/FieldTypes.cs, workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/src/Generation/Model/Details/UnityFieldDetails.cs
Look at first commit only. The latter is just generated code.
Compiled both projects - ran playground, updates were still serialised. Could see color changing on the spinners on the worker so change fixed what was intended.
N/A
=> Fix Short Circuiting Update

workers/unity/Packages/com.improbable.gdk.buildsystem/BuildSystemMenu.cs, workers/unity/Packages/com.improbable.gdk.buildsystem/WorkerBuilder.cs, workers/unity/Packages/com.improbable.gdk.tools/Common.cs
-------
Each commit to fix another problem
Testing with an external project
Internal fixes
=> Fix a few problems I encountered during dogfooding

docs/content/gameobject/reading-and-writing-component-data.md
=> Added reading and writing component data

docs/README.md, docs/content/set-up-new-project.md
Fixed some stuff in the TOC and also spotted a rogue "pre-alpha".
=> small fixes

docs/README.md
=> Docs signposting quick fix: Don't recommend custom config for beginners

docs/content/ecs/accessing-worker-info.md, docs/content/gameobject/reading-and-writing-component-data.md
-------
2 formatting issues fixed in some new .md docs: 
1. Massive number of blank lines in some code samples
2. Indentation in raw MD turning would-be lists into code blocks.
@samc-improbable
=> Fixed formatting issues with new .md docs

docs/content/ecs/entity-checkout-process.md, docs/content/gameobject/logging-and-accessing-the-worker.md, docs/content/gameobject/sending-receiving-commands.md, docs/content/gameobject/sending-receiving-events.md, docs/content/gameobject/set-up-gameobjects.md, docs/content/gameobject/world-commands.md
-------
GDocs autoupdate now.
@samc-improbable
=> Removing phrase about WIP GDocs links not autoupdating

docs/content/ecs/commands.md, docs/content/ecs/create-entity.md, docs/content/ecs/reactive-components.md
-------
The creating entities docs have code issues in them. This fixes it.
N/A
N/A
=> Fix creating entities doc

workers/unity/Packages/com.improbable.gdk.tools/GdkToolsConfigurationEditorExtensions.cs
Added a save button - this will make it easier to save changes to the configuration
Made changes - clicked save - it was saved 👍 
N/A
=> Add explicit save button to tools config

docs/content/ecs/commands.md
=> Updated docs to use command new syntax

docs/setup-and-installing.md
Noted that you need the .NET Core SDK and noted the tested versions.
N/A
yes
@jessicafalk
=> Tweak Setup Guide for .NET Core

docs/README.md, docs/known-issues.md, test-project/Packages/manifest.json, workers/unity/Assets/Playground/Scripts/Cubes/CubeMovementSystem.cs, workers/unity/Assets/Playground/Scripts/Cubes/ProcessColorChangeSystem.cs, workers/unity/Assets/Playground/Scripts/Cubes/TriggerColorChangeSystem.cs, workers/unity/Assets/Playground/Scripts/Metrics/MetricSendSystem.cs, workers/unity/Assets/link.xml, workers/unity/Packages/com.improbable.gdk.buildsystem/package.json, workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/EntityGameObjectLinkerSystem.cs, workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/GameObjectDispatcherSystem.cs, workers/unity/Packages/com.improbable.gdk.core/Systems/CleanReactiveComponentsSystem.cs, workers/unity/Packages/com.improbable.gdk.core/Systems/CommandRequestTrackerSystem.cs, workers/unity/Packages/com.improbable.gdk.core/Systems/CustomSpatialOSSendSystem.cs, workers/unity/Packages/com.improbable.gdk.core/Systems/SpatialOSReceiveSystem.cs, workers/unity/Packages/com.improbable.gdk.core/Systems/SpatialOSSendSystem.cs, workers/unity/Packages/com.improbable.gdk.core/Systems/WorkerSystem.cs, workers/unity/Packages/com.improbable.gdk.core/Systems/WorldCommandsSendSystem.cs, workers/unity/Packages/com.improbable.gdk.core/package.json, workers/unity/Packages/com.improbable.gdk.gameobjectcreation/GameObjectInitializationSystem.cs, workers/unity/Packages/com.improbable.gdk.playerlifecycle/Systems/PlayerCreation/SendCreatePlayerRequestSystem.cs, workers/unity/Packages/com.improbable.gdk.testutils/Tests/Editmode/HybridGdkSystemTestBaseTests.cs, workers/unity/Packages/com.improbable.gdk.transformsynchronization/Systems/TickRateEstimationSystem.cs, workers/unity/Packages/manifest.json
-------
Upgrading the entities package to latest. 
tested it locally. No errors, everything works as expected
updated docs
=> Upgrading to entities package 13

workers/unity/Assets/Playground/Scripts/Cubes/CubeMovementSystem.cs, workers/unity/Packages/com.improbable.gdk.transformsynchronization/Systems/DefaultApplyLatestTransformSystem.cs, workers/unity/Packages/com.improbable.gdk.transformsynchronization/Systems/GetTransformValueToSetSystem.cs, workers/unity/Packages/com.improbable.gdk.transformsynchronization/Systems/TickRateEstimationSystem.cs, workers/unity/Packages/com.improbable.gdk.transformsynchronization/Systems/TickSystem.cs
Fixed update wasn't running in fixed update. Fixed that.
Ran it. Fixed update was fixed.
=> Moved all the fixed update systems to fixed update

workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/SpatialOSComponent.cs, workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/GameObjectRepresentation/SpatialOSComponentTests.cs
-------
adding `TryGetSpatialOSEntityIdForGameObject`
added tests
no doc so far
=> adding TryGetSpatialOSEntityIdForGameObject

test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveBlittableSingularTranslation.cs, test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapKeyTranslation.cs, test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapValueTranslation.cs, test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveOptionalTranslation.cs, test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveRepeatedTranslation.cs, test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveSingularTranslation.cs, test-project/Assets/Generated/Source/improbable/gdk/tests/NestedComponentTranslation.cs, test-project/Assets/Generated/Source/improbable/gdk/tests/alternateschemasyntax/ConnectionTranslation.cs, test-project/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponentTranslation.cs, test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsTranslation.cs, test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithCommandsTranslation.cs, test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithEventsTranslation.cs, test-project/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponentTranslation.cs, workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityComponentConversionGenerator.tt
Updated code generation to no longer generate unreachable code
=> Fix empty command warning about unreachable code

workers/unity/Packages/com.improbable.gdk.core/Logging/ForwardingDispatcher.cs, workers/unity/Packages/com.improbable.gdk.core/Logging/ILogDispatcher.cs, workers/unity/Packages/com.improbable.gdk.core/Logging/LogEvent.cs, workers/unity/Packages/com.improbable.gdk.core/Logging/LoggingDispatcher.cs, workers/unity/Packages/com.improbable.gdk.core/Logging/LoggingUtils.cs, workers/unity/Packages/com.improbable.gdk.core/Worker/Worker.cs, workers/unity/Packages/com.improbable.gdk.testutils/TestLogDispatcher.cs
Logs are now much clearer when you have multiple workers in your editor
=> Add WorkType is a well known field for LogEvents

docs/content/ecs/logging.md
-------
Mentioning entity logging in the logging docs.
=> mentioning entity logging

workers/unity/Packages/com.improbable.gdk.tools/LocalLaunch.cs
Actually run the command given rather than `spatial osascript`
Manually
N/A
@jared-improbable
=> Mac Osascript Regression Fix

workers/unity/Assets/Playground/Config/PlayerTemplate.cs, workers/unity/Packages/com.improbable.gdk.playerlifecycle/Config/PlayerLifecycleConfig.cs, workers/unity/Packages/com.improbable.gdk.playerlifecycle/PlayerLifecycleHelper.cs, workers/unity/Packages/com.improbable.gdk.playerlifecycle/Schema/owning_worker.schema, workers/unity/Packages/com.improbable.gdk.playerlifecycle/Schema/owning_worker.schema.meta, workers/unity/Packages/com.improbable.gdk.playerlifecycle/Systems/PlayerCreation/HandleCreatePlayerRequestSystem.cs
Added an a component to be used when a player is first checked out
Ran it
Pending
=> Added an OwningWorker component and helpers

docs/setup-and-installing.md
Make it a table. Tables are fun. You can put things on them.
Nah
Yeah
@samc-improbable
=> Make setup guide a table

docs/projects/template-fps/setup-and-installing.md
Adding FPS setup guide in Improbadoc format.
Verified it looked good in Improbadoc 😄 
Yes
@samc-improbable
=> Add FPS Setup Guide (SUPER SECRET DON'T LOOK)

workers/unity/Assets/Playground/Config/PlayerTemplate.cs, workers/unity/Packages/com.improbable.gdk.playerlifecycle/Config/PlayerLifecycleConfig.cs, workers/unity/Packages/com.improbable.gdk.playerlifecycle/Systems/PlayerCreation/HandleCreatePlayerRequestSystem.cs
-------
Mainly did it as it was confusing to document something that is not really required anymore.
tested local and cloud deployment
is wip
=> Removes clientAttributeSet argument in CreatePlayerEntityTemplate

.env
Required for docs linting + link checking to work properly
Ran docs linter
N/A
=> Update dotenv with new link

workers/unity/Packages/com.improbable.gdk.buildsystem/Configuration/SpatialOSBuildConfiguration.cs, workers/unity/Packages/com.improbable.gdk.buildsystem/WorkerBuilder.cs
-------
to skip the fake players during build: just ignore them and log a warning instead of throwing an exception.
ran the build. it skipped a testworker I created.
none needed?
=> skipping unknown worker builds instead of failing the build

docs/content/testing/how-to-run-tests.md, docs/content/testing/testing-guidelines.md, docs/content/testing/testing-overview.md, docs/content/testing/testing-systems.md, docs/content/testing/writing-a-new-unit-test.md
Markdown lints + ensuring it looks nicely formatted + links work.
Clicked on the links 
This is docs! 
@samc-improbable @ElleEss
=> Fixup Testing Docs

docs/content/ecs/accessing-worker-info.md, docs/content/ecs/authority.md, docs/content/ecs/commands.md, docs/content/ecs/component-data.md, docs/content/ecs/custom-replication-system.md
=> Fix improbadocs issues for first part of ecs content

docs/content/gameobject/api-workerconnector.md, docs/content/gameobject/create-delete-spos-entries.md, docs/content/gameobject/gomb-creating-workers-with-workerconnector.md, docs/content/gameobject/gomb-world-commands.md, docs/content/gameobject/interact-spos-monobehaviours.md, docs/content/gameobject/linking-spos-entities-gameobjects.md, docs/content/gameobject/linking-workers-gameobjects.md, docs/content/gameobject/readers-writers.md, docs/content/gameobject/reading-and-writing-component-data.md, docs/content/gameobject/sending-receiving-commands.md, docs/content/gameobject/sending-receiving-events.md, docs/content/gameobject/spatialoscomponent.md, docs/content/glossary.md
=> Improbadoc formatting for gameobject docs

docs/content/glossary.md, docs/content/workers/api-worker-system.md, docs/content/workers/api-worker.md, docs/content/workers/worker-entity.md, docs/content/workers/workers-in-the-gdk.md
-------
Also fixes a heading for "Checking Out" in the glossary
=> Fix all links in content\workers\*.md

docs/projects/template-fps/setup-and-installing.md
Broke a link - fixed it. Feel free to change the copy.
=> Fix Broken Link

docs/content/ecs/accessing-worker-info.md, docs/content/ecs/component-data.md, docs/content/ecs/custom-replication-system.md, docs/content/ecs/ecs-component-generation.md, docs/content/ecs/ecs-component-updates.md, docs/content/ecs/ecs-system-update-order.md, docs/content/ecs/ecs-world-commands.md, docs/content/ecs/entity-contracts.md, docs/content/ecs/events.md, docs/content/ecs/logging.md, docs/content/ecs/reactive-components.md, docs/content/ecs/sending-receiving-component-commands.md, docs/content/ecs/temporary-components.md, docs/content/gameobject/api-workerconnector.md, docs/content/gameobject/create-delete-spos-entries.md, docs/content/gameobject/linking-workers-gameobjects.md, docs/content/modules/core-and-feature-module-overview.md, docs/content/modules/player-lifecycle-feature-module.md, docs/content/modules/transform-feature-module.md, docs/content/workers/api-worker-system.md, docs/content/workers/api-worker.md, docs/content/workers/worker-entity.md, docs/content/workers/workers-in-the-gdk.md
This removes the extension only from docs which had a lint pass already to prevent conflicts
=> Remove .md extension from links

docs/content/entity-templates.md
Changes to make improbadoc linting work with entity-templates file.
=> Improbadoc fixes for entity-template

docs/content/world-component-commands-requests-responses.md
=> Fix WCCRR document for improbadoc

docs/welcome.md
-------
I spotted a typo on the welcome page. Also decided to wrap two notes in info callouts on the way.
=> Welcome page style and typo fixed

test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveBlittableSingularTranslation.cs, test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapKeyTranslation.cs, test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapValueTranslation.cs, test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveOptionalTranslation.cs, test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveRepeatedTranslation.cs, test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveSingularTranslation.cs, test-project/Assets/Generated/Source/improbable/gdk/tests/NestedComponentTranslation.cs, test-project/Assets/Generated/Source/improbable/gdk/tests/alternateschemasyntax/ConnectionTranslation.cs, test-project/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponentTranslation.cs, test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsTranslation.cs, test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithCommandsTranslation.cs, test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithEventsTranslation.cs, test-project/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponentTranslation.cs, workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityComponentConversionGenerator.tt
=> Early out when cleaning sometimes

docs/content/ecs/authority.md, docs/license.md
=> Rename Unity GDK -> SpatialOS GDK for Unity

docs/setup-and-installing.md
=> Improve the setup guide

hooks/pre-push
Pre-release prep - tidying up the repo.
=> Remove Hooks Folder

workers/unity/Packages/com.improbable.gdk.buildsystem/package.json, workers/unity/Packages/com.improbable.gdk.core/package.json, workers/unity/Packages/com.improbable.gdk.gameobjectcreation/package.json, workers/unity/Packages/com.improbable.gdk.playerlifecycle/package.json, workers/unity/Packages/com.improbable.gdk.standardlibraryutils/package.json, workers/unity/Packages/com.improbable.gdk.testutils/package.json, workers/unity/Packages/com.improbable.gdk.tools/package.json, workers/unity/Packages/com.improbable.gdk.transformsynchronization/package.json
Updating package versions for release. Will need to update the FPS ones too 
=> Bump Package Versions

docs/content/ecs/authority.md, docs/content/ecs/entity-contracts.md, docs/content/ecs/sending-receiving-component-commands.md, docs/content/gameobject/api-workerconnector.md, docs/content/gameobject/sending-receiving-commands.md, docs/content/gameobject/spatialoscomponent.md, docs/content/glossary.md, docs/content/intro-workflows-spatialos-entities.md, docs/content/testing/testing-guidelines.md, docs/content/testing/testing-systems.md, docs/content/testing/writing-a-new-unit-test.md, docs/get-started.md, docs/projects/fps/tutorial.md
=> doc fixes and adding note to use the 0.1.0 tag

docs/get-started.md, docs/toc.md, docs/welcome.md
=> adding warning and fixing link

ci/bootstrap.sh
We now have a need for shared CI resources between this and the fps project. This script is a placeholder so that we can start doing the work to decouple this repo from any shared resources.
N/A
N/A
=> Add Placeholder Bootstrap

docs/content/build.md, docs/content/troubleshooting.md, docs/get-started.md, docs/setup-and-installing.md
-------
Ref: Discord Unity channel
Improbadoc
Is docs.
@samc-improbable @jessicafalk
=> Linux build support warning added

workers/unity/spatialos.UnityGameLogic.worker.json
=> running gamelogic worker always in headless

docs/content/ecs/commands.md, docs/content/ecs/sending-receiving-component-commands.md
-------
A few snippets had bad syntax
No warnings/errors in local serve
=> Resolve syntax issues in snippets

workers/unity/Packages/com.improbable.gdk.buildsystem/WorkerBuilder.cs
Fix Clean All Workers menu button
=> Fix Clean All Workers menu button

docs/content/build.md, docs/content/troubleshooting.md, docs/get-started.md, docs/setup-and-installing.md
Emergency warning about Unity build dependencies
Improbadoc
Is docs.
@Helcaraxan @anne-edwards (Sam on vacay FYI only)
=> Added warning notes on build dependencies

workers/unity/Assets/link.xml, workers/unity/ProjectSettings/ProjectSettings.asset
-------
This PR adds Unity project settings changes to support iOS and Android. It also corrects IL2CPP assembly linking that is used in iOS.
Tested along with other PRs in `mobile_merge` on iOS and Android devices and simulators
cc @DanailPenev
=> Mobile local dev: Unity project changes + IL2CPP correction

workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/GameObjectWorldCommandSystem.cs, workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Injection/InjectableStore.cs
-------
Removal of some nasty array magic from the hot loop
Tested with local deployment, monobehaviour examples and world commands still work
Very internal
@samiwh @zeroZshadow
=> Use lists instead of hashsets for injectable caching

workers/unity/ProjectSettings/ProjectSettings.asset
-------
Fixed old naming in settings
=> fixing naming in settings

workers/unity/Packages/com.improbable.gdk.buildsystem/package.json, workers/unity/Packages/com.improbable.gdk.core/package.json, workers/unity/Packages/com.improbable.gdk.gameobjectcreation/package.json, workers/unity/Packages/com.improbable.gdk.playerlifecycle/package.json, workers/unity/Packages/com.improbable.gdk.standardlibraryutils/package.json, workers/unity/Packages/com.improbable.gdk.testutils/package.json, workers/unity/Packages/com.improbable.gdk.tools/package.json, workers/unity/Packages/com.improbable.gdk.transformsynchronization/package.json
Release some kind of hungry quadrupeds
=> Upgraded package numbers to 0.1.1

LICENSE.md
-------
`SpatialOS UnityGDK` --> `SpatialOS GDK for Unity`
=> Update name in LICENSE.md

.github/CONTRIBUTING.md, .github/pull_request_template.md, README.md
-------
Fix PR template link to contributions
=> Fix PR template link to contributions

workers/unity/Assets/Playground/Resources/Prefabs/Worker/ClientWorker.prefab, workers/unity/Assets/Playground/Resources/Prefabs/Worker/GameLogicWorker.prefab, workers/unity/Assets/Playground/Resources/Prefabs/Worker/iOSClientWorker.prefab, workers/unity/Assets/Playground/Scenes/ClientScene.unity, workers/unity/Assets/Playground/Scenes/GameLogicScene.unity, workers/unity/Assets/Playground/Scenes/SampleScene.unity, workers/unity/Assets/Playground/Scripts/UI/ConnectionScreenController.cs, workers/unity/Assets/Playground/Scripts/Worker/AndroidClientWorkerConnector.cs, workers/unity/Assets/Playground/Scripts/Worker/ClientWorkerConnector.cs, workers/unity/Assets/Playground/Scripts/Worker/GameLogicWorkerConnector.cs, workers/unity/Assets/Playground/Scripts/Worker/iOSClientWorkerConnector.cs, workers/unity/Packages/com.improbable.gdk.buildsystem/WorkerBuilder.cs, workers/unity/Packages/com.improbable.gdk.core/Worker/WorkerConnector.cs, workers/unity/Packages/com.improbable.gdk.mobile/Worker/MobileWorkerConnector.cs
-------
just my branch for changing a couple of things and fixing connection issues. 
Will probably add more commits as I'm going through stuff
running locally on emulator and phones
docs are wip
=> small mobile fixes

workers/unity/Packages/com.improbable.gdk.tools/LocalLaunch.cs, workers/unity/Packages/com.improbable.gdk.tools/MenuPriorities.cs
Simple FR to add a button to open the inspector
Ran local launch and clicked the button. My browser opened 🎉 
N/A
@jessicafalk
=> Add Open Inspector Button

docs/content/get-started/set-up.md, docs/content/intro-reference.md, docs/content/set-up-new-project.md, docs/toc.md
-------
A table wasn't showing up properly and incorporated some feedback on header names,
ran a preview locally
=> fixing up formatting and reword some headers

ci/docs-build-verification.sh
Fixed a regression in #527 to the `docs-build-verification` script. 
Ran locally - things worked as expected.
=> Fix docs build verification script

docs/content/gameobject/api-workerconnector.md, docs/content/gameobject/creating-workers-with-workerconnector.md
-------
Updating docs to reflect latest changes
=> updating worker connector docs

docs/content/get-started/set-up.md, docs/setup-and-installing.md
-------
Changing unity version everywhere
=> updating docs for unity update

docs/content/get-started/set-up.md
=> update release version in guide

CHANGELOG.md, workers/unity/Packages/com.improbable.gdk.buildsystem/package.json, workers/unity/Packages/com.improbable.gdk.core/package.json, workers/unity/Packages/com.improbable.gdk.gameobjectcreation/package.json, workers/unity/Packages/com.improbable.gdk.mobile/package.json, workers/unity/Packages/com.improbable.gdk.playerlifecycle/package.json, workers/unity/Packages/com.improbable.gdk.standardlibraryutils/package.json, workers/unity/Packages/com.improbable.gdk.testutils/package.json, workers/unity/Packages/com.improbable.gdk.tools/package.json, workers/unity/Packages/com.improbable.gdk.transformsynchronization/package.json
Update package.json and the change log.
=> Release 0.1.2 prep

docs/content/gameobject/create-delete-spatialos-entities.md
Was pointed out on Discord, code snippet would not work as intended.
=> Fix code snippet in world commands doc

docs/projects/blank/overview.md, docs/toc.md, docs/welcome.md
Added the entry to the TOC and wrote some stuff. Please read to make sure it sounds fine 
Welcome page:
Blank project overview:
ToC:
`improbadoc serve ./docs`
=> Add Blank starter project to docs

CHANGELOG.md, README.md
-------
add reference to blank project in the README
looks like:
CI
n/a
=> Add blank project to README

docs/index.md, docs/welcome.md
-------
add blank project to `index.md` - copying over the contents of `welcome.md`
local improbadoc
=> add blank project to index page

test-project/Assets/.Schema/improbable/gdk/tests/exhaustive_test.schema, test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveBlittableSingular.cs, test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveBlittableSingularReaderWriter.cs, test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveBlittableSingularTranslation.cs, test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapKey.cs, test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapKeyProviders.cs, test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapKeyReaderWriter.cs, test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapKeyTranslation.cs, test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapValue.cs, test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapValueProviders.cs, test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapValueReaderWriter.cs, test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapValueTranslation.cs, test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveOptional.cs, test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveOptionalProviders.cs, test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveOptionalReaderWriter.cs, test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveOptionalTranslation.cs, test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveRepeated.cs, test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveRepeatedProviders.cs, test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveRepeatedReaderWriter.cs, test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveRepeatedTranslation.cs, test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveSingular.cs, test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveSingularReaderWriter.cs, test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveSingularTranslation.cs, test-project/Assets/Generated/Source/improbable/gdk/tests/SomeEnum.cs
Title really - first commit is all that matters.
Test project compiled 🎉 
N/A - no release note required for this.
=> UTY-1067: Add enum to test schema

workers/unity/Packages/com.improbable.gdk.core/Config/ConnectionConfig.cs, workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Editor/Prefabs/PrefabPreprocessor.cs, workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Injection/MonoBehaviourActivationManager.cs, workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/Config/LocatorConfigTests.cs, workers/unity/Packages/com.improbable.gdk.core/Utility/EntityBuilder.cs, workers/unity/Packages/com.improbable.gdk.core/Worker/DefaultWorkerConnector.cs
See individual commits for descriptions
=> Kport updates week of 19/11/2018

CHANGELOG.md, workers/unity/Packages/com.improbable.gdk.buildsystem/package.json, workers/unity/Packages/com.improbable.gdk.core/package.json, workers/unity/Packages/com.improbable.gdk.gameobjectcreation/package.json, workers/unity/Packages/com.improbable.gdk.mobile/package.json, workers/unity/Packages/com.improbable.gdk.playerlifecycle/package.json, workers/unity/Packages/com.improbable.gdk.testutils/package.json, workers/unity/Packages/com.improbable.gdk.tools/package.json, workers/unity/Packages/com.improbable.gdk.transformsynchronization/package.json
Release prep - increment versions and update changelog.
Steam stuff purposefully omitted as we don't have a worked example of how to use this.
=> Release 0.1.3 Prep

docs/content/get-started/set-up.md
Updated pinned version to tell people to checkout
=> update pinned hash

docs/welcome.md
Brings in a few extra things users might want to do when they sign up - not everyone wants to / is skilled to get started straight away.
The motivation for this is described [here](https://docs.google.com/document/d/1yhK4kUN3dRktJ9NR_cRnfw0UKF5bCYd1LqHsKc7IYfM/edit#)
The content has been agreed before with @ElleEss  in the Gdoc
I have checked this with improbadoc
=> Welcome page improvements

docs/content/get-started/set-up.md
Added set up restart your machine.
Improbadoc
This is docs.
@jamiebrynes7 @jessicafalk
=> Add step 5 to set up

docs/content/get-started/upload-launch.md
Applied changes to `docs/getting-started.md` based on Andrea's feedback.
=> Docs: Minor fixes external feedback

docs/content/get-started/set-up.md, docs/setup-and-installing.md
Added a sentence about the Unity version and fixed up some formatting (by adding new lines)
=> added warning regarding Unity version

docs/index.md, docs/welcome.md
Small tweaks to formatting to aid clarity.
Also update index.
Improbadoc (attached)
This is docs.
@ernopp
=> Fromatting tweaks to welcome and index docs

workers/unity/Assets/Playground/Config/CubeTemplate.cs, workers/unity/Assets/Playground/Config/PlayerTemplate.cs, workers/unity/Assets/Playground/Editor/SnapshotGenerator/SnapshotGenerator.cs
Previous changes have broken the mobile clients as they didn't have access to player
Run mobile client and ensure it is connecting correctly
=> Fix mobile client read access to PlayerTemplate

docs/content/mobile/overview.md, docs/toc.md
Updates trello links (and the title in TOCs) to our new github roamdap
Tested the links with improbadoc
'tis docs
@ElleEss  @jamiebrynes7
=> Docs: Update roadmap links to Github

CHANGELOG.md, spatialos.json, workers/unity/Packages/com.improbable.gdk.tools/core-sdk.version
Upgrade worker sdk to the stable version 🎉 
Opened Unity, made sure all compiled and was happy.
None required iirc.
Yes
=> Upgrade to stable Worker SDK version

docs/content/get-started/set-up.md, docs/content/get-started/upload-launch.md, docs/setup-and-installing.md
Quick change required for 0.1.4 release. The version of the SDK has changed, just updating the docs to reflect this. Also Unity version
Lots of tests. Promise.
Yes
No
=> Docs - Update SpatialOS & Unity version in tutorial/setup

ci/build-test.sh
Noticed during https://github.com/spatialos/gdk-for-unity-fps-starter-project/pull/92 that we weren't building the client for cloud (Windows & Mac). This fixes that.
=> Build client for cloud in CI

CHANGELOG.md, packer.config.json, workers/unity/Packages/com.improbable.gdk.buildsystem/package.json, workers/unity/Packages/com.improbable.gdk.core/package.json, workers/unity/Packages/com.improbable.gdk.gameobjectcreation/package.json, workers/unity/Packages/com.improbable.gdk.mobile/package.json, workers/unity/Packages/com.improbable.gdk.playerlifecycle/package.json, workers/unity/Packages/com.improbable.gdk.testutils/package.json, workers/unity/Packages/com.improbable.gdk.tools/package.json, workers/unity/Packages/com.improbable.gdk.transformsynchronization/package.json
- Changelog updated.
- Package versions updated.
Note removed the steam auth flow from the changelog as the WIP PR for that was dropped.
Release QA in progress.
Ye
Of course.
=> Release 0.1.4 Prep

docs/content/mobile/android/local-deploy.md, docs/content/mobile/android/ways-to-test.md
Rewrote Android local deployment documentation to use ADB.
Ran local improbadoc and checked that everything looks OK.
=> Local deployment docs for local deployment with ADB

docs/content/connecting-to-spatialos.md, docs/content/gameobject/creating-workers-with-workerconnector.md, docs/content/mobile/android/cloud-deploy.md, docs/content/mobile/ios/cloud-deploy.md, docs/content/mobile/overview.md, docs/toc.md
=> The mobile cloud docs

docs/content/get-started/set-up.md
=> fixing table

ci/docs-build-verification.sh
Need to compare against `develop` rather than `master` for a given PR.
CI will be the judge.
N/A
N/A
=> Fix Docs Branch Verification

README.md
See title ^
Clicked the link.
Yes
No
=> Update roadmap link in readme

README.md
Even more badges. Shows the state of the `develop` branch. 
Looked at README
=> Build Badge! More Badges!

.buildkite/premerge.definition.yaml
master -> develop
Buildkite tests
N/A
N/A
=> Update Buildkite Default Branch

CHANGELOG.md, workers/unity/Packages/com.improbable.gdk.buildsystem/WorkerBuilder.cs, workers/unity/Packages/com.improbable.gdk.mobile/Editor/LaunchMenu.cs, workers/unity/Packages/com.improbable.gdk.tools/DownloadCoreSdk.cs, workers/unity/Packages/com.improbable.gdk.tools/GenerateCode.cs, workers/unity/Packages/com.improbable.gdk.tools/LocalLaunch.cs, workers/unity/Packages/com.improbable.gdk.tools/RedirectedProcess.cs
Following the https://github.com/spatialos/gdk-for-unity/pull/670/files I've tried the idea to rework RedirectedProcess to have Builder API
Ensure the code using RedirectedProcess runs the same
=> Rework RedirectProccess to have Builder API

workers/unity/Packages/com.improbable.gdk.core/Worker/WorkerConnector.cs, workers/unity/Packages/com.improbable.gdk.mobile/Worker/MobileWorkerConnector.cs
multiple smaller things:
- printing stacktrace
- making a private field protected so that I can use it in the inherited classes
ran it local and cloud
none needed
**Did you remember a changelog entry?** do I need one for this?
=> Small changes to worker connector

docs/content/troubleshooting.md
Correctly wrongly written name.
Improbadoc
This is the docs.
N/A
Anyone
=> Correct name

ci/build-ios.sh, ci/build-test.sh, ci/pack.sh, ci/upload-launch.sh
Fix shell script which has `set` options in the wrong order
=> CI pipefail fix

docs/content/mobile/ios/local-deploy.md
A small fix for a numbered list so that is renders sequentially rather than restarting at 1 mid way thought.
@ElleEss
=> fix the rendering of the numered list

workers/unity/Packages/com.improbable.gdk.gameobjectcreation/GameObjectCreationHelper.cs, workers/unity/Packages/com.improbable.gdk.gameobjectcreation/GameObjectInitializationSystem.cs
Re enabled the old worker gameobject flow
=> Enable worker entity linking

workers/unity/Packages/com.improbable.gdk.transformsynchronization/MonoBehaviours/TransformSynchronization.cs, workers/unity/Packages/com.improbable.gdk.transformsynchronization/Systems/DefaultApplyLatestTransformSystem.cs, workers/unity/Packages/com.improbable.gdk.transformsynchronization/Systems/DefaultUpdateLatestTransformSystem.cs, workers/unity/Packages/com.improbable.gdk.transformsynchronization/Systems/DirectTransformUpdateSystem.cs, workers/unity/Packages/com.improbable.gdk.transformsynchronization/Systems/GetTransformValueToSetSystem.cs, workers/unity/Packages/com.improbable.gdk.transformsynchronization/Systems/InterpolateTransformSystem.cs, workers/unity/Packages/com.improbable.gdk.transformsynchronization/Systems/RateLimitedPositionSendSystem.cs, workers/unity/Packages/com.improbable.gdk.transformsynchronization/Systems/RateLimitedTransformSendSystem.cs, workers/unity/Packages/com.improbable.gdk.transformsynchronization/Systems/ResetForAuthorityGainedSystem.cs, workers/unity/Packages/com.improbable.gdk.transformsynchronization/Systems/SetKinematicFromAuthoritySystem.cs, workers/unity/Packages/com.improbable.gdk.transformsynchronization/Systems/TickSystem.cs
Removed reactive components from transforms.
=> Moved transforms off reactive components

docs/content/get-started/set-up.md, docs/content/initial-set-up.md, docs/setup-and-installing.md
Docs: Upgrade the documented Unity version to 2018.3.5
=> Docs: Upgrade the documented Unity version to 2018.3.5

workers/unity/Packages/com.improbable.gdk.playerlifecycle/Systems/PlayerCreation/HandleCreatePlayerRequestSystem.cs, workers/unity/Packages/com.improbable.gdk.playerlifecycle/Systems/PlayerCreation/SendCreatePlayerRequestSystem.cs, workers/unity/Packages/com.improbable.gdk.playerlifecycle/Systems/PlayerHeartbeat/HandlePlayerHeartbeatRequestSystem.cs, workers/unity/Packages/com.improbable.gdk.playerlifecycle/Systems/PlayerHeartbeat/HandlePlayerHeartbeatResponseSystem.cs, workers/unity/Packages/com.improbable.gdk.playerlifecycle/Systems/PlayerHeartbeat/SendPlayerHeartbeatRequestSystem.cs
Re-implemented the Lifecycle systems using the new CommandSystem
Tested locally, runningly kicking off a cloud build to double check.
=> Lifecycle API validation

ci/test.sh, workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/CodeGeneration/Tests/FileHandling/MockFile.cs, workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/CodeGeneration/Tests/FileHandling/MockFileSystem.cs, workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/CodeGeneration/Tests/Jobs/CodegenJobTests.cs, workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/CodeGeneration/Tests/Model/SchemaBundleV1/JsonParsingTests.cs, workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/CodeGeneration/Tests/Utils/FormattingTests.cs, workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Tests/Model/DetailsStoreTests.cs
Added many tests to the code generator:
- `Formatting` tests
- `CodegenJob` tests
- `DetailStore` tests
Also added some mocks for:
- `MockFile : IFile`
- `MockFileSystem : IFileSystem`
These work by maintaining a tree data structure of what files and directories are there. It doesn't support reading/writing data and doesn't support searching patterns on `GetFilesInDirectory` (doesn't actually appear to be used anywhere?).
Yes I am tests.
N/A
=> UTY-1752: Schema Bundle Tests

CHANGELOG.md, packer.config.json, workers/unity/Assets/Playground/Config/BuildConfiguration.asset, workers/unity/Packages/com.improbable.gdk.buildsystem/package.json, workers/unity/Packages/com.improbable.gdk.core/package.json, workers/unity/Packages/com.improbable.gdk.gameobjectcreation/package.json, workers/unity/Packages/com.improbable.gdk.mobile/package.json, workers/unity/Packages/com.improbable.gdk.playerlifecycle/package.json, workers/unity/Packages/com.improbable.gdk.testutils/package.json, workers/unity/Packages/com.improbable.gdk.tools/package.json, workers/unity/Packages/com.improbable.gdk.transformsynchronization/package.json
I've made all the changes listed in https://github.com/spatialos/gdk-for-unity/wiki/Release-Process and am now opening a PR to pull this branch into `develop` as per that process.
None yet, I'm about to run validation steps.
Noted the release in the changelog.
@jamiebrynes7
=> `0.1.5` release pre-validation

workers/unity/Packages/com.improbable.gdk.core/Collections/ReceivedMessageList.cs, workers/unity/Packages/com.improbable.gdk.core/Systems/ComponentUpdateSystem.cs, workers/unity/Packages/com.improbable.gdk.core/Systems/SpatialOSReceiveSystem.cs, workers/unity/Packages/com.improbable.gdk.core/Systems/WorkerSystem.cs, workers/unity/Packages/com.improbable.gdk.core/UpdatesAndEvents/ComponentManagers.cs, workers/unity/Packages/com.improbable.gdk.core/Worker/DiffStorage.cs, workers/unity/Packages/com.improbable.gdk.core/Worker/ViewDiff.cs, workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/CommandDiffStorageGenerator.tt, workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/ComponentDiffDeserializerGenerator.tt, workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/ComponentDiffStorageGenerator.tt, workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityComponentUpdateManagerGenerator.tt
Remove the list swapping for component updates
=> remove component swaps

docs/content/mobile/ios/cloud-deploy.md, docs/content/mobile/ios/local-deploy.md
Correctly refer to the Project Settings window.
=> Correctly refer to the Project Settings window.

workers/unity/Packages/com.improbable.gdk.core/Systems/ComponentSendSystem.cs, workers/unity/Packages/com.improbable.gdk.core/Systems/ComponentUpdateSystem.cs, workers/unity/Packages/com.improbable.gdk.core/Systems/EcsViewSystem.cs, workers/unity/Packages/com.improbable.gdk.core/Systems/EcsViewSystem.cs.meta, workers/unity/Packages/com.improbable.gdk.core/Systems/SpatialOSReceiveSystem.cs, workers/unity/Packages/com.improbable.gdk.core/Systems/SpatialOSSendSystem.cs, workers/unity/Packages/com.improbable.gdk.core/Systems/SpatialOSSendSystem.cs.meta, workers/unity/Packages/com.improbable.gdk.core/Systems/UpdateGroups.cs, workers/unity/Packages/com.improbable.gdk.core/UpdatesAndEvents/ComponentManagers.cs, workers/unity/Packages/com.improbable.gdk.core/View/View.cs, workers/unity/Packages/com.improbable.gdk.core/View/ViewStorage.cs, workers/unity/Packages/com.improbable.gdk.core/Worker/Worker.cs, workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/GdkCodeGenerator.csproj, workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityEcsViewManagerGenerator.tt, workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/ViewStorageGenerator.tt, workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/src/Generation/Generators/Parts/UnityEcsViewManagerGeneratorPart.cs, workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/src/Generation/SingleGenerationJob.cs
The ecs view is now updated from its own system.
The component update system now uses the view rather than the update mangers
=> Separate the ecs view from other systems

workers/unity/Packages/com.improbable.gdk.core/Subscriptions/EntityGameObjectLinker.cs, workers/unity/Packages/com.improbable.gdk.core/Subscriptions/EntitySubscriptions.cs, workers/unity/Packages/com.improbable.gdk.core/Subscriptions/LinkedEntityComponent.cs, workers/unity/Packages/com.improbable.gdk.core/Subscriptions/RequiredSubscriptionsInjector.cs, workers/unity/Packages/com.improbable.gdk.core/Subscriptions/Systems/SubscriptionSystem.cs, workers/unity/Packages/com.improbable.gdk.core/Systems/SpatialOSReceiveSystem.cs, workers/unity/Packages/com.improbable.gdk.core/Worker/ConnectionHandlers/SpatialOSConnectionHandler.cs, workers/unity/Packages/com.improbable.gdk.gameobjectcreation/GameObjectInitializationSystem.cs, workers/unity/Packages/com.improbable.gdk.transformsynchronization/MonoBehaviours/TransformSynchronization.cs
Changes found while upgrading the fps starter project
=> fps upgrade fixes

workers/unity/Packages/com.improbable.gdk.core/Subscriptions/EntityGameObjectLinker.cs, workers/unity/Packages/com.improbable.gdk.core/Subscriptions/EntitySubscriptions.cs, workers/unity/Packages/com.improbable.gdk.core/Subscriptions/LinkedEntityComponent.cs, workers/unity/Packages/com.improbable.gdk.core/Subscriptions/Systems/SubscriptionSystem.cs, workers/unity/Packages/com.improbable.gdk.core/Systems/SpatialOSReceiveSystem.cs, workers/unity/Packages/com.improbable.gdk.core/Worker/ConnectionHandlers/SpatialOSConnectionHandler.cs, workers/unity/Packages/com.improbable.gdk.gameobjectcreation/GameObjectInitializationSystem.cs, workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityCommandSenderReceiverGenerator.tt, workers/unity/Packages/com.improbable.gdk.transformsynchronization/MonoBehaviours/TransformSynchronization.cs
Fixed being able to link against a worker entity
=> Fixed an error when linking a gameobject to an invalid entity

test-project/Assets/EditmodeTests/Subscriptions/ReaderWriter/InjectionCriteriaTests.cs
=> Fix tests in experimental branch

docs/projects/fps/tutorial.md
=> Update tutorial code snippet

docs/toc.md
Moved - [Create and delete SpatialOS entities]({{urlRoot}}/content/gameobject/create-delete-spatialos-entities) ToC entry to its proper place. 
Local Improbadoc
=> Move ToC Entry

workers/unity/Packages/com.improbable.gdk.core/Subscriptions/Callbacks.cs, workers/unity/Packages/com.improbable.gdk.core/Subscriptions/Systems/RequireLifecycleSystem.cs, workers/unity/Packages/com.improbable.gdk.core/Systems/EntitySystem.cs, workers/unity/Packages/com.improbable.gdk.core/View/View.cs, workers/unity/Packages/com.improbable.gdk.core/Worker/SerializedMessagesToSend.cs
Fixed a bug in getting entities in the view and in registering indexed callbacks.
=> More fixes found from the fps starter project upgrade

CHANGELOG.md, workers/unity/Assets/Playground/Resources/Prefabs/Common/Character.prefab, workers/unity/Assets/Playground/Resources/Prefabs/Common/Cube.prefab, workers/unity/Assets/Playground/Resources/Prefabs/Common/MobileConnectionSplashScreen.prefab, workers/unity/Assets/Playground/Resources/Prefabs/Common/Spinner.prefab, workers/unity/Assets/Playground/Resources/Prefabs/Level.prefab, workers/unity/Assets/Playground/Resources/Prefabs/UIGameObject.prefab, workers/unity/Assets/Playground/Resources/Prefabs/UnityGameLogic/Cube.prefab, workers/unity/Assets/Playground/Resources/Prefabs/Worker/AndroidClientWorker.prefab, workers/unity/Assets/Playground/Resources/Prefabs/Worker/ClientWorker.prefab, workers/unity/Assets/Playground/Resources/Prefabs/Worker/GameLogicWorker.prefab, workers/unity/Assets/Playground/Resources/Prefabs/Worker/iOSClientWorker.prefab, workers/unity/Packages/com.improbable.gdk.core/Subscriptions/Editor/Prefabs/PrefabPreprocessor.cs
The prefab processor was not yet using the new Prefab editing API's, causing issues when upgrading from the SDK to the GDK.
This small PR fixes this issue, and adds some additional logging to identify problematic prefabs
Tested with playground
=> Fix prefab processor

CHANGELOG.md, test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapKey.cs, test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapValue.cs, test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveOptional.cs, test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveRepeated.cs, test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveSingular.cs, test-project/Assets/Generated/Source/improbable/gdk/tests/NestedComponent.cs, test-project/Assets/Generated/Source/improbable/gdk/tests/alternateschemasyntax/Connection.cs, test-project/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponent.cs, test-project/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponent.cs, workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityComponentDataGenerator.tt, workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/src/Generation/Generators/Parts/UnityComponentDataGeneratorPart.cs
Added snapshot constructors - does what is says on the tin really.
Will be rebased and merged after #788 is merged.
Generated code - looked good.
N/A
Yes
=> Add Snapshot Constructors

workers/unity/Packages/com.improbable.gdk.core/CodegenAdapters/IComponentReplicationHandler.cs, workers/unity/Packages/com.improbable.gdk.core/Systems/ComponentSendSystem.cs, workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/Systems/SpatialOSSendSystemTests.cs, workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityComponentSenderGenerator.tt
Made a small change to make use of the job system to significantly speed up the ComponentSendSystem
Tested with playground
Internal change, needs to docs.
=> Large performance boost for ComponentSendSystem

workers/unity/Packages/com.improbable.gdk.playerlifecycle/Systems/PlayerCreation/SendCreatePlayerRequestSystem.cs
Re-enable spawn retries
Tested in playground
=> A failed spawn player command is now retried again

docs/projects/fps/tutorial.md
* Clarifies the prefab duplication workflow.
* Clarifies where to edit snapshot generation script.
=> Clarify the prefab duplication workflow.

test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapKeyViewStorage.cs, test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapValueViewStorage.cs, test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveOptionalViewStorage.cs, test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveRepeatedViewStorage.cs, test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveSingularViewStorage.cs, test-project/Assets/Generated/Source/improbable/gdk/tests/NestedComponentViewStorage.cs, test-project/Assets/Generated/Source/improbable/gdk/tests/alternateschemasyntax/ConnectionViewStorage.cs, test-project/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponentViewStorage.cs, test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsViewStorage.cs, test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithCommandsViewStorage.cs, test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithEventsViewStorage.cs, test-project/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponentViewStorage.cs, workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/ViewStorageGenerator.tt
Temporary fix until we handle loopbacks properly. cc @samiwh 
Will make a ticket for this.
Ran it
N/A
=> Fix a race on component update loopbacks

test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapKeyComponentDiffDeserializer.cs, test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapKeyEcsViewManager.cs, test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapValueComponentDiffDeserializer.cs, test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapValueEcsViewManager.cs, test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveOptionalComponentDiffDeserializer.cs, test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveOptionalEcsViewManager.cs, test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveRepeatedComponentDiffDeserializer.cs, test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveRepeatedEcsViewManager.cs, test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveSingularComponentDiffDeserializer.cs, test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveSingularEcsViewManager.cs, test-project/Assets/Generated/Source/improbable/gdk/tests/NestedComponentComponentDiffDeserializer.cs, test-project/Assets/Generated/Source/improbable/gdk/tests/NestedComponentEcsViewManager.cs, test-project/Assets/Generated/Source/improbable/gdk/tests/alternateschemasyntax/ConnectionComponentDiffDeserializer.cs, test-project/Assets/Generated/Source/improbable/gdk/tests/alternateschemasyntax/ConnectionEcsViewManager.cs, test-project/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponentComponentDiffDeserializer.cs, test-project/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponentEcsViewManager.cs, test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsComponentDiffDeserializer.cs, test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsEcsViewManager.cs, test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithCommandsComponentDiffDeserializer.cs, test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithCommandsEcsViewManager.cs, test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithEventsComponentDiffDeserializer.cs, test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithEventsEcsViewManager.cs, test-project/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponentComponentDiffDeserializer.cs, test-project/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponentEcsViewManager.cs, workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/ComponentDiffDeserializerGenerator.tt
Workaround for the crash we have been seeing in cloud deployments until a permanent fix is put into place.
Many deployments were ran.
Nah
Doesn't need one.
=> Crash Workaround

workers/unity/Assets/Playground/Config/BuildConfiguration.asset, workers/unity/Packages/com.improbable.gdk.core/ReactiveComponents/CodegenAdapters/AcknowledgeAuthorityLossHandler.cs, workers/unity/Packages/com.improbable.gdk.core/ReactiveComponents/CodegenAdapters/ComponentCleanupHandler.cs, workers/unity/Packages/com.improbable.gdk.core/ReactiveComponents/CodegenAdapters/IReactiveComponentReplicationHandler.cs, workers/unity/Packages/com.improbable.gdk.core/ReactiveComponents/Systems/AcknowledgeAuthorityLossSystem.cs, workers/unity/Packages/com.improbable.gdk.core/ReactiveComponents/Systems/CleanReactiveComponentsSystem.cs, workers/unity/Packages/com.improbable.gdk.core/ReactiveComponents/Systems/ReactiveComponentSendSystem.cs, workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityReactiveComponentHandlersGenerator.tt
Reactive Systems now use concurrent jobs for chunk gathering
ReactiveComponentSendSystem order of sending has been changed to better cache usage
Local UnityGameLogic build is now a Development build
Ran playground project using editor and build out workers
=> Reactive Systems now use concurrent jobs for chunk gathering

workers/unity/Packages/com.improbable.gdk.core/ReactiveComponents/Systems/AcknowledgeAuthorityLossSystem.cs, workers/unity/Packages/com.improbable.gdk.core/ReactiveComponents/Systems/CleanReactiveComponentsSystem.cs, workers/unity/Packages/com.improbable.gdk.core/ReactiveComponents/Systems/ReactiveComponentSendSystem.cs, workers/unity/Packages/com.improbable.gdk.core/Systems/ComponentSendSystem.cs
Oops I forgot to generate the test code.
Tiny quick changes to cache jobhandles
Generated test code, ran tests, all green
Playground still works
=> Reactive small changes

docs/projects/fps/tutorial.md
=> Updated the tutorial for core 0.2

CHANGELOG.md
=> Change-log typo

CHANGELOG.md
=> Added Laura's feedback to changelog

docs/content/get-started/build-workers.md, docs/content/modules/core-and-feature-module-overview.md, docs/content/modules/player-lifecycle-feature-module.md
updated docs to mention:
* how to pass arbitrary data (incl serialization/deserialization)
* how to enable/disable automatic player creation
this is the documentation
=> Player lifecycle docs update

CHANGELOG.md, packer.config.json, workers/unity/Packages/com.improbable.gdk.buildsystem/package.json, workers/unity/Packages/com.improbable.gdk.core/package.json, workers/unity/Packages/com.improbable.gdk.gameobjectcreation/package.json, workers/unity/Packages/com.improbable.gdk.mobile/package.json, workers/unity/Packages/com.improbable.gdk.playerlifecycle/package.json, workers/unity/Packages/com.improbable.gdk.testutils/package.json, workers/unity/Packages/com.improbable.gdk.tools/package.json, workers/unity/Packages/com.improbable.gdk.transformsynchronization/package.json
I've made all the changes listed in https://github.com/spatialos/gdk-for-unity/wiki/Release-Process and am now opening a PR to pull this branch into develop as per that process.
Updated changelog
@oblm
=>  `0.2.0` release pre-validation

docs/content/ecs/sending-receiving-component-commands.md, docs/content/gameobject/sending-receiving-commands.md, docs/content/gameobject/world-commands.md, docs/content/world-component-commands-requests-responses.md, docs/projects/blank/overview.md
Fixing some typos and formatting issues
improbadoc + visual check in docs-staging
=> 0.2.0 docs live patch

docs/toc.md
Because includes are magic apparently
=> Explicitly include toc

ci/generate-docs.sh
Quick change to the target branch for the generate docs script. 
Ran it.
N/A
=> Update generate docs script to use new docs branches

.buildkite/release-qa.steps.yaml
Looks like we forgot to change them both.
=> Bump BK queue ID

docs/content/get-started/set-up.md
=> Fix little typo

docs/projects/fps/tutorial.md
Some changes to the tutorial: 
- A bit more focus on design constraints
- Remove outdated explanations
- Formatting changes.
=> Health packs tutorial tweaks

docs/projects/fps/tutorial.md
Fixes encountered while running through the tutorial fully.
=> FPS tutorial fixes

CHANGELOG.md, README.md, workers/unity/Packages/com.improbable.gdk.core/package.json, workers/unity/Packages/com.improbable.gdk.playerlifecycle/package.json
Fix package dependencies
Quick bug fix in compile order
Tested with FPS and Playground
=> Fix package dependencies

docs/content/get-started/get-started.md
Until we can update the master readme - we need this redirect.
=> Add a redirect

docs/content/get-started/get-started.md
=> Fast forward docs-next

docs/reference/troubleshooting.md
Refreshed the troubleshooting docs: 
- Removed entries that are not specific to the GDK
- Reformatted it.
- Added Toc back in.
`improbadoc serve`
=> Update troubleshooting documentation

docs/reference/troubleshooting.md
Cherry-picked #881 into docs-next
=> Cherry pick troubleshooting docs

docs/reference/mobile/overview.md
added warning that mobile is still in pre-alpha.
Also changed cross-platform wording a bit as the GDK.
checked docs locally
=> adding mobile pre-alpha warning

docs/modules/game-object-creation/custom-usage.md, docs/modules/game-object-creation/standard-usage.md
=> Fix docs typo

docs/modules/build-system/build-config.md, docs/modules/build-system/cli.md, docs/modules/build-system/editor-menu.md, docs/modules/build-system/overview.md, docs/modules/core-and-feature-module-overview.md, docs/projects/myo/build.md, docs/toc.md
Added lots of documentation about the build system:
- Build configuration
- CLI option
- Editor menu description
`improbadoc serve`. PM for live preview.
Ye
=> Update and expand Build System feature module documentation

docs/modules/build-system/build-config.md, docs/modules/build-system/cli.md, docs/modules/build-system/editor-menu.md, docs/modules/build-system/overview.md, docs/modules/core-and-feature-module-overview.md, docs/projects/myo/build.md, docs/toc.md
=> Cherry pick build system changes to docs next

workers/unity/Packages/com.improbable.gdk.playerlifecycle/Config/PlayerLifecycleConfig.cs
Fix xml docs for player lifecycle config
CI
this is the doc
=> Fix xml docs for player lifecycle config

docs/content/get-started/get-started.md
Added a redirect while the README in `master` pointed to this link. Removing the redirect for the next release.
=> Remove Redirect

docs/reference/concepts/code-generation.md, docs/reference/concepts/entity-templates.md, docs/toc.md
Removed code samples that: weren't particularly useful, and likely to go stale. Removed a lot of wordiness.
At this point, I kind of doubt the usefulness of this page outside of the type mappings.
Local improbadoc serve.
=> Refresh code generator section

docs/reference/concepts/code-generation.md, docs/reference/concepts/entity-templates.md, docs/toc.md
update docs-next with https://github.com/spatialos/gdk-for-unity/pull/897
n/a
this is the documentation
=> Refresh code generator section (#897)

CHANGELOG.md, cloud_launch.json, default_launch.json, workers/unity/Packages/com.improbable.gdk.playerlifecycle/Systems/PlayerCreation/SendCreatePlayerRequestSystem.cs, workers/unity/ProjectSettings/ProjectSettings.asset
Fixes project settings and Changelog for UTY-1963
Some switch related project settings snuck in as unity re-serialized the project settings.
=> Reactive components quickfix

workers/unity/Packages/com.improbable.gdk.tools/RedirectedProcess.cs
Ran the deployment launcher. Didn't freeze
N/A - fixing a regression introduced earlier.
@jessicafalk
=> Stop things freezing in FPS

docs/fragments/machine-setup.md
See title. Verified with running `grep -r "2018.3.5" .` in the repo. No results.
=> Update Unity version in docs

CHANGELOG.md, packer.config.json, test-project/Packages/com.improbable.gdk.dependencytest/package.json, test-project/Packages/com.improbable.gdk.dependencytestchild/package.json, test-project/Packages/com.improbable.gdk.dependencytestgrandchild/package.json, workers/unity/Packages/com.improbable.gdk.buildsystem/package.json, workers/unity/Packages/com.improbable.gdk.core/package.json, workers/unity/Packages/com.improbable.gdk.gameobjectcreation/package.json, workers/unity/Packages/com.improbable.gdk.mobile/package.json, workers/unity/Packages/com.improbable.gdk.playerlifecycle/package.json, workers/unity/Packages/com.improbable.gdk.querybasedinteresthelper/package.json, workers/unity/Packages/com.improbable.gdk.testutils/package.json, workers/unity/Packages/com.improbable.gdk.tools/package.json, workers/unity/Packages/com.improbable.gdk.transformsynchronization/package.json
=> Release 0.2.1 - Pre-Validation

docs/reference/concepts/connection-flows.md
- Removed some wordiness
- Removed duplication and link to existing docs instead.
- Added instructions for a debugging workflow.
- Removed not-very-helpful section about protocol logging, this is the wrong place to talk about this. Will raise a ticket to add it in properly.
`improbadoc serve` 
Yes
=> Refreshed connection flows section

.buildkite/hooks/post-checkout, .buildkite/premerge.steps.yaml, .buildkite/release-qa.steps.yaml, ci/bootstrap.sh
PR fixes BK git issues, but looks like we may have a flakey package downloading behaviour? 
Will do a few runs to test
=> Buildkite Fix

docs/modules/transform-sync/setup-transform.md
Some minor fixes for typos in the docs.
=> Assorted typo fixes in docs

.buildkite/premerge.steps.yaml, .buildkite/release-qa.steps.yaml
=> ENG-1276: enable all bk output to get logged, not just command

workers/unity/Packages/com.improbable.gdk.tools/Common.cs
Discovered by @jared-improbable the link in the popup is broken. This fixes it
=> Fix link to machine setup.

docs/fragments/machine-setup.md
update dotnet core sdk version + link
improbadoc serve + followed links
this is the documentation
=> Update dotnet core sdk version + link

docs/modules/core-and-feature-module-overview.md
Add deployment launcher to feature module overview
improbadoc serve
=> Add deployment launcher to feature module overview

CHANGELOG.md, workers/unity/Packages/com.improbable.gdk.tools/DevAuthTokenUtils.cs
Fix for UTY-2026 (DAT file imported with invalid path)
tested in editor - no more warnings
added changelog entry for 0.2.2
=> Import DAT file using relative path

docs/modules/deployment-launcher/launch-deployments.md, docs/modules/deployment-launcher/manage-deployments.md, docs/modules/deployment-launcher/upload-assemblies.md, docs/projects/fps/get-started/upload-launch.md, docs/projects/myo/setup.md, docs/reference/glossary.md
- move input validation sections to expandables
- add simulated player/coordinator to glossary
improbadoc serve
this is the documentation
=> 0.2.2 docs fixes

docs/projects/fps/get-started/upload-launch.md
Minor docs nits 0.2.2
improbadoc serve
this is the documentation 
=> Minor docs nits 0.2.2

.buildkite/premerge.steps.yaml, .buildkite/release-qa.steps.yaml, CHANGELOG.md, test-project/ProjectSettings/ProjectVersion.txt, test-project/ProjectSettings/XRSettings.asset, workers/unity/Packages/manifest.json, workers/unity/ProjectSettings/ProjectVersion.txt, workers/unity/ProjectSettings/XRSettings.asset
Upgrading to Unity 2019.1.3f1
Upgrade toolbelt pin to latest
Upgraded and run locally
Cloud TODO
Changelog added
=> Unity 2019.1.3f1 upgrade

workers/unity/Packages/com.improbable.gdk.transformsynchronization/Systems/DefaultApplyLatestTransformSystem.cs, workers/unity/Packages/com.improbable.gdk.transformsynchronization/Systems/DefaultUpdateLatestTransformSystem.cs, workers/unity/Packages/com.improbable.gdk.transformsynchronization/Systems/DirectTransformUpdateSystem.cs, workers/unity/Packages/com.improbable.gdk.transformsynchronization/Systems/GetTransformValueToSetSystem.cs, workers/unity/Packages/com.improbable.gdk.transformsynchronization/Systems/InterpolateTransformSystem.cs, workers/unity/Packages/com.improbable.gdk.transformsynchronization/Systems/RateLimitedPositionSendSystem.cs, workers/unity/Packages/com.improbable.gdk.transformsynchronization/Systems/RateLimitedTransformSendSystem.cs, workers/unity/Packages/com.improbable.gdk.transformsynchronization/Systems/SetKinematicFromAuthoritySystem.cs, workers/unity/Packages/com.improbable.gdk.transformsynchronization/Systems/TickRateEstimationSystem.cs
Seems replace all did not replace all, and find didn't find them.
I've replaced the missed functions
=> Missed obsolete managers

docs/projects/fps/tutorial.md
Hotfix for broken code snippets (few other changes as suggested in feedback)
=> Fix tutorial

docs/projects/fps/tutorial.md
Cherry-picked #993 into docs-next
=> Tutorial hotfix cherry-pick

docs/projects/fps/get-started/set-up.md
links to the correct blog + update text because it's not specifically a games blog anymore
improbadoc serve
=> Fix blog link in get-started set-up page

docs/projects/fps/get-started/set-up.md
cherry pick from docs-current
diff looks sane
=> cherry pick blog link fix in get-started set-up page (#996)

workers/unity/Packages/com.improbable.gdk.mobile/Editor/AndroidLaunchUtils.cs, workers/unity/Packages/com.improbable.gdk.mobile/Editor/MobileLauncherWindow.cs
Quick fix for a label in the mobile launcher.
language approved by Laura
Drive by fix of DirectoryNotFound exception for android.
=> Mobile launcher label fix

docs/modules/transform-sync/how-it-works.md
- update schema snippet
- update an expandable on reasons why position/transform separate
- improbadoc serve
=> Update docs post-transform module update

CHANGELOG.md, UPGRADE_GUIDE.md, packer.config.json, workers/unity/Packages/com.improbable.gdk.buildsystem/package.json, workers/unity/Packages/com.improbable.gdk.core/package.json, workers/unity/Packages/com.improbable.gdk.deploymentlauncher/package.json, workers/unity/Packages/com.improbable.gdk.gameobjectcreation/package.json, workers/unity/Packages/com.improbable.gdk.mobile/package.json, workers/unity/Packages/com.improbable.gdk.playerlifecycle/package.json, workers/unity/Packages/com.improbable.gdk.querybasedinteresthelper/package.json, workers/unity/Packages/com.improbable.gdk.testutils/package.json, workers/unity/Packages/com.improbable.gdk.tools/package.json, workers/unity/Packages/com.improbable.gdk.transformsynchronization/package.json
- Package versions
- Changelog
- Upgrade guide
- Windows
- Mac
- Android
- iOS
=> Release 0.2.4

docs/modules/deployment-launcher/overview.md, docs/modules/mobile/cloud-deploy.md, docs/modules/mobile/local-deploy.md, docs/modules/mobile/overview.md, docs/modules/mobile/prepare-project.md, docs/modules/mobile/run-client.md
Updated mobile docs for new Mobile Window
+ Drive-by on Deployment launcher menu path
=> Mobile launcher docs

.buildkite/premerge.steps.yaml, .buildkite/release-qa.steps.yaml, ci/bootstrap.sh, test-project/Packages/manifest.json
- Added the SDK downloading to the bootstrap script
- New agent queue which has `jq` built in.
CI is our guide.
N/A
=> Fix NPM CI

docs/modules/core-and-feature-module-overview.md, docs/projects/blank/overview.md, docs/projects/fps/get-started/get-started.md, docs/projects/fps/overview.md, docs/reference/glossary.md
- update broken links
- remove djangogirls link
- copied across from `docs/pipeline` branch
n/a
=> cherry-pick linting fixes

CHANGELOG.md, test-project/Assets/EditmodeTests/Improbable.Gdk.EditModeTests.asmdef, test-project/Assets/EditmodeTests/PlayerLifecycle.meta, test-project/Assets/EditmodeTests/PlayerLifecycle/PlayerLifecycleHelperTests.cs, test-project/Assets/EditmodeTests/PlayerLifecycle/PlayerLifecycleHelperTests.cs.meta, test-project/Packages/manifest.json, workers/unity/Packages/io.improbable.gdk.playerlifecycle/PlayerLifecycleHelper.cs
Fixed the bug described by #1026 and added test coverage for this method.
=> Fix `PlayerLifecycleHelper.IsOwningWorker`

workers/unity/Assets/Playground/Config/BuildConfiguration.asset
Scene GUID's changed in a merge somewhere, fixed the id's for building
=> Set the correct worker scenes in the buildconfig

workers/unity/Packages/io.improbable.gdk.mobile/package.json
=> Fix mobile package version dependency

docs/.hiddendocs, docs/modules/build-system/overview.md, docs/modules/deployment-launcher/overview.md, docs/modules/game-object-creation/overview.md, docs/modules/game-object-creation/standard-usage.md, docs/modules/mobile/overview.md, docs/modules/player-lifecycle/overview.md, docs/modules/qbi-helper/overview.md, docs/modules/transform-sync/overview.md, docs/projects/fps/get-started/build-workers.md, docs/projects/fps/get-started/get-playing.md, docs/projects/fps/get-started/get-started.md, docs/projects/fps/get-started/set-up.md, docs/projects/myo/setup.md, docs/reference/glossary.md, docs/toc.md, docs/variable.properties
Updated documentation on project and feature module installation to use NPM packages.
Small drive by on fixing links containing file extensions and mentions of Unity ECS injection.
=> Upgrade docs for NPM

docs/modules/player-lifecycle/custom-player-creation.md, docs/reference/concepts/logging.md
there were still a few references to `GetExistingManager`. Replaced them with `GetExistingSystem`.
=> Replace GetExistingManager with GetExistingSystem

docs/modules/player-lifecycle/custom-player-creation.md, docs/reference/concepts/logging.md
cherry-picked from https://github.com/spatialos/gdk-for-unity/pull/1050 for `docs-next` branch
=> replacing GetExistingManager with GetExistingSystem (#1050)

docs/reference/workflows/ecs/interaction/reactive-components/overview.md
Docs to go along with #1059. Simply updated the disclaimer and added our intent to remove these in the future.
=> Reactive components docs updates

docs/modules/core-and-feature-module-overview.md, docs/projects/fps/get-started/set-up.md, docs/projects/fps/get-started/upload-launch.md, docs/reference/concepts/worker.md, docs/reference/glossary.md
- Tidied entries up
- Removed unnecessary ones
- Fixed ToC formatting
- Cleaned up formatting
=> Glossary refresh

docs/modules/transform-sync/utilities.md, docs/reference/concepts/code-generation.md, docs/toc.md
- documenting changes from https://github.com/spatialos/gdk-for-unity/pull/1063/
- improbadoc serve
- yes this is docs
=> Type conversions docs

docs/reference/workflows/monobehaviour/interaction/commands/create-delete-spatialos-entities.md
=> Fix code snippet

docs/reference/workflows/monobehaviour/interaction/commands/create-delete-spatialos-entities.md
=> Fix code snippet (#1069)

CHANGELOG.md, workers/unity/Packages/io.improbable.gdk.gameobjectcreation/GameObjectCreatorFromMetadata.cs, workers/unity/Packages/io.improbable.gdk.transformsynchronization/AssemblyInfo.cs, workers/unity/Packages/io.improbable.gdk.transformsynchronization/AssemblyInfo.cs.meta, workers/unity/Packages/io.improbable.gdk.transformsynchronization/Systems/DefaultApplyLatestTransformSystem.cs, workers/unity/Packages/io.improbable.gdk.transformsynchronization/Systems/DefaultUpdateLatestTransformSystem.cs, workers/unity/Packages/io.improbable.gdk.transformsynchronization/Systems/ResetForAuthorityGainedSystem.cs, workers/unity/Packages/io.improbable.gdk.transformsynchronization/Systems/SetKinematicFromAuthoritySystem.cs, workers/unity/Packages/io.improbable.gdk.transformsynchronization/TransformImplementations.meta, workers/unity/Packages/io.improbable.gdk.transformsynchronization/TransformImplementations/ITransformSync.cs, workers/unity/Packages/io.improbable.gdk.transformsynchronization/TransformImplementations/ITransformSync.cs.meta, workers/unity/Packages/io.improbable.gdk.transformsynchronization/TransformImplementations/RigidbodyTransformSync.cs, workers/unity/Packages/io.improbable.gdk.transformsynchronization/TransformImplementations/RigidbodyTransformSync.cs.meta, workers/unity/Packages/io.improbable.gdk.transformsynchronization/TransformUtils.cs, workers/unity/Packages/io.improbable.gdk.transformsynchronization2d/Improbable.Gdk.TransformSynchronization2D.asmdef, workers/unity/Packages/io.improbable.gdk.transformsynchronization2d/Improbable.Gdk.TransformSynchronization2D.asmdef.meta, workers/unity/Packages/io.improbable.gdk.transformsynchronization2d/Rigidbody2DTransformSync.cs, workers/unity/Packages/io.improbable.gdk.transformsynchronization2d/Rigidbody2DTransformSync.cs.meta, workers/unity/Packages/io.improbable.gdk.transformsynchronization2d/TransformSynchronizationHelper2D.cs, workers/unity/Packages/io.improbable.gdk.transformsynchronization2d/TransformSynchronizationHelper2D.cs.meta, workers/unity/Packages/io.improbable.gdk.transformsynchronization2d/package.json, workers/unity/Packages/io.improbable.gdk.transformsynchronization2d/package.json.meta, workers/unity/Packages/manifest.json
Super straightforward support for Rigidbody2D for testing
Tested in local 2D test project
=> Add MVP implementation for Unity 2D support

docs/toc.md
=> Cherry-pick #1093

.buildkite/docs.steps.yaml
See title. Will cherry pick onto `docs-next` when merged
=> Add Scaler v2 to docs pipeline

CHANGELOG.md, workers/unity/Packages/io.improbable.gdk.core/Tests/Editmode/Connection/CommandLineConnectionParametersInitializerTests.cs, workers/unity/Packages/io.improbable.gdk.core/Tests/Editmode/Connection/CommandLineConnectionParametersInitializerTests.cs.meta, workers/unity/Packages/io.improbable.gdk.core/Worker/ConnectionHandlers/ConnectionParameterInitializers.cs
Small set of tests for the `CommandLineConnectionParameterInitializer` class.
=> Add tests for `CommandLineConnectionParameterInitializer`

CHANGELOG.md
Forgot that I changed it in `RuntimeConfigDefaults` too!
=> Add missed breaking change from #1105

CHANGELOG.md, workers/unity/Packages/io.improbable.gdk.core/Components/Option.cs, workers/unity/Packages/io.improbable.gdk.core/Tests/Editmode/Components/OptionTests.cs
As per sami's old PR
Make Options readonly, fix tests
Updated tests
=> Make Options readonly, fix tests

workers/unity/Packages/io.improbable.gdk.tools/LocalLaunch.cs
local launches through editor should work again on macos
tried local launch through editor on macos
n/a because bug caught before release
=> Fix local launch on mac

docs/projects/fps/tutorial.md, docs/reference/concepts/connection-flows.md, docs/reference/glossary.md, docs/reference/workflows/monobehaviour/worker-connectors.md, docs/variable.properties
Docs to accompany #1112 
- No more `Vector3f` = adjust tutorial contents. 
- No more `AlphaLocator` stuff.
=> Docs for `14.0.0` upgrade

docs/modules/mobile/prepare-project.md
=> cherrypick 8090a13 (#1124)

docs/variable.properties
=> Cherry-pick #1126

workers/unity/Packages/io.improbable.gdk.core/Tests/Editmode/Utility/PlayerConnectionPortTests.cs, workers/unity/Packages/io.improbable.gdk.core/Tests/Editmode/Utility/PlayerConnectionPortTests.cs.meta, workers/unity/Packages/io.improbable.gdk.core/Worker/WorkerConnector.cs
- Refactored `GetPlayerConnectionPort()` to pull out the bit that does the parsing and wrote some tests for that.
- Also adjusted the regex and some logic to fix bugs revealed during the tests.
Yes I am test.
N/A
=> Add player connection port parsing tests

docs/fragments/machine-setup.md
=> 2019.2.0 docs changes

CHANGELOG.md, init.ps1, init.sh, spatialos.json, test-project/Packages/io.improbable.gdk.dependencytest/package.json, test-project/Packages/io.improbable.gdk.dependencytestchild/package.json, test-project/Packages/io.improbable.gdk.dependencytestgrandchild/package.json, test-project/Packages/io.improbable.worker.sdk.testschema/package.json, workers/unity/Packages/io.improbable.gdk.core/package.json, workers/unity/Packages/io.improbable.gdk.mobile/package.json, workers/unity/Packages/io.improbable.worker.sdk.mobile/package.json, workers/unity/Packages/io.improbable.worker.sdk/package.json
- upgrade from "14.0.1" to 14.0.2
- drive-by update unity version in test project packages
it opens in unity
=> Worker SDK 14.0.2 Upgrade

test-project/Assets/EditmodeTests/ModularCodegenTests.cs, test-project/Assets/EditmodeTests/ModularCodegenTests.cs.meta, test-project/Assets/EditmodeTests/Subscriptions/InjectionCriteriaTests.cs, test-project/Assets/Generated/Source/improbable/tests/ModularTarget.cs, test-project/Packages/io.improbable.gdk.dependencytest/.codegen/Partials/Improbable.Tests.ModularTarget, test-project/Packages/io.improbable.gdk.dependencytest/.codegen/Source/Generators/ModularCodegenTestGeneratorPart.cs, test-project/Packages/io.improbable.gdk.dependencytest/.codegen/Source/TestCodegenJob.cs, test-project/Packages/io.improbable.gdk.dependencytest/.codegen/Templates/ModularCodegenTestGenerator.tt, test-project/Packages/io.improbable.gdk.dependencytest/.schema/improbable/tests/modular_codegen_target.schema
Add a basic set of test cases for each of the type of objects we support in modular codegen: raw source code, templates, and partials. Also a small driveby fix to another test.
Yes I am test.
=> UTY-2292: modular codegen tests

docs/variable.properties
=> Fix `current_version` variable

docs/variable.properties
=> Fix `current_version` variable  - cherry picked from 

docs/modules/debug/network-analyzer.md
Just calling out some caveats/gotchas.
=> Add disclaimer to network analyzer

docs/modules/debug/network-analyzer.md
Re-apply the changes to the `docs-next` branch 😄
=> Add disclaimer (docs-next)

docs/projects/blank/tutorial/2/gameobject-creation.md
copy across https://github.com/spatialos/gdk-for-unity/pull/1176
=> Cherrypick #1176

workers/unity/Packages/io.improbable.gdk.debug/NetStatsViewer/Templates/NetStatsWindow.uss
Quick fix of scaling for world selector and tab selectors
=> Netstats fix scaling

.buildkite/premerge.steps.yaml, .buildkite/release-qa.steps.yaml
Updating windows buildkite queue
Includes Unity fix
Might fix git checkout issue.
=> Update Windows Buildkite

test-project/Assets/EditmodeTests/Subscriptions/InjectionCriteriaTests.cs, workers/unity/Packages/io.improbable.gdk.core/Subscriptions/RequiredSubscriptionsInfo.cs
Remove an unneeded binding flag + adds a test to ensure this behaviour keeps working
=> Inherited required test

docs/reference/glossary.md, docs/variable.properties
Upping the version number for docs
=> Docs - worker sdk upgrade 14.2.1

CHANGELOG.md, workers/unity/Packages/io.improbable.gdk.buildsystem/Configuration/BuildConfigEditor.cs, workers/unity/Packages/io.improbable.gdk.buildsystem/Configuration/BuildContext.cs, workers/unity/Packages/io.improbable.gdk.buildsystem/Configuration/BuildContext.cs.meta, workers/unity/Packages/io.improbable.gdk.buildsystem/Configuration/BuildEnvironment.cs, workers/unity/Packages/io.improbable.gdk.buildsystem/Configuration/BuildTargetConfig.cs, workers/unity/Packages/io.improbable.gdk.buildsystem/Configuration/WorkerBuildData.cs, workers/unity/Packages/io.improbable.gdk.buildsystem/Util/BuildSupportChecker.cs, workers/unity/Packages/io.improbable.gdk.buildsystem/Util/CommandlineParser.cs, workers/unity/Packages/io.improbable.gdk.buildsystem/Util/CommandlineParser.cs.meta, workers/unity/Packages/io.improbable.gdk.buildsystem/Util/EditorPaths.cs, workers/unity/Packages/io.improbable.gdk.buildsystem/WorkerBuilder.cs, workers/unity/ProjectSettings/GraphicsSettings.asset
Refactor build system to put all configuration checking up front and build workers in batch
Add `CurrentContext` to get SpatialOS build information in Unity build callbacks.
=> UTY-2275 buildsystem refactor

docs/projects/fps/tutorial.md
remove reference to session flow
note: I've also deleted the github wiki page with instructions on how to test the session-flow
improbadoc
yes this is docs
=> Remove reference to session flow 

LICENSE.md, README.md
Update copyright in license/readme to 2020
- n/a
- n/a
=> Update copyright in license/readme to 2020

workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/CodeWriter/Scope.cs, workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/CodeWriter/Scopes/Annotations.cs
Expand annotations API
- used when porting across gameobject creation module
- n/a
=> Expand annotations API

docs/modules/build-system/cli.md, docs/workflows/ecs/concepts/system-update-order.md
Documented the new cli flags for ios
=> Document targetiOSSdk flag

workers/unity/Packages/io.improbable.worker.sdk.mobile/CopyLibcpp.cs
Fix NDK dir finding.
Tested locally with valid and invalid settings.
Build now fails if libc++ cannot be found.
=> Fix code finding the NDK root directory

docs/modules/build-system/cli.md
=> Fix typo in iOS target sdk section

docs/modules/build-system/cli.md
=> Cherry pick #1285 into docs-next

CHANGELOG.md, test-project/Packages/io.improbable.gdk.dependencytest/.codegen/Source/TestCodegenJob.cs, workers/unity/Packages/io.improbable.gdk.buildsystem/.codegen/Source/WorkerGenerationJob.cs, workers/unity/Packages/io.improbable.gdk.core/.codegen/Source/CoreCodegenJob.cs, workers/unity/Packages/io.improbable.gdk.core/.codegen/Source/Generators/Core/UnityComponentDataGenerator.cs, workers/unity/Packages/io.improbable.gdk.gameobjectcreation/.codegen/Source/GameObjectCodegenJob.cs, workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGen/EntryPoint.cs, workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/Jobs/CodegenJob.cs, workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/Jobs/JobRunner.cs, workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/Model/Details/DetailsStore.cs, workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/Tests/Jobs/CodegenJobTests.cs, workers/unity/Packages/io.improbable.gdk.tools/GenerateCode.cs
- remove old codegenjob system
- more logs from info to trace
- no change in generated code
=> [5/5] Cleanup codegen

.buildkite/hooks/post-checkout, .buildkite/hooks/pre-command, .buildkite/premerge.steps.yaml, workers/unity/Packages/io.improbable.gdk.mobile/Editor/iOSUtils.cs, workers/unity/Packages/io.improbable.gdk.testutils/Editor/SpatialdManager.cs
Running MacOS CI for real this time
=> MacOS buildkite for real

.buildkite/premerge.steps.yaml, ci/test.sh, workers/unity/Packages/io.improbable.gdk.core/Tests/Editmode/Components/OptionTests.cs
Magically the tests have started working consistently.
It seems the machine needed the reboot that happened by moving the machine from EV's desk to the server rack?
=> Enable SpatialD tests on MacOS

workers/unity/Packages/io.improbable.gdk.core/Collections/EntityRangeCollection.cs, workers/unity/Packages/io.improbable.gdk.core/Collections/EntityRangeCollection.cs.meta, workers/unity/Packages/io.improbable.gdk.core/Tests/Editmode/Collections.meta, workers/unity/Packages/io.improbable.gdk.core/Tests/Editmode/Collections/EntityRangeCollectionTests.cs, workers/unity/Packages/io.improbable.gdk.core/Tests/Editmode/Collections/EntityRangeCollectionTests.cs.meta
PRing this separately from the reservation system so that it can be reviewed while I work on it.
There are tests
=> Create EntityRangeCollection for upcoming EntityReservationSystem

docs/modules/player-lifecycle/basic-player-creation.md, docs/modules/player-lifecycle/custom-player-creation.md
Include EntityId in method signature for player template
=> Include EntityId in method signature for player template

workers/unity/Packages/io.improbable.gdk.tools/Common.cs
=> Update in-code link to docs

.buildkite/generate-docs.steps.yaml, ci/generate-docs.sh
A follow on from #1310, this uses both a pinned docker image reference and triggers the platform pipeline to actually publish the documentation
Changed a source link in one ReadMe doc. Ran the pipeline & checked that it was reverted back. 
Will update the Wiki for the release process.
=> Generated docs pipeline part two

UPGRADE_GUIDE.md
upgrade guide fix
- after this is merged, I'll repoint upgrade guide links to this page instead of master
=> upgrade guide fix

CHANGELOG.md, UPGRADE_GUIDE.md, workers/unity/Assets/Playground/Scripts/Camera/FollowCameraSystem.cs, workers/unity/Assets/Playground/Scripts/Camera/InitCameraSystem.cs, workers/unity/Assets/Playground/Scripts/Cubes/CollisionProcessSystem.cs, workers/unity/Assets/Playground/Scripts/Cubes/CubeMovementSystem.cs, workers/unity/Assets/Playground/Scripts/Cubes/ProcessColorChangeSystem.cs, workers/unity/Assets/Playground/Scripts/Cubes/TriggerColorChangeSystem.cs, workers/unity/Assets/Playground/Scripts/DisconnectSystem.cs, workers/unity/Assets/Playground/Scripts/Metrics/MetricSendSystem.cs, workers/unity/Assets/Playground/Scripts/Player/LocalPlayerInputSync.cs, workers/unity/Assets/Playground/Scripts/Player/MoveLocalPlayerSystem.cs, workers/unity/Assets/Playground/Scripts/Player/PlayerCommandsSystem.cs, workers/unity/Assets/Playground/Scripts/Player/ProcessLaunchCommandSystem.cs, workers/unity/Assets/Playground/Scripts/Player/ProcessRechargeSystem.cs, workers/unity/Assets/Playground/Scripts/Player/ProcessScoresSystem.cs, workers/unity/Assets/Playground/Scripts/UI/InitUISystem.cs, workers/unity/Assets/Playground/Scripts/UI/UpdateUISystem.cs, workers/unity/Packages/io.improbable.gdk.core/Systems/ComponentSendSystem.cs, workers/unity/Packages/io.improbable.gdk.core/Utility/PlayerLoopUtils.cs, workers/unity/Packages/io.improbable.gdk.core/Worker/WorkerConnector.cs, workers/unity/Packages/io.improbable.gdk.core/package.json, workers/unity/Packages/io.improbable.gdk.debug/NetStatsViewer/NetStatViewer.cs
Upgrade to entities 0.7.0
Replace deprecated API
=> Upgrade entities to 0.7.0

OWNERS
=> Update owners file to reflect current team structure

CHANGELOG.md, workers/unity/Packages/io.improbable.gdk.playerlifecycle/Systems/PlayerHeartbeat/PlayerHeartbeatInitializationSystem.cs
Make sure the PlayerHeartbeatInitializationSystem uses the right component so that it keeps working with QBI filtering.
Use new API for adding component.
=> Fix PlayerHeartbeatInitializationSystem

CHANGELOG.md, workers/unity/Packages/io.improbable.gdk.tools/GdkToolsConfiguration.cs, workers/unity/Packages/io.improbable.gdk.tools/GdkToolsConfigurationWindow.cs
Made the GDK Tools dialog auto-save. Also moved the reset button to the bottom instead of the top to make it a bit cleaner.
=> GDK Tools dialog auto-saves

CHANGELOG.md, test-project/Assets/Generated/Source/improbable/dependentschema/DependentComponent.cs, test-project/Assets/Generated/Source/improbable/dependentschema/DependentDataComponent.cs, test-project/Assets/Generated/Source/improbable/dependentschema/DependentDataComponentCommandDiffDeserializer.cs, test-project/Assets/Generated/Source/improbable/dependentschema/DependentDataComponentCommandMetaDataStorage.cs, test-project/Assets/Generated/Source/improbable/dependentschema/DependentDataComponentCommandPayloads.cs, test-project/Assets/Generated/Source/improbable/tests/DependencyTest.cs, test-project/Assets/Generated/Source/improbable/tests/DependencyTestChild.cs, test-project/Assets/Generated/Source/improbable/tests/DependencyTestGrandchild.cs, test-project/Assets/Generated/Source/improbable/testschema/ComponentUsingNestedTypeSameName.cs, test-project/Assets/Generated/Source/improbable/testschema/ExhaustiveEntity.cs, test-project/Assets/Generated/Source/improbable/testschema/ExhaustiveMapKey.cs, test-project/Assets/Generated/Source/improbable/testschema/ExhaustiveMapValue.cs, test-project/Assets/Generated/Source/improbable/testschema/ExhaustiveOptional.cs, test-project/Assets/Generated/Source/improbable/testschema/ExhaustiveRepeated.cs, test-project/Assets/Generated/Source/improbable/testschema/ExhaustiveSingular.cs, test-project/Assets/Generated/Source/improbable/testschema/RecursiveComponent.cs, workers/unity/Packages/io.improbable.gdk.core/.codegen/Source/Generators/Core/UnityComponentDataGenerator.cs
Don't bit shift by 4, bit shift by 5
=> fix Dirtybits  bit shift

ci/bootstrap.sh, ci/build-deployment-launcher.sh, ci/get-shared-ci.sh, ci/launch.sh, ci/lint.sh, ci/publish_packages.sh, ci/shared-ci.pinned, ci/sonar-scanner.sh, ci/test.sh
As per the guide in https://improbableio.atlassian.net/browse/UTY-2600
=> New Buildkite instrumentation format

.buildkite/generate-docs.steps.yaml, .buildkite/premerge.steps.yaml, workers/unity/Assets/Resources.meta
Update queue to v4-20-07-06-120608-bk13080-eb89af6c. [Bake Link] (https://buildkite.com/improbable/platform-bakery/builds/13080)
- Premerge
- Generate Docs (I cancelled this after the trigger)
=> UTY-2607: update linux queue

CHANGELOG.md, spatialos.json
=> UTY-2626: Update spatialos json

.buildkite/premerge.steps.yaml, .buildkite/release-qa.steps.yaml
=> UTY-2657: set max ci agents

CHANGELOG.md, workers/unity/Packages/io.improbable.gdk.buildsystem/Configuration/BuildContext.cs, workers/unity/Packages/io.improbable.worker.sdk/CEventTrace.cs, workers/unity/Packages/io.improbable.worker.sdk/CEventTrace.cs.meta, workers/unity/Packages/io.improbable.worker.sdk/CIO.cs, workers/unity/Packages/io.improbable.worker.sdk/CIO.cs.meta, workers/unity/Packages/io.improbable.worker.sdk/Constants.cs, workers/unity/Packages/io.improbable.worker.sdk/Constants.cs.meta, workers/unity/Packages/io.improbable.worker.sdk/Improbable.Worker.Sdk.asmdef, workers/unity/Packages/io.improbable.worker.sdk/Improbable.Worker.Sdk.asmdef.meta
For [UTY-2671](https://improbableio.atlassian.net/browse/UTY-2671)
Initial work for the implementation of the Event Tracing API, introduces some internal C# bindings for the C API
WIP
WIP
=> Event Tracing API C# Bindings

CHANGELOG.md, UPGRADE_GUIDE.md, workers/unity/Assets/Tests/PlaymodeTests/Correctness/TransformSynchronization/TransformInitialisationTest.cs, workers/unity/Packages/io.improbable.gdk.core/.codegen/Source/Generators/Core/UnityEcsViewManagerGenerator.cs, workers/unity/Packages/io.improbable.gdk.core/Utility/PlayerLoopUtils.cs, workers/unity/Packages/io.improbable.gdk.core/Worker/WorkerConnector.cs, workers/unity/Packages/io.improbable.gdk.core/package.json, workers/unity/Packages/io.improbable.gdk.debug/WorkerInspector/EntityListData.cs, workers/unity/Packages/io.improbable.gdk.playerlifecycle/Systems/PlayerHeartbeat/HandlePlayerHeartbeatResponseSystem.cs, workers/unity/Packages/io.improbable.gdk.transformsynchronization/MonoBehaviours/TransformSynchronization.cs, workers/unity/Packages/manifest.json, workers/unity/ProjectSettings/ProjectSettings.asset
Upgraded the entities package to latest (0.14.0-preview.18)
=> Upgrade to entities 0.14.0-preview.18

workers/unity/Packages/io.improbable.gdk.core/SceneAuthoring.meta, workers/unity/Packages/io.improbable.gdk.core/SceneAuthoring/IConvertGameObjectToSpatialOsEntity.cs, workers/unity/Packages/io.improbable.gdk.core/SceneAuthoring/IConvertGameObjectToSpatialOsEntity.cs.meta, workers/unity/Packages/io.improbable.gdk.core/SceneAuthoring/ISpatialOsAuthoringComponent.cs, workers/unity/Packages/io.improbable.gdk.core/SceneAuthoring/ISpatialOsAuthoringComponent.cs.meta
This PR contains the two interfaces that make up the core of the scene authoring feature. Future PRs will build on top of these interfaces. 
N/A
=> Add interfaces for scene authoring

.buildkite/generate-docs.definition.yaml, .buildkite/premerge.definition.yaml, .buildkite/release-qa.definition.yaml
Switch to using teams which are automatically managed by groupsync.
If there are any mistakes or other manual teams that we missed, please feel free to add commits to this branch to resolve.
Immediately post-merge, roll out permission changes via `circle`:
OR
* Change generated via sourcegraph campaign https://code.i8e.io/users/ca-johnson/campaigns/Q2FtcGFpZ246MQ==
* Pre-merge pipelines may fail with "Authorisation Denied". Please click "Rebuild" in Buildkite to authorise the build to run.
* You may need to push pipelines individually with `circle ci pipeline push` where they do not appear in the output of `circle ci pipeline check`
* Contact @support-eng-velocity in #eng-velocity-support slack channel if you have questions or issues
=> Use Buildkite Auto-Managed Groupsync Teams

.buildkite/premerge.steps.yaml, .buildkite/release-qa.steps.yaml
=> Reanimate CI

workers/unity/Packages/io.improbable.gdk.core/.codegen/Source/Generators/Core/ComponentDiffStorageGenerator.cs, workers/unity/Packages/io.improbable.gdk.core/.codegen/Source/Generators/Core/UnityComponentDataGenerator.cs, workers/unity/Packages/io.improbable.gdk.core/.codegen/Source/Generators/Core/UnityComponentReplicationSystemGenerator.cs, workers/unity/Packages/io.improbable.gdk.core/.codegen/Source/Generators/Core/UnityEcsViewManagerGenerator.cs, workers/unity/Packages/io.improbable.gdk.core/Collections/MessageList.cs, workers/unity/Packages/io.improbable.gdk.core/Collections/ReceivedMessageListExtensions.cs, workers/unity/Packages/io.improbable.gdk.core/Commands/CommandDiffStorageBase.cs, workers/unity/Packages/io.improbable.gdk.core/Components/ISpatialComponentSnapshot.cs, workers/unity/Packages/io.improbable.gdk.core/Systems/CleanTemporaryComponentsSystem.cs, workers/unity/Packages/io.improbable.gdk.core/Systems/SpatialOSSendSystem.cs, workers/unity/Packages/io.improbable.gdk.core/Systems/UpdateGroups.cs, workers/unity/Packages/io.improbable.gdk.core/Systems/WorkerSystem.cs, workers/unity/Packages/io.improbable.gdk.core/View/DiffComponentStorage.cs, workers/unity/Packages/io.improbable.gdk.core/Worker/DynamicComponentRequests.cs, workers/unity/Packages/io.improbable.gdk.core/Worker/DynamicComponentRequests.cs.meta, workers/unity/Packages/io.improbable.gdk.core/Worker/MessagesToSend.cs, workers/unity/Packages/io.improbable.gdk.core/Worker/SerializedMessagesToSend.cs, workers/unity/Packages/io.improbable.gdk.core/Worker/WorldCommandsReceivedStorage.cs
* Move component replication systems to end of simulation step to optimize for multi-worker environments
* Optimize MessageList to significantly reduce sorting costs when receiving Ops
* Add support for Dynamic Components
=> Multi-Worker Optimizations

CHANGELOG.md, workers/unity/Packages/io.improbable.gdk.core/.codegen/Source/Generators/Core/CommandDiffDeserializerGenerator.cs, workers/unity/Packages/io.improbable.gdk.core/Worker/SerializedMessagesToSend.cs
Fix command `ShortCircuit` property being ignored
Fix command request id being wrong size
=> Command short circuit + request id fix

CHANGELOG.md, workers/unity/Packages/io.improbable.gdk.core/Logging/LogDispatcherExtensions.cs, workers/unity/Packages/io.improbable.gdk.core/Logging/LogDispatcherExtensions.cs.meta
A few simple logging extensions for the more common cases. 
Split from #1491
=> Add logging extensions

workers/unity/Packages/io.improbable.gdk.core/.codegen/Source/CoreCodegenJob.cs, workers/unity/Packages/io.improbable.gdk.core/.codegen/Source/Generators/Core/ComponentDiffDeserializerGenerator.cs, workers/unity/Packages/io.improbable.gdk.core/.codegen/Source/Generators/Core/MetaclassGenerator.cs, workers/unity/Packages/io.improbable.gdk.core/.codegen/Source/Generators/Core/UnityComponentReplicationSystemGenerator.cs, workers/unity/Packages/io.improbable.gdk.core/.codegen/Source/Generators/Core/UnityEcsViewManagerGenerator.cs, workers/unity/Packages/io.improbable.gdk.core/Components/IComponentMetaclass.cs, workers/unity/Packages/io.improbable.gdk.core/Logging/ForwardingDispatcher.cs, workers/unity/Packages/io.improbable.gdk.core/UpdatesAndEvents/ComponentManagers.cs, workers/unity/Packages/io.improbable.gdk.core/Worker/MessageSerialization.cs, workers/unity/Packages/io.improbable.gdk.core/Worker/SerializedMessagesToSend.cs, workers/unity/Packages/io.improbable.gdk.core/Worker/WorkerInWorld.cs
Only attempt to replicate components that have fields, and you have authority over.
Small fix on ForwardingDispatcher when using multiple threads.
=> Replication changes v15

CHANGELOG.md, workers/unity/Assets/Playground/Config/EntityTemplates.cs, workers/unity/Assets/Tests/EditmodeTests/Correctness/Utility/ConstraintTests.cs, workers/unity/Packages/io.improbable.gdk.querybasedinteresthelper/Constraint.cs
Adds support for Self constraint to QBI helper module.
=> Add support for Self constraint to QBI helper module

CHANGELOG.md, workers/unity/Packages/io.improbable.gdk.core/Worker/OpListConverter.cs, workers/unity/Packages/io.improbable.gdk.core/Worker/ViewDiff.cs, workers/unity/Packages/manifest.json
Remove ability to receive internal metrics from Worker SDK
Upgrade IDE Packages to support
=> Remove ability to receive internal metrics from Worker SDK

workers/unity/Packages/io.improbable.gdk.loadbalancing/Improbable.Gdk.LoadBalancing.asmdef, workers/unity/Packages/io.improbable.gdk.loadbalancing/Systems/PointsOfInterestStrategySystem.cs
Actually check if the value is changing before changing it!
=> Fix unnecessary `AuthorityDelegation` component updates

CHANGELOG.md, workers/unity/Assets/Playground/Scripts/MonoBehaviours/WorkerFlagTest.cs, workers/unity/Assets/Playground/Scripts/Worker/ClientWorkerConnector.cs, workers/unity/Assets/Playground/Scripts/Worker/GameLogicWorkerConnector.cs, workers/unity/Assets/Playground/Scripts/Worker/LoadBalancerWorkerConnector.cs, workers/unity/Assets/Playground/Scripts/Worker/MobileClientWorkerConnector.cs, workers/unity/Packages/io.improbable.gdk.buildsystem/.codegen/Source/Generators/BuildSystem/UnityWorkerMenuGenerator.cs, workers/unity/Packages/io.improbable.gdk.buildsystem/.codegen/Source/WorkerGenerationJob.cs, workers/unity/Packages/io.improbable.gdk.core/.codegen/Source/CoreCodegenJob.cs, workers/unity/Packages/io.improbable.gdk.core/.codegen/Source/Generators/Core/WorkerTypesGenerator.cs, workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGen/EntryPoint.cs, workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/Model/Details/DetailsStore.cs, workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/Tests/Jobs/CodegenJobTests.cs, workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/Tests/Model/DetailsStoreTests.cs, workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/Tests/Model/NameClashingTests.cs
=> Generate WorkerTypes.cs
