- workers/unity/Assets/Gdk/Physics/Systems/PositionSendSystem.cs
- workers/unity/Assets/Gdk/Physics/Systems/TransformSendSystem.cs
Fixed TransformSendSystem to use a real timer to limit sends, rather than the parity of GlobalTick.
Made Change, tested locally with various different send rates, verified expected behaviour (cube movement becomes less smooth at lower send rates)
N/A
> Bugfix: UTY-457 TransformSendSystem should not miss sends.

- docs/setup-and-installing.md
Remove `spatial worker build --target=deployment` from /docs, as `--target=deployment` does not function.
I ran `spatial worker build --target=deployment` to confirm that it errors.
I ran `spatial build` to confirm that it succeeds.
I deployed locally and in the [cloud](https://console.improbable.io/projects/demo/deployments/asofbaroihgbo/overview).
@samiwh
> Remove `spatial worker build --target=deployment` from /docs.

- workers/unity/Assets/Gdk/Core/Components/WorldCommandsTranslation.cs
- workers/unity/Assets/Gdk/Core/MutableView/MutableView.cs
- workers/unity/Assets/Gdk/Core/Worker/WorkerBase.cs
-------
This PR makes some changes to the `MutableView` API to clean it up by removing unnecessary methods/fields, making things internal where appropriate, and reorganising the methods such that they go in `public` -> `internal` -> `private` order.
List of changes:
* Remove all shared component methods on the `MutableView` as they were not used and a relic of the past.
* Remove the connection on the view and the setting of it in the Worker. Systems now access the connection via the …
> UTY-189: Mutable View API Review

- workers/unity/Assets/Playground/Scripts/Player/ProcessLaunchCommandSystem.cs
- workers/unity/Assets/Playground/Scripts/Spawning/GameObjectInitializationSystem.cs
- workers/unity/Assets/Playground/Scripts/Spawning/SpatialOSComponent.cs
-------
Very small change to also add a World to the SpatialOSComponent which links 
N/A
N/A
@samiwh @JonasImprobable
> UTY-370: Link world to a monobehaviour.

- code_generator/Templates/UnityComponentDataGenerator.tt
- code_generator/Templates/UnityComponentGenerator.tt
- docs/content/component-data.md
- workers/unity/Assets/Gdk/Core/Components/ISpatialComponentData.cs
- workers/unity/Assets/Gdk/Core/Systems/CustomSpatialOSSendSystem.cs
-------
We have overlooked the fact that all blittable components inherit from `ISpatialComponentData` and non-blittable components have no indication that they are Spatial. 
This PR corrects that by decoupling `ISpatialComponentData` from `IComponentData` and tweaking the `tt` files to extend two interface(s)/base class. 
This allows us to test components for "Spatial-ity" by checking that it implements `ISpatialComponentData`.
Also done a driveby to fix `CustomSendSystem`
Tested …
> UTY-407: Decouple ISpatialComponentData from IComponentData

- workers/unity/Assets/Playground/Scripts/Cubes/CubeMovementSystem.cs
-------
The CubeMovementSystem relied on the origin being at 0. When the origin was changed this broke and the cubes kept running off the platform.
Ran the game, all works.
N/A
@jessicafalk
> Fix cube movement

- workers/unity/Assets/Gdk/Core/Components/ComponentTranslation.cs
- workers/unity/Assets/Gdk/Core/Components/WorldCommandsTranslation.cs
Fixed a bug where incorrect errors were reported when a response arrived for a world command and the entity that sent the command is gone. Incorrect command names were being reported, and requests IDs were passed in place of entity IDs, this is now corrected.
Also differentiated between a request ID not existing in the dictionary, and the entity for a request not existing on the worker anymore. The latter is expected to happen occasionally under normal circumstances, so lowered the error to a warning.
Minor bugfix
Minor bugfix
@samiwh @jamiebrynes7
> Fixed incorrect error messages reported for world commands

- ci/lint.sh
ci/lint.sh doesn't like spaces in UNITY_HOME
> UTY-581: Bugfix Support UNITY_HOME with spaces in ci/lint.sh

- code_generator/End2End/GeneratedDependencies/Generated/improbable/testschema/ExhaustiveBlittableSingularTranslation.cs
- code_generator/End2End/GeneratedDependencies/Generated/improbable/testschema/ExhaustiveMapKeyTranslation.cs
- code_generator/End2End/GeneratedDependencies/Generated/improbable/testschema/ExhaustiveMapValueTranslation.cs
- code_generator/End2End/GeneratedDependencies/Generated/improbable/testschema/ExhaustiveOptionalTranslation.cs
- code_generator/End2End/GeneratedDependencies/Generated/improbable/testschema/ExhaustiveRepeatedTranslation.cs
- code_generator/End2End/GeneratedDependencies/Generated/improbable/testschema/ExhaustiveSingularTranslation.cs
- code_generator/End2End/GeneratedDependencies/Generated/improbable/testschema/NestedComponentTranslation.cs
- code_generator/End2End/GeneratedDependencies/Generated/improbable/testschema/blittable/BlittableComponentTranslation.cs
- code_generator/End2End/GeneratedDependencies/Generated/improbable/testschema/nonblittable/NonBlittableComponentTranslation.cs
- code_generator/GdkCodeGenerator/Templates/UnityComponentConversionGenerator.tt
- docs/content/reactive-components.md
- workers/unity/Assets/Gdk/Core/Components/ComponentTranslation.cs
- workers/unity/Assets/Gdk/Core/Components/ReactiveComponents.cs
Created 2 new tag components, (ComponentAdded<T>, ComponentRemoved<T>) that are added to ECS entities for one frame when the SpatialOSComponent T is added / removed.
Tested locally by injecting the ComponentAdded tag into a system and verifying they are present during initial checkout for a single frame.
Used Connection.SendComponentInterest on UnityClient to unregister interest of a SpatialOSComponent and verified the 
Updated reactive-components.md
> UTY-540: ComponentAdded / ComponentRemoved reactive tags

- docs/README.md
- docs/content/reactive-components.md
- docs/content/temporary-components.md
- workers/unity/Assets/Gdk/Core/Attributes.meta
- workers/unity/Assets/Gdk/Core/Attributes/RemoveAtEndOfTick.cs
- workers/unity/Assets/Gdk/Core/Attributes/RemoveAtEndOfTick.cs.meta
- workers/unity/Assets/Gdk/Core/Components/NewlyAddedSpatialOSEntity.cs
- workers/unity/Assets/Gdk/Core/Components/WorkerEntityComponents.cs
- workers/unity/Assets/Gdk/Core/Systems/CleanReactiveComponentsSystem.cs
Currently we hard code in temporary components in the clean system. This makes this generic and opens up the possibility of having auto cleaned components in other features.
There is a clean reactive component test already, which this passes
temporary-component.md
@zeroZshadow @jamiebrynes7 @JonasImprobable
> Added an attribute to remove non-codegen components

- android_launch.json
- tools/DocsLinter/Tests/LinkCheckingTests.cs
- workers/unity/Assets/Gdk/Android.meta
- workers/unity/Assets/Gdk/Android/Editor.meta
- workers/unity/Assets/Gdk/Android/Editor/AndroidSpatialRunner.cs
- workers/unity/Assets/Gdk/Android/Editor/AndroidSpatialRunner.cs.meta
- workers/unity/Assets/Gdk/Android/Editor/Improbable.Gdk.Android.Editor.asmdef
- workers/unity/Assets/Gdk/Android/Editor/Improbable.Gdk.Android.Editor.asmdef.meta
- workers/unity/Assets/Gdk/Android/Improbable.Gdk.Android.asmdef
- workers/unity/Assets/Gdk/Android/Improbable.Gdk.Android.asmdef.meta
- workers/unity/Assets/Gdk/Android/Utility.meta
- workers/unity/Assets/Gdk/Android/Utility/DeviceInfo.cs
- workers/unity/Assets/Gdk/Android/Utility/DeviceInfo.cs.meta
- workers/unity/Assets/Gdk/Core/Components/WorldCommandsTranslation.cs
- workers/unity/Assets/Gdk/Core/Config/ReceptionistConfig.cs
- workers/unity/Assets/Playground/Improbable.Playground.asmdef
- workers/unity/Assets/Playground/Scripts/Bootstrap.cs
- workers/unity/ProjectSettings/ProjectSettings.asset
- Added logic that detects whether the device that the game is currently running on is an Android emulator (widely accepted way of checking, should work for all popular emulators).
- Added an Improbable menu item to run spatial locally with all required parameters to improve workflow.
- Code gets executed on Android emulator device only.
-
> UTY-555: Add emulator support for Android

- workers/unity/Assets/Gdk/TestUtils/HybridGdkSystemTestBase.cs
- workers/unity/Assets/Gdk/TestUtils/Tests/Editmode/HybridGdkSystemTestBaseTests.cs
-------
If the `DefaultWorldInitializationTestsInitialize_ShouldLogNothing` test runs before `HybridGdkSystemTestBaseTests.HybridSystems_will_result_in_errors_when_created_if_fixture_does_not_extend_HybridGdkSystemTestBase` then the injection hooks would not be cleaned up.
This means the `HybridGdkSystemTestBase` would find itself unneeded and be sad. But it's still needed.
So we clean up the hooks now.
Also, when the test fails, it would leak parts of the system. Moved the system dispose call into a finally block to ensure it will not leak in failure cases.
The tests were …
> UTY-639 Fix test failures

- docs/setup-and-installing.md
Added the Mac prerequisites to `setup-and-installing.md`.
Since only the prerequisites are different between operating systems, I've kept it as one doc and just added the Mac prerequisites into both the short version and the longer version.
n/a
n/a - already docs :)
@jessicafalk @ElleEss
> Add Mac steps to setup guide

- ci/codegen.sh
- code_generator/GdkCodeGenerator/src/CodeGenerator.cs
Fixes a few small issues with schema-compiler-path:
1. Removes isLinux check since linux is not currently supported.
2. Checks for schema-compiler-path flag as it is required.
Ran codegen tests, and ran ci/codegen.sh
> UTY 714: schema-compiler-path fixes

- docs/setup-and-installing.md
I have made this change because, not that 2018.2.0 is out of page we previously linked to, [/unity/beta-download](https://unity3d.com/unity/beta-download) no longer contains any download links.
I'm manually testing 2018.2.0 now.
> Update Unity Version in setup-and-installing.md

- ci/test.sh
- workers/unity/spatialos.UnityGameLogic.worker.json
-------
The Unity.entities tests will crash when run from CI with `-nographics` enabled. Removing all instances of this flag as it's not the first time that `-nographics` has caused problems.
ran it multiple times on a Mac using different projects.
no doc needed
> [Mac] Fixing crash of Unity when running tests in CI

- code_generator/GdkCodeGenerator/Templates/UnityCommandPayloadGenerator.tt
- code_generator/GdkCodeGenerator/Templates/UnityComponentConversionGenerator.tt
- workers/unity/Packages/com.improbable.gdk.core/Components/WorldCommandsTranslation.cs
-------
When a worker receives a command request it has 3 options - send a response, ignore it, or deliberately fail it. Currently we do not have an api for deliberately failing commands. Most likely this should be added as an api on the command request component along side the response method.
Example generated code:
```csharp
public partial class Launcher
{
public class Translation : ComponentTranslation, IDispatcherCallbacks<global::Playground.Launcher>
{
internal List<LaunchEntity.OutgoingRequest> LaunchEntityRequests = new List<LaunchEntity.OutgoingRequest>();
internal …
```
> UTY-277: Add the ability to fail a command.

- workers/unity/Packages/com.improbable.gdk.core/Components/ISpatialComponentUpdate.cs
- workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Delegates.cs
- workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Delegates.cs.meta
- workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/IReader.cs
- workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/IReader.cs.meta
- workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/IReaderInternal.cs
- workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/IReaderInternal.cs.meta
-------
Introducing the public and internal versions of the Reader interfaces.
Also preparing tagging for component updates to highlight that they are for a particular component. This will aid with type hinting for the rest of MonoBehaviour implementation.
To follow in following PRs:
- events
- commands
Tests to come in a following PR about UTY-709
Inline documentation for interfaces
> UTY-709 Add interfaces to be used by MonoBehaviours

- workers/unity/Packages/com.improbable.gdk.core/Collections.meta
- workers/unity/Packages/com.improbable.gdk.core/Collections/BlittableList.cs
- workers/unity/Packages/com.improbable.gdk.core/Collections/BlittableList.cs.meta
- workers/unity/Packages/com.improbable.gdk.core/Collections/BlittableMap.cs
- workers/unity/Packages/com.improbable.gdk.core/Collections/BlittableMap.cs.meta
- workers/unity/Packages/com.improbable.gdk.core/Collections/BlittableString.cs
- workers/unity/Packages/com.improbable.gdk.core/Collections/BlittableString.cs.meta
- workers/unity/Packages/com.improbable.gdk.core/Collections/CollectionProvider.cs
- workers/unity/Packages/com.improbable.gdk.core/Collections/CollectionProvider.cs.meta
- workers/unity/Packages/com.improbable.gdk.core/Collections/HandleProvider.cs
- workers/unity/Packages/com.improbable.gdk.core/Collections/HandleProvider.cs.meta
- workers/unity/Packages/com.improbable.gdk.core/Collections/StringProvider.cs
- workers/unity/Packages/com.improbable.gdk.core/Collections/StringProvider.cs.meta
Add Wrappers for List, Dictionary, and string to use in codegen for schema list,map, and strings.
This is a quick version to allow @jamiebrynes7 to make all components blittable.
This still needs to be discussed and improved upon later.
IList and IDictionary was implemented just for ease of use now.
Will need to be re-considered.
@jamiebrynes7
> [Experimental][CSharp Core SDK] Blittable list and map

- workers/unity/Packages/com.improbable.gdk.core/MutableView/MutableView.cs
- workers/unity/Packages/com.improbable.gdk.core/Utility/EntityManagerExtensions.cs
- workers/unity/Packages/com.improbable.gdk.core/Utility/EntityManagerExtensions.cs.meta
-------
This makes it consistent with `GetComponentObject` extension method too.
Also adds some exceptions to help resolve problems if things change
Tested with local deployments and in editor
Internal only
@zeroZshadow @jamiebrynes7
> Extract SetComponentObject into an extension method

- workers/unity/Assets/Playground/Scripts/Bootstrap.cs
- workers/unity/Packages/com.improbable.gdk.core/Config/RuntimeConfig.cs
- workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/Worker/WorkerBaseTests.cs
- workers/unity/Packages/com.improbable.gdk.core/Worker/WorkerBase.cs
- workers/unity/spatialos.UnityGameLogic.worker.json
-------
Attempt to resolve issues raised by @zeroZshadow within #123 by removing the flag passed into the launch parameters, and force unique ids if no worker id is specified
Adjusted WorkerBaseTests to handle the parameter changes
Internal changes
@zeroZshadow @jessicafalk
> UTY-622 Enable alternative with no flag

- workers/unity/Assets/Playground/Scripts/Bootstrap.cs
- workers/unity/Assets/Playground/Scripts/Workers/UnityClient.cs
- workers/unity/Assets/Playground/Scripts/Workers/UnityGameLogic.cs
- workers/unity/Packages/com.improbable.gdk.core/Config/RuntimeConfig.cs
- workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/Worker/WorkerBaseTests.cs
- workers/unity/Packages/com.improbable.gdk.core/Worker/WorkerBase.cs
- workers/unity/Packages/com.improbable.gdk.core/Worker/WorkerRegistry.cs
- workers/unity/spatialos.UnityClient.worker.json
- workers/unity/spatialos.UnityGameLogic.worker.json
-------
Comes with some driveby fixes and features:
- Can launch UnityGameLogic
- Fixed ArgumentException for bad worker type in config params
- Added unique connection ID param to be passed into UnityGameLogic worker during startup (because we cannot have the cloud deployment be affected)
- Moved launch log files to logs folder
Tested locally using:
```
spatial local worker launch UnityGameLogic default
spatial local worker launch UnityClient default
```
Needs to be added when documentation for launch arguments are considered (will create a ticket if it doesn't exist) …
> UTY-622 Allow `spatial local worker launch` and reconnections

- code_generator/GdkCodeGenerator/Templates/UnityComponentDataGenerator.tt
- code_generator/GdkCodeGenerator/Templates/UnityComponentGenerator.tt
- workers/unity/Packages/com.improbable.gdk.core/AssemblyInfo.cs
-------
UTY-792
This unblocks reader/writer registration for components and acts as a base for their constructor signatures.
> UTY-792 Implement stubs for the reader classes

- docs/content/logging.md
- workers/unity/Packages/com.improbable.gdk.core/Logging/ForwardingDispatcher.cs
- workers/unity/Packages/com.improbable.gdk.core/Logging/LogEvent.cs
- workers/unity/Packages/com.improbable.gdk.core/Logging/LoggingDispatcher.cs
- workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/Logging.meta
- workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/Logging/LoggingTests.cs
- workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/Logging/LoggingTests.cs.meta
-------
While writing exceptions for UTY-709 I discovered that they were not showing in the Unity console.
This PR
- allows exception messages to be passed into Unity's logger properly
- and adds logging tests
- also removes redundant newlines from logs
New tests added to test all log types
Added docs for new methods
@martinzlocha @JonasImprobable
> Allow exception messages to be passed into Unity's logger properly

- ci/includes/pinned-tools.sh
Paths are borked on the mac TC agents. We know exactly where dotnet is though.
Ran the CI build step. Dotnet actually ran but the build failed for other reasons (similar to Mac crashes I imagine)
N/A
> UTY-473: Fix Dotnet Path for Mac TC Agents

- workers/unity/Assets/Playground/Scripts/Cubes/ProcessColorChangeSystem.cs
-------
Cube colour change is now done with predetermined MaterialPropertyBlocks, allowing them to be drawn in batches and improving rendering performance.
> UTY-831: Draw playground cubes in batches

- docs/setup-and-installing.md
Remove unnecessary "for SpatialOS local deployment only" callout.
None
> Remove unnecessary "for SpatialOS local deployment only" callout.

- code_generator/GdkCodeGenerator/Templates/UnityComponentConversionGenerator.tt
- workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveBlittableSingularTranslation.cs
- workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapKeyTranslation.cs
- workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapValueTranslation.cs
- workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveOptionalTranslation.cs
- workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveRepeatedTranslation.cs
- workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveSingularTranslation.cs
- workers/unity/Assets/Generated/Source/improbable/gdk/tests/NestedComponentTranslation.cs
- workers/unity/Assets/Playground/Scripts/Player/PlayerCommandsSystem.cs
- workers/unity/Packages/com.improbable.gdk.core/Components/ComponentTranslation.cs
- workers/unity/Packages/com.improbable.gdk.core/Components/WorldCommandsTranslation.cs
- workers/unity/Packages/com.improbable.gdk.core/MutableView/MutableView.cs
- workers/unity/Packages/com.improbable.gdk.core/Utility/ViewCommandBuffer.cs
-------
The first of many PRs to get rid of the mutable view. This one simply removes all the wrapper methods that we have and don't provide any additional functionality. Any method that contains a bit more logic is still in there until I decide on how to exactly factor this out. Right now, we use the EntityManager from the view, this will also change in one of the next PRs
Tested that local deployment still works.
no docs 
@jamiebrynes7
> Removing functionality from the Mutable View

- docs/content/commands.md
- docs/content/custom-replication-system.md
- docs/content/entity-checkout-process.md
- docs/content/events.md
-------
There were references to DemoGame in the docs. It should refer to Playground instead.
N/A
N/A
@jessicafalk @oblm
> Remove references to DemoGame in docs.

- code_generator/GdkCodeGenerator/Templates/UnityGameObjectComponentDispatcherGenerator.tt
- workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveBlittableSingularGameObjectComponentDispatcher.cs
- workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapKeyGameObjectComponentDispatcher.cs
- workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapValueGameObjectComponentDispatcher.cs
- workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveOptionalGameObjectComponentDispatcher.cs
- workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveRepeatedGameObjectComponentDispatcher.cs
- workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveSingularGameObjectComponentDispatcher.cs
- workers/unity/Assets/Generated/Source/improbable/gdk/tests/NestedComponentGameObjectComponentDispatcher.cs
- workers/unity/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponentGameObjectComponentDispatcher.cs
- workers/unity/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponentReaderWriter.cs
- workers/unity/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponentGameObjectComponentDispatcher.cs
- workers/unity/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponentReaderWriter.cs
- workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/GameObjectComponentDispatcherBase.cs
-------
Implemented invoking callbacks on the internal ReaderWriter implementations with the appropriate payloads, which should in turn invoke user callbacks in the future. This is done by the code generated GameObjectComponentDispatcherSystems, by looking for the appropriate ECS reactive components and passing the relevant update/event/etc objects into the Readers obtained through the SpatialOSBehaviourManager objects associated with each GameObject.
The current implementation assumes a currently nonexistent of a *ComponentName*.ReaderWriterImpl class. (That exact name and …
> UTY-589: Invoking callbacks on the readers

- workers/unity/Assets/Playground/Scripts/EntityInitialization/GameObjectInitializationSystem.cs
- workers/unity/Packages/com.improbable.gdk.core/Worker/WorkerBase.cs
-------
The GameObjectRepresentation stuff is supposed to act like a feature module, so Core things should not need references to it. This is only broken in one place at the moment, the EntityGameObjectLinker instance is a field of WorkerBase. This PR moves that into the GameObjectInitializationSystem, which is the only place using it.
The GameObjectInitializationSystem is also subject to change, currently it is in Playground while most of its functionality should be in the feature module. And we might want to expose the EntityGameObjectLinker to the users eventually, in which …
> UTY-938: Moved EntityGameObjectLinker out of WorkerBase

- workers/unity/Packages/com.improbable.gdk.core/Commands/WorldCommands.cs
- workers/unity/Packages/com.improbable.gdk.core/MutableView/MutableView.cs
- workers/unity/Packages/com.improbable.gdk.core/Systems/SpatialOSReceiveSystem.cs
- workers/unity/Packages/com.improbable.gdk.core/Systems/WorldCommandsCleanSystem.cs
- workers/unity/Packages/com.improbable.gdk.core/Systems/WorldCommandsCleanSystem.cs.meta
- workers/unity/Packages/com.improbable.gdk.core/Systems/WorldCommandsSendSystem.cs
- workers/unity/Packages/com.improbable.gdk.core/Systems/WorldCommandsSendSystem.cs.meta
- workers/unity/Packages/com.improbable.gdk.core/Utility/EntityBuilder.cs
- workers/unity/Packages/com.improbable.gdk.core/Worker/WorkerBase.cs
- workers/unity/Packages/com.improbable.gdk.playerlifecycle/Systems/PlayerCreation/HandleCreatePlayerRequestSystem.cs
- workers/unity/Packages/com.improbable.gdk.playerlifecycle/Systems/PlayerHeartbeat/HandlePlayerHeartbeatResponseSystem.cs
Added World Commands and all the associated types to match the current API.
Lots and lots of ~generated~ handwritten code.
Note that I've put the handling of the response ops into the `SpatialOSReceiveSystem` directly. If people prefer - I can refactor that out into a `WorldCommandsReceiveSystem` and make the dispatcher on the `SpatialOSReceiveSystem` internal such that the other system can register with it. 
It compiled! Tests coming soon ™️ 
Also going to come soon
@zeroZshadow
> UTY-764: World Commands Rewrite

- code_generator/GdkCodeGenerator/Templates/UnityReferenceTypeProviderGenerator.tt
- schema/improbable/gdk/tests/exhaustive_test.schema
Small change required to get `collection<bool>` to compile.
Un-commented the parts of schema, ran codegen and had Unity compile.
> UTY-450: Collection<Bool> Schema Codegen Fix

- code_generator/GdkCodeGenerator/Templates/UnityComponentConversionGenerator.tt
This PR fixes a bug where a schema component with a package of `connection` would cause compile errors.
This was due to not using FQN for `Improbable.Worker.Core.Connection` in generated code.
> UTY-350: Fix Connection Namespace Bug

- ci/download-core-sdk.sh
- workers/unity/Assets/Plugins/Improbable/Core/OSX/libworker.dylib.meta
- workers/unity/Assets/Plugins/Improbable/Core/OSX/worker.bundle.meta
- workers/unity/Assets/Plugins/Improbable/Core/OSX/worker.bundle/Contents.meta
- workers/unity/Assets/Plugins/Improbable/Core/OSX/worker.bundle/Contents/Info.plist
- workers/unity/Assets/Plugins/Improbable/Core/OSX/worker.bundle/Contents/Info.plist.meta
- workers/unity/Assets/Plugins/Improbable/Core/OSX/worker.bundle/Contents/MacOS.meta
- workers/unity/Assets/Plugins/Improbable/Core/OSX/worker.bundle/Contents/MacOS/worker.meta
- workers/unity/Packages/manifest.json
-------
Because the dylib didn't seem to load correctly for Mac.
Switched it to download the bundle instead.
ran it locally and the error that it can't download the worker library went away.
no docs needed
@jamiebrynes7
> changing which library we download for mac

- workers/unity/Assets/link.xml
- workers/unity/Assets/link.xml.meta
- workers/unity/Packages/com.improbable.gdk.core/Systems/CleanReactiveComponentsSystem.cs
Contributions: We are not currently taking public contributions - see our contributions policy. However, we are accepting issues and we do want your feedback.
Description
This adds assembly linker instructions to not strip classes needed for AOT and instantiation calls to methods that should be declared for AOT.
Original discussion in #143
Tests
Ensure iOS is built with these changes, performance doesn't regress and builds are done correctly
Documentation
https://brevi.link/il2cpp
Primary reviewers
> Adding support for IL2CPP to GDK

- code_generator/GdkCodeGenerator/Templates/UnityComponentConversionGenerator.tt
- workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveBlittableSingularTranslation.cs
- workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapKeyTranslation.cs
- workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapValueTranslation.cs
- workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveOptionalTranslation.cs
- workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveRepeatedTranslation.cs
- workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveSingularTranslation.cs
- workers/unity/Assets/Generated/Source/improbable/gdk/tests/NestedComponentTranslation.cs
- workers/unity/Assets/Generated/Source/improbable/gdk/tests/alternateschemasyntax/ConnectionTranslation.cs
- workers/unity/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponentTranslation.cs
- workers/unity/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsTranslation.cs
- workers/unity/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithCommandsTranslation.cs
- workers/unity/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithEventsTranslation.cs
- workers/unity/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponentTranslation.cs
- workers/unity/Assets/Playground/Scripts/Player/MoveLocalPlayerSystem.cs
- workers/unity/Assets/Playground/Scripts/Player/ProcessLaunchCommandSystem.cs
- workers/unity/Assets/Playground/Scripts/Player/ProcessRechargeSystem.cs
- workers/unity/Packages/com.improbable.gdk.playerlifecycle/Systems/PlayerCreation/HandleCreatePlayerRequestSystem.cs
- workers/unity/Packages/com.improbable.gdk.playerlifecycle/Systems/PlayerHeartbeat/HandlePlayerHeartbeatResponseSystem.cs
- workers/unity/Packages/com.improbable.gdk.transformsynchronization/Systems/InterpolateTransformSystem.cs
- workers/unity/Packages/com.improbable.gdk.transformsynchronization/Systems/LocalTransformSyncSystem.cs
This updates all systems to have the correct [ReadOnly] tags and readonly component types where needed.
Some slight reordering was also done for readability
> Correct ComponentType access tags

- code_generator/GdkCodeGenerator/src/Generation/Model/Details/UnityFieldDetails.cs
-------
Fixed bug in serialization codegen where enum fields updates would not be received.
Fixed issue in MonoBehaviour Playgrounds feature I'm working on in other branch
N/A
@jamiebrynes7 @samiwh
> Serialization codegen fix for enum fields

- workers/unity/Assets/Playground/Editor/Prefabs.meta
- workers/unity/Assets/Playground/Editor/Prefabs/PrefabPreprocessor.cs
- workers/unity/Assets/Playground/Editor/Prefabs/PrefabPreprocessor.cs.meta
- workers/unity/Assets/Playground/Resources/Prefabs/Spinner.prefab
-------
SpatialOS GDK for Unity takes ownership of MonoBehaviour activation if they [Require] Readers/Writers/Command Senders/Command Response Handlers. Let’s call these Spatial Behaviours.
This is because they should not be receiving OnEnable callbacks if their reader/writers are null.
When a prefab is instantiated, all of the active MonoBehaviours will be enabled immediately. This results in undesired behaviour if any of these MonoBehaviours are Spatial Behaviours. For example if they would like to, within OnEnable, immediately fetch SpatialOS component info through a Reader, …
> Preprocess prefabs before entering playmode or building

- workers/unity/Packages/com.improbable.gdk.core/Commands/WorldCommands.cs
- workers/unity/Packages/com.improbable.gdk.core/Systems/SpatialOSReceiveSystem.cs
This fixes the `ArgumentException: UpdatesProvider does not contain handle 0` exception that was seen when losing connection.
Fix copy paste errors in Provider logs
> Removing WorldCommandRequesters from worker entity when disconnected

- cloud_launch.json
- default_launch.json
- workers/unity/Packages/com.improbable.gdk.transformsynchronization/Components/BufferedTransform.cs
- workers/unity/Packages/com.improbable.gdk.transformsynchronization/Systems/ApplyTransformUpdatesSystem.cs
Upgraded to Bridge v2 in both current configurations. Also fixed a strange bug that presented itself whereby `BufferdTransform.LastTransformSnapshot` was uninitialised - so if you received an update with no location or rotation you would end up with bogus data being propagated to the interpolation system. 
1. Ran local deployment
2. Ran cloud deployment, connected client and ran around.
3. @DanailPenev Said he had tested mobile with bridge v2
N/A - not necessary
@samiwh
> UTY-595: Upgrade to Bridge v2

- workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveBlittableSingularTranslation.cs
- workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapKeyTranslation.cs
- workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapValueTranslation.cs
- workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveOptionalTranslation.cs
- workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveRepeatedTranslation.cs
- workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveSingularTranslation.cs
- workers/unity/Assets/Generated/Source/improbable/gdk/tests/NestedComponentTranslation.cs
- workers/unity/Assets/Generated/Source/improbable/gdk/tests/alternateschemasyntax/ConnectionTranslation.cs
- workers/unity/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponentTranslation.cs
- workers/unity/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsTranslation.cs
- workers/unity/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithCommandsTranslation.cs
- workers/unity/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithEventsTranslation.cs
- workers/unity/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponentTranslation.cs
- workers/unity/Packages/com.improbable.gdk.core/CoreSystemHelper.cs
- workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityComponentConversionGenerator.tt
-------
Currently you only receive ReceivedUpdates when you are authoritative over a component when its added. This isn't intuitive and instead we should always be added.
Best to read in commit order to avoid a lot of generated code.
Previous PR that implemented this on the previous core: #142
Checked that an update actually got added when not authoritative.
Will be added.
> UTY-375: Always have a ReceivedUpdates on ComponentAdded

- workers/unity/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponentCommandPayloads.cs
- workers/unity/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponentTranslation.cs
- workers/unity/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithCommandsCommandPayloads.cs
- workers/unity/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithCommandsTranslation.cs
- workers/unity/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponentCommandPayloads.cs
- workers/unity/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponentTranslation.cs
- workers/unity/Packages/com.improbable.gdk.core/Commands/CommandStorage.cs
- workers/unity/Packages/com.improbable.gdk.core/Commands/WorldCommands.cs
- workers/unity/Packages/com.improbable.gdk.core/Systems/SpatialOSReceiveSystem.cs
- workers/unity/Packages/com.improbable.gdk.core/Systems/WorldCommandsSendSystem.cs
- workers/unity/Packages/com.improbable.gdk.core/Utility/CommandRequestIdGenerator.cs
- workers/unity/Packages/com.improbable.gdk.core/Utility/CommandRequestIdGenerator.cs.meta
- workers/unity/Packages/com.improbable.gdk.playerlifecycle/Systems/PlayerCreation/HandleCreatePlayerRequestSystem.cs
- workers/unity/Packages/com.improbable.gdk.playerlifecycle/Systems/PlayerCreation/SendCreatePlayerRequestSystem.cs
- workers/unity/Packages/com.improbable.gdk.playerlifecycle/Systems/PlayerHeartbeat/HandlePlayerHeartbeatResponseSystem.cs
- workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityCommandPayloadGenerator.tt
- workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityComponentConversionGenerator.tt
Also use them for player requests
-------
Passes command contexts to commands so responders can use them
Adds an example case
Automated testing hard to do without mock connection
Tested locally using player creation
Missing
@jamiebrynes7 @MPeti01
> Pass in command contexts

- workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveBlittableSingularGameObjectComponentDispatcher.cs
- workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapKeyGameObjectComponentDispatcher.cs
- workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapValueGameObjectComponentDispatcher.cs
- workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveOptionalGameObjectComponentDispatcher.cs
- workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveRepeatedGameObjectComponentDispatcher.cs
- workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveSingularGameObjectComponentDispatcher.cs
- workers/unity/Assets/Generated/Source/improbable/gdk/tests/NestedComponentGameObjectComponentDispatcher.cs
- workers/unity/Assets/Generated/Source/improbable/gdk/tests/alternateschemasyntax/ConnectionGameObjectComponentDispatcher.cs
- workers/unity/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponentGameObjectComponentDispatcher.cs
- workers/unity/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsGameObjectComponentDispatcher.cs
- workers/unity/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithCommandsGameObjectComponentDispatcher.cs
- workers/unity/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithEventsGameObjectComponentDispatcher.cs
- workers/unity/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponentGameObjectComponentDispatcher.cs
- workers/unity/Assets/Playground/Scripts/EntityInitialization/GameObjectInitializationSystem.cs
- workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/GameObjectComponentDispatcherBase.cs
- workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/GameObjectDispatcherSystem.cs
- workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Injection/MonoBehaviourActivationManagerInitializationSystem.cs
- workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityGameObjectComponentDispatcherGenerator.tt
-------
We have been using the entity index instead of the entity to identify entities in our game object representation module. This is not unique (you need the index and the version) and caused some interesting bugs.
Ran it locally and checked whether the error still appeared. Now you can build out the gamelogic worker and connect/disconnect the client as often as you want without it throwing errors.
internal implementation
@JonasImprobable @zeroZshadow
> UTY-1106: replace entity index with entity

- workers/unity/Packages/com.improbable.gdk.tools/Common.cs
- workers/unity/Packages/com.improbable.gdk.tools/DownloadCoreSdk.cs
-------
because on my mac dotnet is installed in `/usr/local/share/dotnet/dotnet`... and the given error messages didn't really help with debugging.
it managed to download the libraries.
none needed
@jared-improbable
> adding more osx specific paths

- workers/unity/Packages/com.improbable.gdk.core/package.json
- workers/unity/Packages/manifest.json
-------
Moved all our dependencies to core except for the dependencies on built-in modules or, if they are not needed for the GDK (e.g. package manager ui).
It doesn't seem possible to move the dependencies on built-in modules to a different package as they will still be disabled.
Checked that everything still compiles
none
> Move dependencies from manifest to the core package

- workers/unity/Assets/Playground/Scripts/Worker/WorkerConnectorBase.cs
-------
Reconnecting was not always working, because the worker id got reused and it was only possible to locally connect an external worker by running `spatial local worker launch UnityClient default` as the worker type was otherwise not set.
tested it locally by testing whether reconnection attempts were now not failing due to reusing the worker id and checking that the worker type is always set (e.g. by directly starting the executable instead of using the spatial command)
none needed
@samiwh
> fixing reconnect and ensuring that worker type is set

- default_launch.json
-------
Disabling qos timeout for the default_launch config that should be used for `spatial local launch`.
That gets rid of the case where a worker disconnects when pausing the game and therefore causing a couple of issues.
tested it locally. Workers never disconnected and pausing/unpausing worked fine.
This should not be used for the cloud workflow
no
> Disable QOS timeout

- workers/unity/Assets/Playground/Scripts/EntityInitialization/EntityGameObjectCreator.cs
- workers/unity/Assets/Playground/Scripts/EntityInitialization/GameObjectInitializationSystem.cs
-------
Up until now we didn't clean up game objects which lead to exceptions being thrown upon disconnecting. 
tested it locally, errors are gone
none
> Destroy game objects upon destroying the world

- workers/unity/Assets/Playground/Scenes/ClientScene.unity
In the ClientWorker scene, the worker object had an offset of 50. Set this back to 0.
> Remove Offset from Client Worker

- workers/unity/Assets/Config.meta
- workers/unity/Assets/Config/GdkToolsConfiguration.asset
- workers/unity/Assets/Config/GdkToolsConfiguration.asset.meta
- workers/unity/Packages/com.improbable.gdk.tools/.DownloadCoreSdk/Program.cs
- workers/unity/Packages/com.improbable.gdk.tools/DownloadCoreSdk.cs
- workers/unity/Packages/com.improbable.gdk.tools/GdkToolsConfigurationEditorExtensions.cs
- workers/unity/Packages/com.improbable.gdk.tools/GdkToolsConfigurationEditorExtensions.cs.meta
- workers/unity/Packages/com.improbable.gdk.tools/GenerateCode.cs
- workers/unity/Packages/com.improbable.gdk.tools/ScriptableGdkToolsConfiguration.cs
- workers/unity/Packages/com.improbable.gdk.tools/ScriptableGdkToolsConfiguration.cs.meta
Made the GDK Tools locations configurable. For two reasons:
1. Required for a sister test project that isn't a Worker but wants generated code to test.
2. Required for FPL in the near(?) future.
Screenshots of the configuration window:
Without errors:
With errors:
Messed around with the paths and verified that the results were as expected.
N/A - Although probably should be (lower priority)
@jared-improbable @jessicafalk
> Make GDK Tool Paths Configurable

- workers/unity/Packages/com.improbable.gdk.core/AssemblyInfo.cs
- workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/GameObjectComponentDispatcherBase.cs
- workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Injection/IInjectableCreator.cs
- workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Injection/InjectableStore.cs
- workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Injection/InjectionConditionAttribute.cs
- workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Injection/MonoBehaviourActivationManager.cs
- workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Injection/RequiredFieldInjector.cs
- workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/ReadersWriters/GameObjectDelegates.cs
- workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/ReadersWriters/ReaderWriterBase.cs
Previously, the Monobehaviour base classes were internal and `AssemblyInfo.cs` exposed the internals of `Gdk.Core` to `Gdk.Generated`. However, this enforces a naming convention of generated code and creates a pseudo-dependency.
This PR address that by making things public and removing the exposing.
Ran playground + ran tests
N/A
@MPeti01 @JonasImprobable
> UTY-1143: Make Monobehaviour Base Classes Public

- workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveBlittableSingularTranslation.cs
- workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapKeyTranslation.cs
- workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapValueTranslation.cs
- workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveOptionalTranslation.cs
- workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveRepeatedTranslation.cs
- workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveSingularTranslation.cs
- workers/unity/Assets/Generated/Source/improbable/gdk/tests/NestedComponentTranslation.cs
- workers/unity/Assets/Generated/Source/improbable/gdk/tests/alternateschemasyntax/ConnectionTranslation.cs
- workers/unity/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponentTranslation.cs
- workers/unity/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsTranslation.cs
- workers/unity/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithCommandsTranslation.cs
- workers/unity/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithEventsTranslation.cs
- workers/unity/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponentTranslation.cs
- workers/unity/Packages/com.improbable.gdk.core/Systems/SpatialOSReceiveSystem.cs
- workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityComponentConversionGenerator.tt
Starting entities preview 12, unity will be strict in disallowing empty `IComponentData` tags to be added through `EntityManager.AddComponentData`
This change fixes the these in advance.
The upgrade itself is blocked on a bug fix that is required for adding tags through the EntityCommandBuffers.
> Add tags properly

- workers/unity/Assets/Playground/Editor/DisconnectOnCompilation.cs
- workers/unity/Assets/Playground/Editor/DisconnectOnCompilation.cs.meta
-------
Editor hangs frequently if code compiles while the editor is playing and connected to Spatial.
Ran locally and the game restarted after compilation as expected.
N/A
@jessicafalk @samiwh
> UTY-329: Stop the game in the editor during compilation.

- workers/unity/Packages/com.improbable.gdk.core/Systems/UpdateGroups.cs
- workers/unity/Packages/com.improbable.gdk.gameobjectcreation/GameObjectInitializationSystem.cs
-------
making sure that the GameObjectInitializationSystem alwazs runs before the GameObjectDispatcherSystem.
ran it locally. spinners are spinning
none
@firtina-improbable
> fixing update order of game object initialization

- workers/unity/Packages/com.improbable.gdk.tools/GenerateCode.cs
Added a marker file to `Temp` to indicate auto codegen has run already. This should stop the constant popups every recompile.
This gets removed when Unity closes so it will always generate when first started.
Tested workflow locally - worked nicely.
N/A 
@jared-improbable
> UTY-1176: Code Generation Workflow Tweaks

- workers/unity/Assets/Playground/Scripts/Worker/ClientWorkerConnector.cs
- workers/unity/Assets/Playground/Scripts/Worker/WorkerConnectorBase.cs
- workers/unity/Packages/com.improbable.gdk.playerlifecycle/Components/ShouldRequestPlayerTag.cs
- workers/unity/Packages/com.improbable.gdk.playerlifecycle/Components/ShouldRequestPlayerTag.cs.meta
- workers/unity/Packages/com.improbable.gdk.playerlifecycle/Systems/PlayerCreation/SendCreatePlayerRequestSystem.cs
Gets rid of two races (and technically adds another)
Removes the issues with workers starting at the same time of out of sequence.
Technically adds the two player race in but only in the case where a create player request is received, the worker receives it, sends the create entity command, then loses authority, then tries to respond.
(It only retries on an AuthorityLost failure)
Please add yourself as a reviewer if you have opinions.
> Clients retry getting a player. Workers connecting one at a time is enforced

- workers/unity/Packages/com.improbable.gdk.transformsynchronization/Systems/TickSystem.cs
Accidentally broke cubes by breaking dependencies.
> Changed tick system dependencies

- test-project/Assets/Generated/Improbable.Gdk.Generated.asmdef
- test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveBlittableSingularTranslation.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapKeyTranslation.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapValueTranslation.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveOptionalTranslation.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveRepeatedTranslation.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveSingularTranslation.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/NestedComponentTranslation.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/alternateschemasyntax/ConnectionTranslation.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponentTranslation.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsTranslation.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithCommandsTranslation.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithEventsTranslation.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponentTranslation.cs
- test-project/ProjectSettings/EditorSettings.asset
- workers/unity/Assets/Generated/Improbable.Gdk.Generated.asmdef
- workers/unity/Packages/com.improbable.gdk.core/CodegenAdapters/ComponentReplicationHandler.cs
- workers/unity/Packages/com.improbable.gdk.core/Systems/SpatialOSSendSystem.cs
- workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityComponentConversionGenerator.tt
This is both an optimisation and redesign.
With this redesign, the command sending will do less iterations, and uses faster component iterators to improve overall performance of the SpatialOSSendSystem.
It is also a good example of how Archetype Chunks can be used in our core, and how they work with code generation.
> Convert command sending to use archetype chunks

- workers/unity/Packages/com.improbable.gdk.core/Systems/CleanReactiveComponentsSystem.cs
- workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/Systems/SpatialOSReceiveSystemTests.cs
`entities@0.0.12-preview12` added the `EntityCommandBuffer.RemoveComponent(Entity, ComponentType` API. Cleaned up the cleanup system by using this API.
Drive-by to remove warning 
Ran unit tests for the `CleanReactiveSystem` & ran playground.
N/A
@zeroZshadow
> UTY-1188: Cleanup the Cleanup System

- workers/unity/Packages/com.improbable.gdk.core/Attributes/DisableAutoRegisterAttribute.cs
- workers/unity/Packages/com.improbable.gdk.core/Attributes/DisableAutoRegisterAttribute.cs.meta
- workers/unity/Packages/com.improbable.gdk.core/CodegenAdapters/ComponentDispatcherHandler.cs
- workers/unity/Packages/com.improbable.gdk.core/Systems/SpatialOSReceiveSystem.cs
- workers/unity/Packages/com.improbable.gdk.core/Systems/SpatialOSSendSystem.cs
- workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/Systems/SpatialOSSendSystemTests.cs
- workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/Systems/SpatialOSSendSystemTests.cs.meta
A few unit tests for the `SpatialOSSendSystem` - mostly focused around registering custom replicators.
These are tests
N/A
@zeroZshadow
> UTY-1099: Add Unit Tests to SpatialOS Send System

- workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/SpatialOSComponent.cs
-------
Add IsEntityOnThisWorker helper method to SpatialOsComponent, decided not to include a version that takes an Entity, to avoid iterating through a whole Dictionary
none
none
> UTY-1234: helper methods to determine if entity is on worker

- workers/unity/Packages/com.improbable.gdk.core/Commands/WorldCommands.cs
-------
update the warning message when creating an entity query request with `ResultType` as `SnapshotResultType` - based on Laura's feedback
none
none
> UTY-1173: update the warning message on entity query request creation

- test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveBlittableSingularTranslation.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapKeyTranslation.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapValueTranslation.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveOptionalTranslation.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveRepeatedTranslation.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveSingularTranslation.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/NestedComponentTranslation.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/alternateschemasyntax/ConnectionTranslation.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponentTranslation.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsTranslation.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithCommandsTranslation.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithEventsTranslation.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponentTranslation.cs
- workers/unity/Packages/com.improbable.gdk.core/CodegenAdapters/ComponentDispatcherHandler.cs
- workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityComponentConversionGenerator.tt
A couple changes:
* To maintain consistency with the changes in the `SpatialOSReceiveSystem` made in #330 - receiving an OP and not having the EntityId in the Worker throws instead of logs.
* A command response that is received after the entity has migrated/was deleted now just logs instead of errors (as this is a very much expected state).
* Driveby - make attribute for testing internal instead of public.
**Last commit is generated code**
Ran all tests + ran playground.
N/A
@jessicafalk
> Update Generated Code Logs and Exceptions

- .gitignore
- test-project/Assets/EditmodeTests/Components/BlittableComponentTests.cs
- test-project/Assets/EditmodeTests/GameObjectRepresentation/CommandSenders/CommandRequestHandlerTests.cs
- test-project/Assets/EditmodeTests/GameObjectRepresentation/CommandSenders/CommandResponseHandlerTests.cs
- test-project/Assets/EditmodeTests/GameObjectRepresentation/MonoBehaviourActivationManager/ActivationManagerTestBase.cs
- test-project/Assets/EditmodeTests/GameObjectRepresentation/MonoBehaviourActivationManager/AuthorityRequiredBehaviourActivationTestsBase.cs
- test-project/Assets/EditmodeTests/GameObjectRepresentation/MonoBehaviourActivationManager/CommandHandlerBehaviourActivationTests.cs
- test-project/Assets/EditmodeTests/GameObjectRepresentation/MonoBehaviourActivationManager/MultipleBehaviourActivationTests.cs
- test-project/Assets/EditmodeTests/GameObjectRepresentation/MonoBehaviourActivationManager/ReaderBehaviourActivationTests.cs
- test-project/Assets/EditmodeTests/GameObjectRepresentation/MonoBehaviourActivationManager/ReadersAndWriterBehaviourActivationTests.cs
- test-project/Assets/EditmodeTests/GameObjectRepresentation/MonoBehaviourActivationManager/RequestSenderBehaviourActivationTests.cs
- test-project/Assets/EditmodeTests/GameObjectRepresentation/MonoBehaviourActivationManager/WorkerTypeActivationTests.cs
- test-project/Assets/EditmodeTests/GameObjectRepresentation/MonoBehaviourActivationManager/WriterBehaviourActivationTests.cs
- test-project/Assets/EditmodeTests/GameObjectRepresentation/Readers/EventTests.cs
- test-project/Assets/EditmodeTests/GameObjectRepresentation/Readers/NonBlittableReaderTests.cs
- test-project/Assets/EditmodeTests/GameObjectRepresentation/Readers/NonBlittableWriterTests.cs
- test-project/Assets/EditmodeTests/GameObjectRepresentation/Readers/ReaderAuthorityTests.cs
- test-project/Assets/EditmodeTests/GameObjectRepresentation/Readers/ReaderDataTests.cs
- test-project/Assets/EditmodeTests/GameObjectRepresentation/Readers/ReaderWriterTestsBase.cs
- test-project/Assets/EditmodeTests/GameObjectRepresentation/Readers/ReaderWriterUpdateTests.cs
- test-project/Assets/EditmodeTests/GameObjectRepresentation/Readers/WriterSendUpdateTests.cs
- test-project/Assets/EditmodeTests/GameObjectRepresentation/RequiredFieldInjectorTests.cs
Small cosmetic changes - make all the namespaces in the `test-project` unified for easier viewing in the TestRunner. Driveby on the gitignore
Yes
N/A
> Unify Test Namespaces

- workers/unity/Packages/com.improbable.gdk.tools/.DownloadCoreSdk/Program.cs
- workers/unity/Packages/com.improbable.gdk.tools/DownloadCoreSdk.cs
This PR adds a logic that allows us to mark plugins compatibility platform after download
-------
We use different plugins for different platforms and we need to mark their compatibility in order to avoid conflicts in Unity (i.e. iOS Worker DLL and non-iOS one). This PR adds a logic that marks plugins compatibility based on our plugin structure.
Run Download plugins in Unity and ensure that plugins are marked as expected.
What would be a good place to document this?
> UTY-1181 Adding plugin directories compatibility logic

- workers/unity/Packages/com.improbable.gdk.tools/DownloadCoreSdk.cs
-------
Using `StandaloneLinuxUniversal` results in not having anything checked and therefore the plugin got never added to the build.. 
changing it to `StandaloneLinux64` as we only have a plugin for linux x64 anyway
ran a couple of cloud deployments and checked the builds
none needed
> ensuring linux plugin is added to the built out worker

- workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/EntityGameObjectLinker.cs
If a client quits and Unity starts destroying objects - there is no guarantee the order in which this happens.
So you can get into the situation where the GameObject has been destroyed but the linking system has not, meaning when OnDestroyManager occurs - it will throw null refs.
Misc changes due to code cleanup
Can test when the `pinned/starter-project` branch is ff'ed.
N/A
@mattyoung-improbable
> UTY-1306: Game Client Crash Fix

- workers/unity/Packages/com.improbable.gdk.tools/.DownloadCoreSdk/Program.cs
- workers/unity/Packages/com.improbable.gdk.tools/DownloadCoreSdk.cs
This reverts commit 45d879250ad9e59dec28c8e7f219c2a4954eca95.
-------
This reverts Plugin compatibility logic to initial state
Download logic goes back to initial state
> Revert "UTY-1181 Adding plugin directories compatibility logic (#445)"

- workers/unity/Packages/com.improbable.gdk.core/package.json
We don't use Burst ourselves, only through entities, which has its own dependency already.
Build all workers for local and cloud
> Remove the burst package as a requirement from Core

- workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Injection/MonoBehaviourActivationManager.cs
- workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/ReadersWriters/GameObjectDelegates.cs
- workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/ReadersWriters/ReaderWriterBase.cs
The default constructor doesn't initialise the Data field because this is a struct. This may cause NPEs. Calling the non-default constructor is a temporary solution.
> Replace usages of LogEvent default constructor

- workers/unity/Packages/com.improbable.gdk.tools/DownloadCoreSdk.cs
- workers/unity/Packages/com.improbable.gdk.tools/PluginPostprocessor.cs
- workers/unity/Packages/com.improbable.gdk.tools/PluginPostprocessor.cs.meta
-------
This PR adds logic for setting plugins compatibility. This allows marking plugins in Unity as only compatible with specific platforms based on the directory structure.
This eliminates the need to manually check/uncheck plugins when switching to iOS/Android platforms, while keeping plugins directory structure under `Assets/Plugins/Improbable`
Checkout clean GDK repo -> Open Unity Editor for the first time -> ensure there are no errors and plugins are marked for platform compatibility as expected
cc @DanailPenev
> Mobile local dev: Plugin compatibility logic

- docs/projects/fps/tutorial.md
The docs previously said to read the health from the `playerSpatialOsComponent` - which does not have any such method. Instead add a hint to add a monobehaviour on the player
Read the docs
Si!
> Clarify optional step in the tutorial

- test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveBlittableSingularTranslation.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapKeyTranslation.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapValueTranslation.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveOptionalTranslation.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveRepeatedTranslation.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveSingularTranslation.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/NestedComponentTranslation.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/alternateschemasyntax/ConnectionTranslation.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponentTranslation.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsTranslation.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithCommandsTranslation.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithEventsTranslation.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponentTranslation.cs
- workers/unity/Packages/com.improbable.gdk.core/CodegenAdapters/ComponentCleanupHandler.cs
- workers/unity/Packages/com.improbable.gdk.core/CodegenAdapters/ComponentReplicationHandler.cs
- workers/unity/Packages/com.improbable.gdk.core/Systems/CleanReactiveComponentsSystem.cs
- workers/unity/Packages/com.improbable.gdk.core/Systems/SpatialOSSendSystem.cs
- workers/unity/Packages/com.improbable.gdk.core/Systems/WorldCommandsCleanSystem.cs
- workers/unity/Packages/com.improbable.gdk.core/Systems/WorldCommandsSendSystem.cs
- workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/Systems/SpatialOSSendSystemTests.cs
- workers/unity/Packages/com.improbable.gdk.core/package.json
- workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityComponentConversionGenerator.tt
- workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/src/Generation/Model/Details/UnityEventDetails.cs
Read in commit order!
Removing component data array injection from core systems
Causes performance issues and looks like it's not going to be the API to bet on long term.
This PR doesn't not put anything into jobs because that will require a bit more thought for core systems.
All old tests still run and are still as relevant as they were.
Not user facing
@jamiebrynes7 @zeroZshadow
> Remove component data array from core

- workers/unity/Packages/com.improbable.gdk.core/Systems/SpatialOSSendSystem.cs
This PR forces the position component to be replicated last. Otherwise, the position change could trigger a load balancing operation that would cause valid update ops to be dropped.
Verified that position was hit last in the loop.
N/A - Should this be documented? 
> Force Position to Replicate Last

- workers/unity/Packages/com.improbable.gdk.buildsystem/Configuration/SpatialOSBuildConfiguration.cs
- workers/unity/Packages/com.improbable.gdk.buildsystem/Configuration/SpatialOSBuildConfigurationEditor.cs
- workers/unity/Packages/com.improbable.gdk.buildsystem/Configuration/WorkerBuildData.cs
- workers/unity/Packages/com.improbable.gdk.buildsystem/Util/BuildSupportChecker.cs
- workers/unity/Packages/com.improbable.gdk.buildsystem/Util/BuildSupportChecker.cs.meta
- workers/unity/Packages/com.improbable.gdk.buildsystem/WorkerBuilder.cs
- workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityWorkerMenuGenerator.tt
-------
Success:
Failure:
Completed:
Tested locally, if you don't have build support, it gives errors before building and on validation
- Needs to be done
> Add error messages for platforms that miss support

- docs/content/set-up-new-project.md
-------
Link to the `spatialos.Unityclient.worker.json` was pointing to the GameLogic one.
checked the preview mode
> fixing link to worker.json

- workers/unity/Packages/com.improbable.gdk.tools/.DownloadCoreSdk/Program.cs
-------
This PR adds postprocessing logic for packages download and renaming iOS libraries after download.
This is done to avoid name clash - iOS libraries have same names and will cause error when compiling Xcode project
Checkout clean repo -> Open Unity Editor -> Ensure Xcode project don't have clashing libraries
cc @DanailPenev
> Mobile local dev: Rename iOS libraries after downloading

- test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveBlittableSingular.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapKey.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapValue.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveOptional.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveRepeated.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveSingular.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/NestedComponent.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/alternateschemasyntax/Connection.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponent.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFields.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithCommands.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithEvents.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponent.cs
- workers/unity/Packages/com.improbable.gdk.core/Dynamic.meta
- workers/unity/Packages/com.improbable.gdk.core/Dynamic/Dynamic.cs
- workers/unity/Packages/com.improbable.gdk.core/Dynamic/Dynamic.cs.meta
- workers/unity/Packages/com.improbable.gdk.core/Dynamic/IDynamicInvokable.cs
- workers/unity/Packages/com.improbable.gdk.core/Dynamic/IDynamicInvokable.cs.meta
- workers/unity/Packages/com.improbable.gdk.core/Systems/SpatialOSReceiveSystem.cs
- workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityComponentDataGenerator.tt
Basically the same as the C# Worker SDK Dyanmic.ForEachComponent and Dynamic.ForComponent but with a slightly different interface.
Here's a silly example of printing all transform updates on a given entity
```
using System;
using System.Collections.Generic;
using Improbable.Gdk.Core;
using Improbable.Transform;
using Improbable.Worker;
using Improbable.Worker.Core;
using Unity.Entities;
using UnityEngine;
[WorkerType("UnityClient")]
public class ForEachComponentTest : MonoBehaviour
{
private struct Handler : Dynamic.IHandler
{
public World World;
public Dispatcher Dispatcher;
public EntityId EntityId;
public void Accept<TData, TUpdate>(uint componentId,
ComponentDeserializer<TData> deserializeComponentAdded,
UpdateDeserializer<TUpdate> deserializeComponentUpdate) where TData : …
```
> Added Dynamic in for generic component functionality

- workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityComponentConversionGenerator.tt
-------
Use `SchemaObject.IndexObject` to retrieve all events if multiple events are received as part of the same component update. `SchemaObject.GetObject` only gives you the last element in a repeated proto object (according to Sami and David) leading to us retrieving the last event multiple times.
Manual tests. I'm not aware of a way to test this nicely at a unit test level. Help appreciated.
As far as I understand we don't do explicit release/bugfix notes atm.
@samiwh @mattyoung-improbable
> UTY-1363: Use SchemaObject.IndexObject instead of GetObject to remove duplicate events

- ci/build-test.sh
-------
Adding build steps for `AndroidClient`, as well as a reference to the preparation script from `shared-ci`.
How to test the preparation script from `shared-ci` repo:
- Checkout this branch
- Run `ci/bootstrap.sh`
- Go in `.shared-ci` and checkout the `feature/add-android-dependencies-unity` branch
- Comment out the call to bootstrap in `<ROOT_DIR>/ci/build-test.sh` (this would reset back to master)
- Run `ci/build-test.sh`
- ???
- Profit
If your change will take a long …
> Added Android dependencies and building to ci script

- test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveBlittableSingularTranslation.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapKeyTranslation.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapValueTranslation.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveOptionalTranslation.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveRepeatedTranslation.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveSingularTranslation.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/NestedComponentTranslation.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/alternateschemasyntax/ConnectionTranslation.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponentTranslation.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsTranslation.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithCommandsTranslation.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithEventsTranslation.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponentTranslation.cs
- workers/unity/Packages/com.improbable.gdk.core/Authority/AuthorityComponents.cs
- workers/unity/Packages/com.improbable.gdk.core/CodegenAdapters/AcknowledgeAuthorityLossHandler.cs
- workers/unity/Packages/com.improbable.gdk.core/CodegenAdapters/AcknowledgeAuthorityLossHandler.cs.meta
- workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/ReadersWriters/IWriter.cs
- workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/ReadersWriters/ReaderWriterBase.cs
- workers/unity/Packages/com.improbable.gdk.core/Systems/AcknowledgeAuthorityLossSystem.cs
- workers/unity/Packages/com.improbable.gdk.core/Systems/AcknowledgeAuthorityLossSystem.cs.meta
- workers/unity/Packages/com.improbable.gdk.core/Worker/Worker.cs
- workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityComponentConversionGenerator.tt
You can ack authority loss in the ecs and in monobehaviours
In the ecs this is by writing to a bool on the authority component
In  monobehaviours this is a send api on the writer.
> Soft handover - now 50% less soft

- workers/unity/Packages/com.improbable.gdk.core/Utility/Snapshot.cs
Another small FR - return the EntityId used when adding an entity to a snapshot.
Printed the return value to test - looks good.
Updated the docstrings
> Return EntityId when adding entity to snapshot

- docs/content/mobile/android/local-deploy.md
- docs/content/mobile/android/setup.md
- docs/content/mobile/android/ways-to-test.md
- docs/content/mobile/ios/local-deploy.md
- docs/content/mobile/ios/setup.md
- docs/content/mobile/ios/ways-to-test.md
- docs/content/mobile/overview.md
- docs/content/modules/core-and-feature-module-overview.md
- docs/toc.md
-------
All the documentation on how to run local deployments for iOS and Android and some additional information.
This is a first version that we publish just to have docs ready and will improve them over time
checked the preview. everything looked good
this is it
> adding all the mobile docs

- docs/content/gameobject/readers-writers.md
Added docs for the writer API for sending authority loss imminent acknowledgements. One or two little drivebys.
Not sure if we want to add docs for the ECS workflow as well? Would probably require a full code sample 
Looked at improbadoc output - looked good.
Yes
@samiwh
> Add AuthorityLossImminent acknowledgement docs 

- docs/toc.md
* Removed gerunds ("ing" words) to standardise verbs as is our new bossy thing
* Removed `<h4>` which was 
making the titles grey rather than black
* Removed the colons on titles (except where they are a calls to action - "checkout:" and  "Visit our GitHib:".
* Removed stars at start of title link - not needed.
* Removed extra "+" where not needed.
* Standardised capitalisation
Can't do much about the annoying indent for titles in a list, unforutunately.
> ToC formatting tidy-up and standardize

- CHANGELOG.md
- workers/unity/Packages/com.improbable.gdk.tools/GenerateCode.cs
-------
Prepend the following warning to copied schema files:
```
// ------------------------------------------------------------------------
// WARNING: DO NOT EDIT.
// Any changes made to this file will be overwritten by the Code Generator.
// ------------------------------------------------------------------------
```
tested locally - schema files in `from_gdk_packages` directory all have the text prepended
none
If your change will take a long time to review, you can name at most two primary reviewers who are ultimately responsible for …
> UTY-1060: Prepend warning to copied schema files

- ci/build-test.sh
-------
temporarily stop building android clients until TeamCity android issue is fixed
TC
N/A
> Temporarily stop building AndroidClient

- CHANGELOG.md
- test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveBlittableSingular.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapKey.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapValue.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveOptional.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveRepeated.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveSingular.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/NestedComponent.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/alternateschemasyntax/Connection.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponent.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFields.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithCommands.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithEvents.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponent.cs
- workers/unity/Packages/com.improbable.gdk.core/Components/ISnapshottable.cs
- workers/unity/Packages/com.improbable.gdk.core/Components/ISnapshottable.cs.meta
- workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityComponentDataGenerator.tt
This PR adds an interface to all generated components which allows you to take a snapshot of that component. The snapshot is done simply through serialize/deserialize, no deep copy implementations required.
Commits are ordered.
Generated code and checked implementation.
Changelog entry. Will probably need some docs I guess 
@samiwh
> Add ISnapshottable interface to generated components

- ci/build-test.sh
Signed-off-by: Paul Balaji <paulbalaji@improbable.io>
-------
reinstate android builds
relies on changes to shared-ci: https://github.com/spatialos/gdk-for-unity-shared-ci/pull/9
passes CI fine on troublesome agents when trying out the dev branch on shared-ci
n/a
> Reinstate android builds

- CHANGELOG.md
- test-project/Assets/.Schema/improbable/gdk/tests/alternate_schema_syntax.schema
- test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveBlittableSingular.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveSingular.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/NestedComponent.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/alternateschemasyntax/Connection.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/alternateschemasyntax/ConnectionGameObjectComponentDispatcher.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/alternateschemasyntax/ConnectionReaderWriter.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/alternateschemasyntax/ConnectionTranslation.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/alternateschemasyntax/RandomDataType.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponent.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponent.cs
- workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityComponentDataGenerator.tt
This PR fixes the problem described in #607 and adds a test case to our test schema to stop regressions.
Added a test case.
Changelog
@firtina-improbable @paulbalaji
> Bugfix - Code generation with fields called value

- CHANGELOG.md
- test-project/Assets/EditmodeTests/GameObjectRepresentation/MonoBehaviourActivationManager/ActivationManagerTestBase.cs
- test-project/Assets/EditmodeTests/GameObjectRepresentation/Readers/EventTests.cs
- test-project/Assets/EditmodeTests/GameObjectRepresentation/Readers/NonBlittableReaderTests.cs
- test-project/Assets/EditmodeTests/GameObjectRepresentation/Readers/NonBlittableWriterTests.cs
- test-project/Assets/EditmodeTests/GameObjectRepresentation/Readers/ReaderDataTests.cs
- test-project/Assets/EditmodeTests/GameObjectRepresentation/Readers/ReaderWriterTestsBase.cs
- test-project/Assets/EditmodeTests/GameObjectRepresentation/RequiredFieldInjectorTests.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveBlittableSingularReaderWriter.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapKeyReaderWriter.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapValueReaderWriter.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveOptionalReaderWriter.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveRepeatedReaderWriter.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveSingularReaderWriter.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/NestedComponentReaderWriter.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/alternateschemasyntax/ConnectionReaderWriter.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponentReaderWriter.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsReaderWriter.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithCommandsReaderWriter.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithEventsReaderWriter.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponentReaderWriter.cs
- workers/unity/Assets/Playground/Scripts/MonoBehaviours/UpdateSpinnerColor.cs
- workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/ReadersWriters/ReaderWriterBase.cs
- workers/unity/Packages/com.improbable.gdk.core/Systems/WorkerSystem.cs
- workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityReaderWriterGenerator.tt
Added two things:
- A `HasEntity` method on the `WorkerSystem`
- The ability to access the EntityId from a reader/writer.
Added a test for the `EntityId` property. Interestingly, this revealed that the Reader Writers previously didn't assert against the underlying entity having an `EntityId`! 
Changelog. Will open another PR for API docs 
> Some misc improvements

- workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/CodeGeneration/CodeGeneration.csproj
- workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/CodeGeneration/Model/SchemaBundleV1/Bundle.cs
- workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/CodeGeneration/Model/SchemaBundleV1/Common.cs
- workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/CodeGeneration/Model/SchemaBundleV1/ComponentDefinitionRaw.cs
- workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/CodeGeneration/Model/SchemaBundleV1/EnumDefinitionRaw.cs
- workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/CodeGeneration/Model/SchemaBundleV1/TypeDefinitionRaw.cs
- workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/CodeGeneration/Tests/Model/SchemaBundleV1/JsonParsingTests.cs
- workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/CodeGeneration/Tests/Model/SchemaBundleV1/Resources/exhaustive_bundle.json
- workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator.sln
**Only reason this PR is so large is because of test JSON**
- Add the underlying library for the code generator to be rebased on top of.
- Add the JSON structure of the `bundle.json`
- Adds a simple test to make sure the test project schema bundle is parsed without throwing.
Further tests will be required to ensure the parsing is actually correct. 
Yes we have tests!
N/A
@jared-improbable @zeroZshadow
> Schema Bundle JSON Structure

- CHANGELOG.md
- workers/unity/Packages/com.improbable.gdk.buildsystem/WorkerBuilder.cs
-------
- updated `Clean` function to clean the entire `build/assembly` directory, instead of just `build/assembly/worker`
tried out locally, renamed stuff to reproduce error and "clean all workers" button now fixes the issue reported in the ticket
n/a
> "Clean all workers" now cleans worker configs

- docs/content/glossary.md
- docs/projects/fps/tutorial.md
ToCs would help navigating the glossary a lot. They should be useful for the tutorial and getting started, too.
Local preview
Health pickup tutorial looks like this:
Glossary looks like this:
> Docs: Add ToCs

- CHANGELOG.md
- workers/unity/spatialos.UnityClient.worker.json
- workers/unity/spatialos.UnityGameLogic.worker.json
Ran it locally with `spatial local launch`, `spatial local worker launch UnityGameLogic default` and `spatial local worker launch UnityClient default` to start up multiple workers. Worked fine.
release notes
> Fixing launch configuration for OSX

- workers/unity/Assets/Config/GdkToolsConfiguration.json
- workers/unity/Assets/Playground/Config/BuildConfiguration.asset
- workers/unity/Assets/Playground/Scripts/UI/ConnectionScreenController.cs
- workers/unity/Packages/com.improbable.gdk.core/Utility/CommandLineUtility.cs
- workers/unity/Packages/com.improbable.gdk.mobile/Android/Utility/LaunchArguments.cs
- workers/unity/Packages/com.improbable.gdk.mobile/Android/Utility/LaunchArguments.cs.meta
- workers/unity/Packages/com.improbable.gdk.mobile/Editor.meta
- workers/unity/Packages/com.improbable.gdk.mobile/Editor/Improbable.Gdk.Mobile.Editor.asmdef
- workers/unity/Packages/com.improbable.gdk.mobile/Editor/Improbable.Gdk.Mobile.Editor.asmdef.meta
- workers/unity/Packages/com.improbable.gdk.mobile/Editor/LaunchMenu.cs
- workers/unity/Packages/com.improbable.gdk.mobile/Editor/LaunchMenu.cs.meta
- workers/unity/Packages/com.improbable.gdk.tools/GdkToolsConfiguration.cs
- workers/unity/Packages/com.improbable.gdk.tools/GdkToolsConfigurationEditorExtensions.cs
- workers/unity/Packages/com.improbable.gdk.tools/LocalLaunch.cs
- workers/unity/Packages/com.improbable.gdk.tools/MenuPriorities.cs
- workers/unity/ProjectSettings/GraphicsSettings.asset
- workers/unity/ProjectSettings/ProjectSettings.asset
This PR contains some additional changes that were related or required:
* Updating the local deployment launcher to use a runtime ip if provided.
* Fix AndroidClient build options.
* Mobile connection screen now skips input if IP is provided through launch argument.
I've build and run for the phone a few times with different settings.
> Adding support for launching an android client over ADB from the editor

- workers/unity/Packages/com.improbable.gdk.core/Subscriptions/StandardSubscriptionManagers/EntitySubscriptionManager.cs
- workers/unity/Packages/com.improbable.gdk.core/Subscriptions/Subscription.cs
- workers/unity/Packages/com.improbable.gdk.core/Subscriptions/Systems/RequireLifecycleSystem.cs
- workers/unity/Packages/com.improbable.gdk.core/Subscriptions/UpdateGroups.cs
- workers/unity/Packages/com.improbable.gdk.core/Subscriptions/UpdateGroups.cs.meta
- workers/unity/Packages/com.improbable.gdk.core/Systems/UpdateGroups.cs
- workers/unity/Packages/com.improbable.gdk.gameobjectcreation/GameObjectInitializationSystem.cs
- workers/unity/Packages/com.improbable.gdk.gameobjectcreation/UpdateGroups.cs
- workers/unity/Packages/com.improbable.gdk.gameobjectcreation/UpdateGroups.cs.meta
- workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityCommandSenderReceiverGenerator.tt
Fixed a typo causing subscriptions to incorrectly register themselves as unavailable with subscription aggregates and not as available.
Fixed an issue with some subscriptions being set twice.
Fixed an issue with gameobjects being created later in the frame than the system enabling them.
> Subscriptions fixes

- ci/bootstrap.sh
- ci/build-test.sh
- workers/unity/Packages/com.improbable.gdk.buildsystem/WorkerBuilder.cs
-------
Added an optional parameter to enable switching the scripting backend to either il2cpp or mono. This is only exposed when building via cmd. When running it via the menu items in the editor the one that is active in the player settings will be chosen.
ran it locally. next step is to test it in ci. 
no documentation needed
@firtina-improbable @paulbalaji
> Add cmd option to choose il2cpp/mono in build tests

- ci/bootstrap.sh
- ci/build-ios.sh
- workers/unity/ProjectSettings/ProjectSettings.asset
-------
This PR adds script that builds iOS XCode project, copies needed fastlane files and triggers fastlane distributable iOS build
linked to: https://github.com/spatialos/gdk-for-unity-shared-ci/pull/11
Run the script locally -> ensure distributable .ipa build is created
Next step is to verify this on CI
> Adding script for distributable iOS builds

- docs/content/get-started/set-up.md
Tested in improbadoc preview
Ignore the platform & label = mac, it is required by our segment API but we have other ways to get the user's platform
> track link for zip dwnld

- CHANGELOG.md
- workers/unity/Packages/com.improbable.gdk.tools/GenerateCode.cs
chmod on macos would succeed, if there are no spaces in the path. With spaces in the path the whole code generation would fail due to a permission denied error.
tested it locally on my mac
none needed 
> ensure chmod runs even with spaces in path (OSX)

- workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/CodeGeneration/FileHandling/FileSystem.cs
- workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/CodeGeneration/FileHandling/FileWrapper.cs
- workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/CodeGeneration/FileHandling/IFile.cs
- workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/CodeGeneration/FileHandling/IFileSystem.cs
- workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/CodeGeneration/Jobs/CodegenJob.cs
- workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/CodeGeneration/Jobs/JobRunner.cs
- workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/CodeGeneration/Model/BuiltInSchemaTypes.cs
- workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/CodeGeneration/Tests/Model/SchemaBundleV1/JsonParsingTests.cs
- workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/src/CodeGenerator.cs
We previously were relying on the DLL for JSON parsing for code generation from the SDK. With the move to schema bundles, this is no longer the case. This PR pulls across the `FileHandling`, `Jobs` and `BuiltInSchemaTypes` files and does a bit of touching up on them. 
It builds.  The real tests come later.
N/A. All internal for now.
@zeroZshadow @jessicafalk
> UTY-1503: Pull across parts of the old CodeGeneration library.

- mobile_launch.json
- workers/unity/Packages/com.improbable.gdk.mobile/Worker/MobileWorkerConnector.cs
This PR switches mobile module to use KCP instead of TCP + adds meaningful connection timeout. Timeout seem to not have effect at the moment
Run mobile local deployment -> Run mobile client -> Ensure client is connected correctly to the deployment
Do we need to change any docs for this? I wasn't able to find any relevant reference.
> Switching to KCP on mobile worker + use small connection timeout

- CHANGELOG.md
- workers/unity/Packages/com.improbable.gdk.transformsynchronization/Systems/InterpolateTransformSystem.cs
Fix a crash bug in the Transform sync feature module.
Includes a slight optimization to avoid dynamic buffer resizes.
Ran the playground project locally and went through the same steps which previously caused the crash.
> Fix underflow memory allocation crash in transform sync.

- CHANGELOG.md
- workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/src/Generation/Model/UnitySchemaFile.cs
For legacy reasons, `Vector3f`, `Coordinates`, etc are treated as built in types (in the SDK JSON parsing library). 
When the command definitions are parsed, we explicitly check for built in types despite only ever being able to have a composite(?) type `type`, i.e. - a `Coordinates` (allowed) vs an `int` (not-allowed). 
This logic caused problems when using the standard library types that straddled these definitions.
I.e. - 
```
package faeborn.schema.movement;
import "improbable/standard_library.schema";
type Empty {}
component ClientMovementRequest {
id = 1000;
improbable.Coordinates latest = 1;
command Empty start_move(improbable.Coordinates);
}
```
Would cause null refs.
This PR fixes this in commands (and potentially events) by allowing the SchemaProcessor to assign the non-raw …
> UTY-1627: Fix Codegen Nullref

- workers/unity/Packages/com.improbable.gdk.buildsystem/package.json
- workers/unity/Packages/com.improbable.gdk.core/package.json
- workers/unity/Packages/com.improbable.gdk.gameobjectcreation/package.json
- workers/unity/Packages/com.improbable.gdk.mobile/package.json
- workers/unity/Packages/com.improbable.gdk.playerlifecycle/package.json
- workers/unity/Packages/com.improbable.gdk.testutils/package.json
- workers/unity/Packages/com.improbable.gdk.tools/package.json
- workers/unity/Packages/com.improbable.gdk.transformsynchronization/package.json
Forgot to do this in the upgrade - actually required given that `2018.2` won't work without the incremental compiler (I believe).
> Update unity version in package.json

- CHANGELOG.md
- workers/unity/Assets/Playground/Scripts/Camera/InitCameraSystem.cs
- workers/unity/Assets/Playground/Scripts/UI/ConnectionScreenController.cs
- workers/unity/Assets/Playground/Scripts/UI/InitUISystem.cs
- workers/unity/Assets/Playground/Scripts/Worker/AndroidClientWorkerConnector.cs
- workers/unity/Assets/Playground/Scripts/Worker/iOSClientWorkerConnector.cs
- workers/unity/Packages/com.improbable.gdk.core/Worker/WorkerConnector.cs
We didn't have any specific handling for disconnect on mobile. Whenever the server was killed, mobile client worker is going to get to weird stale state where it doesn't technically hang, but nothing was happening and the client wasn't interactive.
This PR adds the code to restore Playground to "Ready to connect" mode
Run Playground locally and ensure that when server is disconnected we are ready to connect again ->
After the server is back, we should be able to reconnect
> [UTY-1613] Gracefully handle disconnect in Playground

- CHANGELOG.md
- workers/unity/Packages/com.improbable.gdk.buildsystem/Util/BuildSupportChecker.cs
- workers/unity/Packages/com.improbable.gdk.buildsystem/WorkerBuilder.cs
- workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityWorkerMenuGenerator.tt
A last minute addition to the `0.1.4` release ~_grumble grumble_~ - adjusting the build system to skip builds that you don't have build support for (without cancelling the other builds). 
For example - if you build all workers without mobile support installed you would get the following messages in the console.
Also the static `Build` method still throws if build support is missing (such that the process _actually_ returns an error exit code) - so that behavior is unchanged.
Tested a build locally and via command line.
Yes
If your change will take a long time to review, you can name at most two primary reviewers who are ultimately responsible for …
> Build System Tweaks

- workers/unity/Packages/com.improbable.gdk.core/Subscriptions/CalllbackManagers/EntityRemovedCallbackManager.cs
- workers/unity/Packages/com.improbable.gdk.core/Systems/EntitySystem.cs
No longer a concept of temporarily removed entities. Should fix the initial add - remove - add problem.
> Removed the concept of a temporarily removed entity

- CHANGELOG.md
- workers/unity/Packages/com.improbable.gdk.mobile/Editor/LaunchMenu.cs
The Android launch menu item would fail if you had spaces in your project path.
This is now fixed
Changed my path to have spaces to reproduce the issue. Added a fix and confirmed that it now launches properly.
@jessicafalk
> Fix ADB throwing an error if your project path has spaces in it

- CHANGELOG.md
- workers/unity/Packages/com.improbable.gdk.tools/Common.cs
In our `package.json` parsing code, if a package did not have a `dependencies` field, it would throw exceptions despite this being a valid package declaration.
This could cause code generation to fail as @polartron experienced. 
Added a mock package with no `dependencies` field. Ran code generation, it was all good.
N/A
Yes
> Fix Package Traversal Exception

- .buildkite/premerge.steps.yaml
- .buildkite/trigger.sh
- ci/build.sh
- ci/test.sh
Run all build and test steps in parallel. In the best case this reduces the CI time from ~15 minutes to 5 minutes. This does require _more_ agents available, the case where everything is sequential (on one agent), this method will be slower. However, we expect to have more than 1 agent available for a build. 
- Added `build.sh` which acts as a passthrough to the shared-ci version which correctly sets up the environment and sets the worker type, etc.
- Made `test.sh` able to be run from standalone on the CI agent.
- Removed `build-test.sh` from Buildkite altogether!
- Early out for building iOS on Windows.
Ran on Buildkite
N/A
> Run Build & Test in Parallel on Buildkite

- workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityCommandSenderReceiverGenerator.tt
- workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityComponentReaderWriterGenerator.tt
- workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityComponentUpdateManagerGenerator.tt
Fixed an issue where we didn't check the component existed before checking it's authority state.
> Subscription component check

- docs/content/mobile/android/local-deploy.md
- docs/content/mobile/ios/local-deploy.md
Remove overly specific network terminology.
**Pages state**
>2. Make sure your computer and your mobile device are both connected to the same wireless network.
**This should say:**
>2. Make sure your computer and your mobile device are both connected to the same network.
None
> Remove overly specific network terminology.

- docs/content/mobile/android/cloud-deploy.md
Add USB debugging acceptance step to the Android cloud documented workflow. A copy paste job from the local workflow.
served improbadoc locally to ensure correct rendering
> Add USB debugging accept step

- test-project/Assets/.Schema/improbable/gdk/tests/exhaustive_test.schema
- test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapKeyData.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapValueData.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveOptionalData.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveRepeatedData.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveSingularData.cs
- workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/CodeGeneration/Model/SchemaBundleV1/AnnotationRaw.cs
- workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/CodeGeneration/Model/SchemaBundleV1/Common.cs
- workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/CodeGeneration/Model/SchemaBundleV1/ComponentDefinitionRaw.cs
- workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/CodeGeneration/Model/SchemaBundleV1/EnumDefinitionRaw.cs
- workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/CodeGeneration/Model/SchemaBundleV1/TypeDefinitionRaw.cs
- workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/CodeGeneration/Tests/Model/SchemaBundleV1/Resources/exhaustive_bundle.json
- workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/src/Generation/Model/Details/DetailsStore.cs
Add annotations support for schema. 
- Regenerated example JSON
- Added `AnnotationRaw` class
- Renamed `UserType` -> `FullyQualifiedReference` as it was a more appropriate name.
- Applied a bugfix where blittable checks would be incorrect for components defined with the `data` schema syntax
PR is in commit order.
Will update exhaustive test schema in another PR to not pollute this one. See #746 
Ran the one and only unit test 💯 
N/A
> Add Schema Annotations Support

- cloud_launch.json
- default_launch.json
- mobile_launch.json
Remove the transitional template from Playground, as the new runtime is now the default runtime.
`spatial local launch`
None
@zeroZshadow
> Remove the transitional template from Playground, as the new runtime is now the default runtime.

- CHANGELOG.md
- workers/unity/Packages/com.improbable.gdk.core/Worker/Worker.cs
Now with 2018.3.5f1, we no longer need to force disable the protocolLogging.
Created a cloud deployment with logging enabled on GameLogic workers.
Didn't crash, saw nice protocol logs appear.
Added changelog
> Remove UTY-1578 workaround

- workers/unity/Assets/Playground/Config/BuildConfiguration.asset
Changes enacted to gdk-for-unity\workers\unity\Assets\Playground\Config\BuildConfiguration.asset
**Worker Type** > **iOSClient** > **Enironments** > **Cloud** > **Build Platforms** changed from **None** to **iOS**
**Worker Type** > **AndroidClient** > **Enironments** > **Cloud** > **Build Platforms** changed from **None** to **Android**
Enabled the **Development Build** option for all local workers.
Disabled **Run Headless** for iOS Client Cloud builds.
Tested on macOS. It work.
None.
> Check the correct boxes in BuildConfiguration.asset

- workers/unity/Packages/com.improbable.gdk.core/Worker/Worker.cs
just removing some excess `GetOrCreateManager<>` calls as they're already in `ReactiveComponentsHelper.AddCommonSystems(World)`
run locally
n/a
> Remove duplication when adding reactive component systems

- workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/src/Generation/Model/Details/DetailsStore.cs
There was a small bug in how nested types were found where calling `GetNestedTypes` on `Foo.Bar` could potentially return `Foo.BarBaz.Foo` as a child. Fixed this by appending a trailing period to the parent qualified name for the name matching such that we check potential children against `Foo.Bar.` instead of `Foo.Bar`.
I can add an explicit test to cover this - would require adding additional test schema however. Thoughts? 
N/A
N/A
> Fix nested types edge case

- workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/Systems/CleanReactiveComponentsSystemTests.cs.meta
- workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/Systems/CleanTemporaryComponentsSystemTests.cs
- workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/Systems/CleanTemporaryComponentsSystemTests.cs.meta
This was actually a very quick one - the system that cleans reactive components and that which removes temporary components was split, but the test was using the wrong one 😂 
Ran them. 
N/A
> Fix broken test

- workers/unity/Packages/com.improbable.gdk.playerlifecycle/Systems/PlayerHeartbeat/PlayerHeartbeatInitializationSystem.cs
Unblocks upgrade path to entities.24
Quick fix of a wrong ComponentType used in a query. Doesn't change anything functionally, but stops Entities .24 packages from throwing as this has an added check.
> Quick fix of a wrong query type

- .buildkite/hooks/pre-exit
- ci/purge.ps1
Pre exit hook to kill all dangling processes in Buildkite.
Written in Powershell and uses `handle64` to find processes. I went with a blacklist approach as blindly killing processes touching the directory didn't end too well 😬 
Currently kills all `dotnet`, `Unity`, and `UnityPackageManager` processes
> Add pre exit hook for Buildkite

- workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/CodeGeneration/Jobs/JobRunner.cs
This PR contains a fix for a code generation regression introduced in #767. TL;DR - boolean check was wrong way around.
Tested on the `test-project` on the `experimental/core-refactor` branch (where the regression was observed) - behavior was as expected.
N/A
> Fix Codegen Regression

- CHANGELOG.md
- workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityComponentDataGenerator.tt
- workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityEnumContent.tt
- workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityTypeContent.tt
Added the `[Serializable]` tag to all Types, Enums, and Snapshots.
Fixes #677 
Created a temporary `ScriptableObject` with public fields of the now serializable types, and confirmed that they indeed shop up in the editor.
Small caveat, the Nullable/Option types do NOT show up, as Unity does not render them by default.
This could possible be worked around using generated inspectors, but will not be trivial.
NOT YET, post release to avoid conflics.
> Make Types, Enums, and Snapshots Serializable.

- workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/Subscriptions.meta
- workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/Subscriptions/AggregateSubscriptionTests.cs
- workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/Subscriptions/AggregateSubscriptionTests.cs.meta
- workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/Subscriptions/RequiredSubscriptionsInfoTests.cs
- workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/Subscriptions/RequiredSubscriptionsInfoTests.cs.meta
- workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/Subscriptions/StandardSubscriptionTests.cs
- workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/Subscriptions/StandardSubscriptionTests.cs.meta
- workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/Subscriptions/SubscriptionTestBase.cs
- workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/Subscriptions/SubscriptionTestBase.cs.meta
Some tests for: 
- the standard `SubscriptionManager` implementations.
- `AggregateSubscription` behaviour
- `RequiredSubscriptionFieldInfo` behaviour
More tests will come in the form of integration tests with Reader/Writer injection. 
Yes we are tests.
N/A
> Add Some Subscription Tests

- docs/content/mobile/ios/cloud-deploy.md
- docs/content/mobile/ios/local-deploy.md
Due to this error:
I've added this alert:
to both local and cloud workflow docs.
I encountered the error.
I rendered the changes in improbadoc.
> Add a callout that iOS Simulator is incombatible with the FPS Starter Project

- docs/content/mobile/ios/cloud-deploy.md
Remove references to the *SpatialOS* > *Launch mobile client* > *iOS Device* flow, as that flow is yet to be released.
> Remove SpatialOS* > *Launch mobile client* > *iOS Device* flow from docs.

- docs/content/mobile/android/cloud-deploy.md
- docs/content/mobile/ios/cloud-deploy.md
* Explicitly specifies that users must input their `id` into the **Development Auth Token** field.
* Cuts duplicated steps on creating the script.
> Docs: Use `id` not `tokenSecret`.

- workers/unity/Packages/com.improbable.gdk.core/Collections/ReceivedMessagesSpan.cs
- workers/unity/Packages/com.improbable.gdk.core/Commands/CommandComponents.cs
- workers/unity/Packages/com.improbable.gdk.core/Subscriptions/CalllbackManagers/CommandRequestCallbackManager.cs
- workers/unity/Packages/com.improbable.gdk.core/Systems/CommandSystem.cs
- workers/unity/Packages/com.improbable.gdk.core/Worker/DiffStorage.cs
- workers/unity/Packages/com.improbable.gdk.core/Worker/WorldCommandsReceivedStorage.cs
- workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/CommandDiffStorageGenerator.tt
- workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityCommandPayloadGenerator.tt
Command requests can now be queried by entity ID and responses by request ID. This is to match the component update API that allows searching updates by entity ID.
> Get commands received by index

- workers/unity/Packages/com.improbable.gdk.core/Systems/ComponentUpdateSystem.cs
- workers/unity/Packages/com.improbable.gdk.core/View/View.cs
- workers/unity/Packages/com.improbable.gdk.core/View/ViewStorage.cs
- workers/unity/Packages/com.improbable.gdk.core/Worker/MessagesToSend.cs
- workers/unity/Packages/com.improbable.gdk.core/Worker/SerializedMessagesToSend.cs
- workers/unity/Packages/com.improbable.gdk.core/Worker/ViewDiff.cs
- workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityComponentSenderGenerator.tt
- workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/ViewStorageGenerator.tt
Sending an update will update the view. This does not make the more intrusive changes, like separating the writer send api from the ecs one. Also does not deal with the potential `in` copy issue.
> Update the view when sending an update. Disable loopback

- workers/unity/Packages/com.improbable.gdk.core/Worker/WorkerConnector.cs
Adding an `Application.isPlaying`check before calling `HandleWorkerConnectionEstablished` as this can result in spawning countless error messages, if the Editor play mode is exited at the wrong time. 
this occured in the `SimualtedPlayerWorkerConnector` which tried to access its transform component after already being destroyed. 
A second PR in the FPS starter project will be opened to add additional checks as that behaviour occured in multiple places. (though all related to the `HandleWorkerConnectionEstablished`)
> Add Application.isPlaying check to WorkerConnector

- CHANGELOG.md
- workers/unity/Packages/com.improbable.gdk.buildsystem/Configuration/BuildConfigEditor.cs
- workers/unity/Packages/com.improbable.gdk.buildsystem/WorkerBuilder.cs
- Added a check on whether Android SDK path is set or not. Note this is done only, if the build fails because Unity does give the user a prompt to set the path before deciding to continue or fail the build.
- When building for all workers, the platform of the last worker built would be the active one (usually Android in our sample prjects). Added an extra step to switch back to whichever build target was set before starting to build the workers.
- Moved a part of the `Build` out into its own method, so that it can be used for both: building from command line or via the menu items.
- Fixed the message where it reports completed & skipped worker types. The list was switched (i.e. we reported skipped worker types as those that succeeded and vice versa)
> Build system: Android SDK check & active target switch

- docs/projects/fps/tutorial.md
* Fix the order of steps for client launching so that a server-worker is up by the time the stand-alone client tries to launch.
* Improve prefab duplication steps
> Fix the order of steps for client launching and improve prefab duplication steps

- ci/generate-docs.sh
Adds a script to:
1. Generate API docs from a git tag/branch/commit-hash
2. Make a branch, commit, and push the docs changes.
3. If `hub` is on your path, it will automatically create the PR and open it in your browser.
Tested - gave me #825 🎉 
N/A - internal docs only
> Add generate api docs script

- workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityEcsViewManagerGenerator.tt
We used to use the entity manager. Not the best API as it creates an expensive barrier. This is a fair bit more efficient, although it could be broken by a job running at the same time as it.
> Removed use of the EntityManager from updating ecs components

- test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapKeyComponentDiffStorage.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapKeyUpdateSender.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapValueComponentDiffStorage.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapValueUpdateSender.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveOptionalComponentDiffStorage.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveOptionalUpdateSender.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveRepeatedComponentDiffStorage.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveRepeatedUpdateSender.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveSingularComponentDiffStorage.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveSingularUpdateSender.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/NestedComponentComponentDiffStorage.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/NestedComponentUpdateSender.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/alternateschemasyntax/ConnectionComponentDiffStorage.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/alternateschemasyntax/ConnectionUpdateSender.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponentComponentDiffStorage.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponentUpdateSender.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsComponentDiffStorage.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsUpdateSender.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithCommandsComponentDiffStorage.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithCommandsUpdateSender.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithEventsComponentDiffStorage.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithEventsUpdateSender.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponentComponentDiffStorage.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponentUpdateSender.cs
- workers/unity/Packages/com.improbable.gdk.core/Collections/MessageList.cs
- workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/ComponentDiffStorageGenerator.tt
Change lists are now created sorted rather than doing this lazily. Configuration should be added to specify what to do on a component basis.
This is not optimised an any way but it can be offloaded onto a deserialisation thread as is.
> Sort while deserialising

- CHANGELOG.md
- workers/unity/Packages/com.improbable.gdk.playerlifecycle/PlayerLifecycleHelper.cs
Removing the serialization helpers in the `PlayerLifecycleHelper` class - to be provided as sample code in the docs instead
playground + CI
to be doc'd in this PR: https://github.com/spatialos/gdk-for-unity/pull/820/files
yes, updated changelog
> Remove serialization helpers from code

- CHANGELOG.md
- workers/unity/Packages/com.improbable.gdk.tools/Common.cs
- workers/unity/Packages/com.improbable.gdk.tools/GenerateCode.cs
Refactored the Tooling package to no longer have a hardcoded dependency on `file:` paths in the manifest.
This allows support for published unity packages in the future.
New approach works with playground, test project, and fps
No - Internal tooling change
> Tooling PackageManager refactor

- CHANGELOG.md
- workers/unity/Packages/com.improbable.gdk.buildsystem/WorkerBuilder.cs
- workers/unity/Packages/com.improbable.gdk.core/Collections/Result.cs
- workers/unity/Packages/com.improbable.gdk.core/Collections/Result.cs.meta
- workers/unity/Packages/com.improbable.gdk.mobile/Editor/LaunchMenu.cs
- workers/unity/Packages/com.improbable.gdk.tools/DownloadCoreSdk.cs
- workers/unity/Packages/com.improbable.gdk.tools/GenerateCode.cs
- workers/unity/Packages/com.improbable.gdk.tools/RedirectedProcess.cs
* Refactor `RedirectedProcess` to support running async with a cancellation token.
* Also fixed a bug where if you invoked `RedirectedProcess.Command()` on a non-main thread Unity would throw an exception.
Ran things. It seemed to work just fine.
Needs release note.
> Redirected process changes required for deployment launcher fixes

- CHANGELOG.md
- test-project/Assets/Generated/Source/improbable/gdk/tests/alternateschemasyntax/ConnectionComponentDiffStorage.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponentComponentDiffStorage.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithEventsComponentDiffStorage.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponentComponentDiffStorage.cs
- test-project/Packages/manifest.json
- test-project/ProjectSettings/ProjectVersion.txt
- workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/ComponentDiffStorageGenerator.tt
@jessicafalk discovered a race where if an entity was removed from your view in the same frame as you received an event, the event would not be cleared from the diff. This PR fixes that bug.
Ran codegen, observed the changes - satisfied it would properly clear the events.
Changelog
@jessicafalk @samiwh
> Fix event race

- CHANGELOG.md
- workers/unity/Packages/com.improbable.gdk.core/Subscriptions/Callbacks.cs
Make callbacks resistant against exceptions in our users code.
Currently this uses Debug.LogException, however this should at some point move to a logging framework for Core.
As a drive-by, remove all closures from Callbacks functions.
Draft until 0.2.1 is released
Ran Playground (will run FPS)
Changelog
@jamiebrynes7
> Safe Callbacks

- CHANGELOG.md
- workers/unity/Packages/com.improbable.gdk.buildsystem/WorkerBuilder.cs
Before building workers, we check whether we can find a SpatialOS Build Configuration instance. If not we:
- Display a popup if we are in the Editor.
- Log an error to the terminal.
- Terminate the build.
This is _instead_ of the user getting a null ref exception thrown somewhere inside the build process.
Deleted the asset. Tried to build. Saw popup + error in the terminal.
Changelog.
> Add user friendly error when failing to find build config

- docs/pricing-and-support/pricing.md
- docs/pricing-and-support/support.md
- docs/toc.md
> Cherry pick #923 into docs-next

- .gitignore
- CHANGELOG.md
- workers/unity/Assets/.gitignore
- workers/unity/Assets/Playground/Scripts/UI/ConnectionScreenController.cs
- workers/unity/Packages/com.improbable.gdk.core/Worker/WorkerConnector.cs
- workers/unity/Packages/com.improbable.gdk.mobile/Worker/MobileWorkerConnector.cs
- workers/unity/Packages/com.improbable.gdk.tools/DevAuthTokenUtils.cs
Instead of having to enter the dev auth token into an inspector field, we should load an asset when needed.
Need to update the other projects as well.
tested locally and in cloud.
will be updated soonish
> Load dev token asset by default

- CHANGELOG.md
- workers/unity/Packages/com.improbable.gdk.core/Systems/WorkerSystem.cs
This PR fixes a bug where subscriptions wouldn't be fulfilled on the worker GameObject since it would never exist in the `EntityIdToEntity` map. 
Tested by Jose, who found the bug.
Yes
> Fix Worker Entity + GameObject Link

- workers/unity/Packages/com.improbable.gdk.core/Subscriptions/EntityGameObjectLinker.cs
Adding check for valid entity as it will otherwise try to remove the components from the gameobject that is linked to the worker entity as well.
ran it, no crashes anymore upon exiting the application
> Adding check for valid entity

- CHANGELOG.md
- workers/unity/Packages/com.improbable.gdk.core/Utility/TaskUtility.cs
- workers/unity/Packages/com.improbable.gdk.core/Utility/TaskUtility.cs.meta
- workers/unity/Packages/com.improbable.gdk.core/Worker/Worker.cs
- workers/unity/Packages/com.improbable.gdk.core/Worker/WorkerConnector.cs
fix for [UTY-1870](https://improbableio.atlassian.net/browse/UTY-1870)
Unity seems to dispose the World as well whenever you stop your editor application, so we need to check first before we dispose of the World to ensure we are not trying to dispose it multiple times.
Also did a quick rename of a parameter to ensure that code and XML documentation are consistent.
ran it in the editor, now it only throws the `Editor application stopped` error instead of a `World is already disposed' and a connection error.
> Fixed world being disposed multiple times

- CHANGELOG.md
- test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapKeyComponentDiffDeserializer.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapValueComponentDiffDeserializer.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveOptionalComponentDiffDeserializer.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveRepeatedComponentDiffDeserializer.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveSingularComponentDiffDeserializer.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/NestedComponentComponentDiffDeserializer.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/alternateschemasyntax/ConnectionComponentDiffDeserializer.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponentComponentDiffDeserializer.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsComponentDiffDeserializer.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithCommandsComponentDiffDeserializer.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithEventsComponentDiffDeserializer.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponentComponentDiffDeserializer.cs
- workers/unity/Packages/com.improbable.gdk.deploymentlauncher/Commands/Assembly.cs
- workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/ComponentDiffDeserializerGenerator.tt
Removed the workaround for a schema component update bug (WRK-1031).
consider reading 1st and 3rd commit (2nd commit is generated code)
includes drive-by deployment launcher fix for uploading assemblies
internal changelog entry
> Remove workaround for a schema component update bug (WRK-1031).

- CHANGELOG.md
- workers/unity/Assets/Config/GdkToolsConfiguration.json
- workers/unity/Assets/Plugins.meta
- workers/unity/Packages/com.improbable.gdk.core/Config/RuntimeConfig.cs
- workers/unity/Packages/com.improbable.gdk.core/Worker/WorkerConnector.cs
- workers/unity/Packages/com.improbable.gdk.mobile/Editor/LaunchMenu.cs
- workers/unity/Packages/com.improbable.gdk.mobile/Improbable.Gdk.Mobile.asmdef
- workers/unity/Packages/com.improbable.gdk.mobile/Worker/DefaultMobileWorkerConnector.cs
- workers/unity/Packages/com.improbable.gdk.tools/DevAuthTokenUtils.cs
- workers/unity/Packages/com.improbable.gdk.tools/GdkToolsConfiguration.cs
- workers/unity/Packages/com.improbable.gdk.tools/GdkToolsConfigurationWindow.cs
- workers/unity/Packages/com.improbable.gdk.tools/MenuPriorities.cs
- workers/unity/ProjectSettings/EditorBuildSettings.asset
- workers/unity/ProjectSettings/GraphicsSettings.asset
- workers/unity/ProjectSettings/ProjectSettings.asset
- move runtime ip to an editor pref
- move DAT to player pref
- [this ties a DAT to a company/project_name](https://docs.unity3d.com/ScriptReference/PlayerPrefs.html)
- only create DAT.txt if enabled in GdkToolsConfiguration
- pass in DAT as argument when starting android client for cloud
- if DAT argument passed in, player pref is set
- if no DAT argument exists / previously set as player pref - read from DAT.txt and save to player prefs
- local launch works fine
- android cloud launch via editor works fine
- no DAT.txt generated unless specifically requested
> Move runtime IP to EditorPref / DevAuthToken to PlayerPref

- workers/unity/Packages/com.improbable.gdk.core/Worker/WorkerConnector.cs
Fixing a small bug found during upgrade of FPS.
If Dispose was called through anything besides a Disconnect, it would not correctly remove the world from the PlayerLoop.
This small commit fixes this issue.
> Ensure Worker World is always removed from PlayerLoop

- workers/unity/Packages/com.improbable.gdk.core/Utility/PlayerLoopUtils.cs
No longer remove all non-ecs function calls from the PlayerLoop when a worker disconnects.
Oops
Tested locally and on the cloud, SimulatedPlayers can safely disconnect again.
> Fix PlayerLoop breaking on disconnected worker

- CHANGELOG.md
- cloud_launch.json
- default_launch.json
`small` -> `w2_r0500_e5` 
Will run the release QA pipeline.
Release note - internal.
> UTY-2058: Update launch config templates

- CHANGELOG.md
- workers/unity/Packages/com.improbable.gdk.buildsystem/Util/EditorPaths.cs
- workers/unity/Packages/com.improbable.gdk.buildsystem/WorkerBuilder.cs
Selecting `SpatialOS > Clean all workers` now only removes worker-related artifacts (configurations + assemblies). The `schema.descriptor` is preserved. 
Built + cleaned - checked state of the directory.
Added a changelog
> UTY-2061: Exclude schema directory when cleaning workers

- CHANGELOG.md
- test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapKey.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapKeyProviders.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapValue.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapValueProviders.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveOptional.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveOptionalProviders.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveRepeated.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveRepeatedProviders.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveSingular.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveSingularProviders.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/NestedComponent.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/NestedComponentProviders.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/alternateschemasyntax/Connection.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/alternateschemasyntax/ConnectionProviders.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponent.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponentProviders.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFields.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsProviders.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithCommands.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithCommandsProviders.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithEvents.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithEventsProviders.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponent.cs
- test-project/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponentProviders.cs
- workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityComponentDataGenerator.tt
- workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityReferenceTypeProviderGenerator.tt
Wasn't correctly wrapped in the `DISABLE_REACTIVE_COMPONENTS` define. The type would exist but never contain any updates.
Generated code - verified it was compiled out
Changelog - breaking change.
> Hotfix - Received Updates should be a reactive component

- workers/unity/Packages/com.improbable.gdk.core/Worker/WorkerConnector.cs
because we need to use it in the client-worker. see https://github.com/spatialos/gdk-for-unity-fps-starter-project/pull/200
> Make DeferredDisposeWorker protected

- CHANGELOG.md
- workers/unity/Packages/com.improbable.gdk.tools/Common.cs
When we encounter an invalid PATH element during the binary discovery process, we drop those elements instead of throwing an exception which would break the entire GDK.
The alternative proposed solution was to call `spatial`/`dotnet` and check the result, but apparently Mac is a little special and so that would not always work.
Will try to break my PATH and see what happens. 🤞 
Change log and will close known issue #959
> Fix PATH errors on Windows

- CHANGELOG.md
- workers/unity/Packages/com.improbable.gdk.core/Logging/ForwardingDispatcher.cs
Pretty quick fix - use Unity's `LogType` instead of the C#IO's `LogLevel`. Requested in #753 
(This was cherry-picked out of #844 where I driveby fixed in a few days ago).
Ran the game - logging still worked. 
Changelog + closes known issue.
> Use Unity logger types in ForwardingDispatcher

- CHANGELOG.md
- workers/unity/Packages/com.improbable.gdk.transformsynchronization/Systems/SetKinematicFromAuthoritySystem.cs
- Fixed a regression in the `SetKinematicFromAuthoritySystem` that failed to toggle a rigidbody's kinematic state on `TransformInternal` authority changes.
- playground doesn't break
- it matches the implementation pre-0.2.2
changelog included
> Fix SetKinematicFromAuthoritySystem regression

- CHANGELOG.md
- workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/src/CodeGenerator.cs
See title. There were a few un-escaped paths.
Changelog incoming
> Fix code generation path escaping

- docs/reference/concepts/deployments.md
Tidied up and updated deployment documentation. Removed CLI usage instructions and directed users to the deployment launcher feature module for cloud deployment instructions.
Improbadoc local serve.
> Update Deployments docs

- workers/unity/Packages/com.improbable.gdk.mobile/Editor/iOSLaunchUtils.cs
Discovered during release QA. The regexes were slightly off resulting in some devices being classified as Simulators. The names were being parsed a little oddly as well.
Tested on @paulbalaji's machine - worked as intended!
N/A - changes were inflight.
> Fix iOS tooling regex

- CHANGELOG.md
- workers/unity/Assets/Playground/Scripts/MonoBehaviours/CubeSpawnerInputBehaviour.cs
- Stopped throwing `Test Exception` in playground
- can't see the exception anymore
> Remove test exception from playground

- docs/fragments/machine-setup.md
This change adds system requirements and network requirements to the Unity GDK setup docs. It's based on feedback that [customers](https://forums.improbable.io/t/cant-upload-to-cloud-and-failed-to-unzip-the-client/5246/8) don't always see these specifications in the current setup flow.
Rendered and linted in `improbadoc`.
This is documentation dude.
I skipped a changelog entry as this is a small changes and has no applicability for existing users.
> add network and hardware specs

- CHANGELOG.md
- workers/unity/Packages/com.improbable.gdk.core/Subscriptions/EntityGameObjectLinker.cs
- workers/unity/Packages/com.improbable.gdk.core/Subscriptions/LinkedGameObjectMap.cs
- workers/unity/Packages/com.improbable.gdk.core/Subscriptions/LinkedGameObjectMap.cs.meta
- workers/unity/Packages/com.improbable.gdk.gameobjectcreation/GameObjectInitializationSystem.cs
- workers/unity/Packages/com.improbable.gdk.gameobjectcreation/LinkedGameObjectMapSubscriptionManager.cs
- workers/unity/Packages/com.improbable.gdk.gameobjectcreation/LinkedGameObjectMapSubscriptionManager.cs.meta
- workers/unity/Packages/com.improbable.gdk.gameobjectcreation/Tests.meta
- workers/unity/Packages/com.improbable.gdk.gameobjectcreation/Tests/Editmode.meta
- workers/unity/Packages/com.improbable.gdk.gameobjectcreation/Tests/Editmode/Improbable.Gdk.GameObjectCreation.EditmodeTests.asmdef
- workers/unity/Packages/com.improbable.gdk.gameobjectcreation/Tests/Editmode/Improbable.Gdk.GameObjectCreation.EditmodeTests.asmdef.meta
- workers/unity/Packages/com.improbable.gdk.gameobjectcreation/Tests/Editmode/LinkedGameObjectMapSubscriptionTests.cs
- workers/unity/Packages/com.improbable.gdk.gameobjectcreation/Tests/Editmode/LinkedGameObjectMapSubscriptionTests.cs.meta
- workers/unity/Packages/com.improbable.gdk.gameobjectcreation/Tests/Editmode/MockGameObjectCreator.cs
- workers/unity/Packages/com.improbable.gdk.gameobjectcreation/Tests/Editmode/MockGameObjectCreator.cs.meta
Added an API to expose the `EntityId -> [GameObject]` relationship. This is wrapped in an object to ensure that we expose a list which is readonly (we really don't want users to mutate the underlying data). 
Also added a subscription manager for this (only in the GameObjectCreation module as the linker actually lives in a system here!) and added tests for this. 
**Commits are ordered and logical!**
Added some tests for the subscription fulfillment.
> Add `LinkedGameObjectMap` API

- .buildkite/premerge.definition.yaml
- .buildkite/premerge.steps.yaml
- .buildkite/release-qa.steps.yaml
- update pipeline name to match others
- disable premerge for docs branches
- add ios emoji to buildkite step
- doesn't build anything for this commit https://github.com/spatialos/gdk-for-unity/commit/efa9903c8bcd3bce29ccdd3e27d2a001f6ed1f4a
- ios emoji shows up 🎉 
n/a
> Disable premerge for docs branches

- init.ps1
- init.sh
- stop linux schema compiler overriding mac one
- actually opens without errors on mac
- n/a
> Stop linux schema compiler overriding mac one

- CHANGELOG.md
- workers/unity/Packages/io.improbable.worker.sdk.mobile/BuildPostProcessXCode.cs
- workers/unity/Packages/io.improbable.worker.sdk.mobile/BuildPostProcessXCode.cs.meta
- workers/unity/Packages/io.improbable.worker.sdk.mobile/Improbable.Worker.Sdk.Mobile.asmdef
- workers/unity/Packages/io.improbable.worker.sdk.mobile/Improbable.Worker.Sdk.Mobile.asmdef.meta
Post process the xcode project library search paths to make sure simulator and arm libraries are separated.
> Fix xcode paths

- workers/unity/Packages/io.improbable.gdk.tools/GenerateCode.cs
Somehow `dotnet run -p <project>` breaks if the filepath contains a symlinked folder, and the has local dependencies.
This fix makes sure to resolve the symlink for the code generator to resolve this issue.
> Fix mac symlinks

- ci/tag-docs.sh
Actually exit if we're trying to tag prod when not on `docs-current`
n/a
> Exit docs release if not on docs-current

- CHANGELOG.md
- UPGRADE_GUIDE.md
- workers/unity/Packages/io.improbable.gdk.gameobjectcreation/GameObjectCreatorFromMetadata.cs
- workers/unity/Packages/io.improbable.gdk.gameobjectcreation/SpatialOSEntity.cs
Upstreamed from dog-fooding project. This helps cut down on boilerplate in `IEntityGameObjectCreator` implementations.
Also did a driveby refactor of `GameObjectCreatorFromMetadata`.
Playground tests.
Changelog + upgrade guide!
> Add `SpatialOSEntity.TryGetComponent`

- CHANGELOG.md
- workers/unity/Packages/io.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityTypeContent.tt
- workers/unity/Packages/io.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Tests/Model/DetailsStoreTests.cs
- workers/unity/Packages/io.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/src/CodeGenerator.cs
- workers/unity/Packages/io.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/src/CodeGeneratorOptions.cs
- workers/unity/Packages/io.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/src/Generation/Model/Details/DetailsStore.cs
- workers/unity/Packages/io.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/src/Generation/Model/Details/UnityTypeDetails.cs
- workers/unity/Packages/io.improbable.gdk.tools/GdkToolsConfiguration.cs
- workers/unity/Packages/io.improbable.gdk.tools/GenerateCode.cs
- Added options for serialization overrides for schema types only. 
- Added this to the `GdkToolsConfiguration.json`, not exposed in the UI.
- Overrides are specified by key-value pairs like so: `"TargetTypeFqn;SerializationOverrideStaticClassFqn"`
- These are parsed and pushed into the `UnityTypeDetails` and replaces the content of the Serialize/Deserialize functions for that type.
Added unit test. Will do an end-to-end test.
Changelog. No public docs.
> Lay groundwork for serialization overrides

- docs/modules/build-system/cli.md
Updating the build system CLI docs to reflect following changes:
- `buildTarget` --> `buildEnvironment` rename
- describe new `buildTargetFilter` argument
> Update build system cli docs

- ci/build-lint-preview.sh
minor whoopsy
need to exit 1 if we get linting errors
Correctly fails here: https://buildkite.com/improbable/gdk-for-unity-docs/builds/154
Works correctly after fixing md links: https://buildkite.com/improbable/gdk-for-unity-docs/builds/153
> Exit if we get linting errors

- CHANGELOG.md
- spatialos.json
- workers/unity/Packages/io.improbable.gdk.core/package.json
- workers/unity/Packages/io.improbable.gdk.mobile/package.json
- workers/unity/Packages/io.improbable.gdk.tools/core-sdk.version
- workers/unity/Packages/io.improbable.gdk.tools/core-sdk.version.meta
@zeroZshadow noticed we had a few remaining references. `grep`-ed the repo for other references and removed them.
> Remove leftover 13.7.1 references

- workers/unity/Packages/io.improbable.gdk.debug/MonoBehaviourInspector.cs
Fix MonoBehaviourInspector throwing if there are no require fields combined with a WorkerType attribute
> UTY-2181 Fix MonoBehaviourInspector throwing NRE

- workers/unity/Packages/io.improbable.gdk.testutils/Editor.meta
- workers/unity/Packages/io.improbable.gdk.testutils/Editor/Improbable.Gdk.TestUtils.Editor.asmdef
- workers/unity/Packages/io.improbable.gdk.testutils/Editor/Improbable.Gdk.TestUtils.Editor.asmdef.meta
- workers/unity/Packages/io.improbable.gdk.testutils/Editor/SpatialDeploymentManager.cs
- workers/unity/Packages/io.improbable.gdk.testutils/Editor/SpatialDeploymentManager.cs.meta
- workers/unity/Packages/io.improbable.gdk.testutils/Editor/Tests.meta
- workers/unity/Packages/io.improbable.gdk.testutils/Editor/Tests/Improbable.Gdk.TestUtils.Editor.Tests.asmdef
- workers/unity/Packages/io.improbable.gdk.testutils/Editor/Tests/Improbable.Gdk.TestUtils.Editor.Tests.asmdef.meta
- workers/unity/Packages/io.improbable.gdk.testutils/Editor/Tests/SpatialDeploymentManagerTests.cs
- workers/unity/Packages/io.improbable.gdk.testutils/Editor/Tests/SpatialDeploymentManagerTests.cs.meta
Added a `SpatialDeploymentManager` which allows you to create and manage the lifecycle of a deployment in the Editor. This is aimed to be used for automated connection testing. Also added some tests for the `SpatialDeploymentManager` to verify its behaviour 🎉 
Yes there are tests.
> Add `SpatialDeploymentManager` to test utils package

- docs/reference/concepts/snapshots.md
- docs/reference/overview.md
- docs/reference/workflows/overview.md
Refreshed the snapshots docs page:
- Removed reference to Playground.
- Tidied up the prose and link to our own glossary.
- Added a code sample.
- Pointed users to tooling for launching deployments before pointing them to the CLI.
> Refresh snapshots docs page

- CHANGELOG.md
- workers/unity/Packages/io.improbable.gdk.core/Tests/Editmode/Connection.meta
- workers/unity/Packages/io.improbable.gdk.core/Tests/Editmode/Connection/ReceptionistFlowTests.cs
- workers/unity/Packages/io.improbable.gdk.core/Tests/Editmode/Connection/ReceptionistFlowTests.cs.meta
- workers/unity/Packages/io.improbable.gdk.core/Tests/Editmode/Improbable.Gdk.Core.EditmodeTests.asmdef
- workers/unity/Packages/io.improbable.gdk.testutils/Editor/SpatialDeploymentManager.cs
- `SpatialDeploymentManager.Start()` builds worker configs as well (so that you may _actually_ connect a worker)
- Added tests for the `ReceptionistFlow`
Yes this is test.
> Add receptionist flow testing

- CHANGELOG.md
- workers/unity/Packages/io.improbable.gdk.core/Tests/Editmode/Connection/CommandLineConnectionFlowInitializerTests.cs
- workers/unity/Packages/io.improbable.gdk.core/Tests/Editmode/Connection/CommandLineConnectionFlowInitializerTests.cs.meta
- workers/unity/Packages/io.improbable.gdk.core/Worker/ConnectionHandlers/ConnectionFlowInitializers.cs
- Added unit tests for `CommandLineConnectionFlowInitializer`.
- While writing the tests, I noticed some semantic errors, which I fixed in `CommandLineConnectionFlowInitializer`.
Also yes.
> Add `CommandLineConnectionFlowInitializer` Tests

- CHANGELOG.md
- workers/unity/Packages/io.improbable.gdk.tools/RedirectedProcess.cs
Fixed a bug where if you didn't provide a cancellation token, the continuation could deadlock if you were `await`-ing on the same thread. Discovered this while playing around with the Platform SDK. 
My tests were deadlocking before this, they didn't after.
> Fix potential deadlock when using `RedirectedProcess.RunAsync()`

- CHANGELOG.md
- workers/unity/Packages/io.improbable.gdk.core/Config/RuntimeConfig.cs
- workers/unity/Packages/io.improbable.gdk.core/Worker/ConnectionHandlers/ConnectionFlows.cs
In preparation for the testing of this flow, fixing some bugs/missing features I found ahead of time: 
- `GetDevelopmentLoginTokens` now correctly uses the host/port combo 
- Allow you to set `UseInsecureConnection` for all parts of the flow.
- Allow you to connect to a non-default locator port.
- Renamed `AnonymousAuthenticationPort` -> `LocatorPort` for consistency. 
- Updated doc strings.
Coming soon ™️ 
> Refactor & Fixes to `AlphaLocatorFlow`

- CHANGELOG.md
- workers/unity/Packages/io.improbable.gdk.core/Tests/Editmode/Connection/AlphaLocatorFlowTests.cs
- workers/unity/Packages/io.improbable.gdk.core/Tests/Editmode/Connection/AlphaLocatorFlowTests.cs.meta
- workers/unity/Packages/io.improbable.gdk.core/Worker/ConnectionHandlers/ConnectionFlows.cs
~*Currently based on top of #1104, so lots of erroneous commits. Will rebase this once #1104 is merged.*~
- Fixed a potential deadlocking issue in `AlphaLocatorFlow.CreateAsync()`. 
- Added tests for the various stages of the dev auth flow and connecting.
Yes we have tests.
> `AlphaLocatorFlow` tests

- CHANGELOG.md
- test-project/Assets/Generated/Source/improbable/dependentschema/DependentComponentProviders.cs
- test-project/Assets/Generated/Source/improbable/dependentschema/DependentDataComponentProviders.cs
- test-project/Assets/Generated/Source/improbable/tests/DependencyTestChildProviders.cs
- test-project/Assets/Generated/Source/improbable/tests/DependencyTestGrandchildProviders.cs
- test-project/Assets/Generated/Source/improbable/tests/DependencyTestProviders.cs
- test-project/Assets/Generated/Source/improbable/testschema/ExhaustiveEntityProviders.cs
- test-project/Assets/Generated/Source/improbable/testschema/ExhaustiveMapKeyProviders.cs
- test-project/Assets/Generated/Source/improbable/testschema/ExhaustiveMapValueProviders.cs
- test-project/Assets/Generated/Source/improbable/testschema/ExhaustiveOptionalProviders.cs
- test-project/Assets/Generated/Source/improbable/testschema/ExhaustiveRepeatedProviders.cs
- test-project/Assets/Generated/Source/improbable/testschema/ExhaustiveSingularProviders.cs
- workers/unity/Packages/io.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityReferenceTypeProviderContent.tt
- workers/unity/Packages/io.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityReferenceTypeProviderGenerator.tt
We forgot to add the providers for reactive components to the `#ifdef`
This fixes this, and contains a driveby fix on a global namespace.
Tested in Playground and test project
> opt-in reactive providers

- CHANGELOG.md
- workers/unity/Packages/io.improbable.gdk.core/Systems/ComponentSendSystem.cs
Don't wait for all gathering jobs to complete, but only the jobs we require for the next bit of work.
Shuffled the profile sampling around a bit to give a better indication of wait times.
> SendComponentSystem jobs improvement

- CHANGELOG.md
- workers/unity/Packages/io.improbable.gdk.core/Utility/CommandLineUtility.cs
- workers/unity/Packages/io.improbable.gdk.core/Worker/WorkerConnector.cs
Adds a feature which sends a log to the SpatialOS console noting which port this worker has open for connecting a remote profiler/etc to. 
- Only runs if we are in a Development build (port isn't available for release builds).
- Doesn't run for mobile clients.
- Doesn't run in the editor.
Tested against Linux, MacOS, and Windows.
**Remaining work**
> Print `PlayerConnection` port in SpatialOS console

- CHANGELOG.md
- init.ps1
- init.sh
- test-project/Assets/.schema/empty.schema
- test-project/Assets/.schema/test.schema
- test-project/Assets/Generated/Source/improbable/testschema/TypeA.cs
- test-project/Assets/Generated/Source/improbable/testschema/TypeB.cs
- test-project/Assets/Generated/Source/improbable/testschema/TypeC.cs
- workers/unity/Packages/io.improbable.gdk.tools/.CodeGenerator/CodeGeneration/Tests/Model/SchemaBundleV1/Resources/exhaustive_bundle.json
- workers/unity/Packages/io.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Tests/Model/DetailsStoreTests.cs
- workers/unity/Packages/io.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/src/Generation/Model/Details/DetailsStore.cs
- workers/unity/Packages/io.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/src/Generation/Model/Details/UnityFieldDetails.cs
- workers/unity/Packages/io.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/src/Generation/Model/Details/UnityTypeDetails.cs
Historically, we have not supported recursive options due to reference-semantic options imposing serious performance penalties. However, this is supported at the schema level. Previously, this would simply cause a compile error, but recently it started causing a Mono hard crash.
This PR fixes this bug by explicitly skipping recursive optional fields in schema types. Additionally, this PR contains updates to the `exhaustive_bundle.json` used for testing and some extra tests for the recursive schema case.
The first 5 commits are mostly housekeeping, the commits after those will be the more interesting ones.
- There are some nice little test cases in here.
> UTY-2091: Fix crash on recursive options

- docs/reference/concepts/code-generation.md
Add a warning that we will skip these fields. Also noted that we do actually support `double`s 😉
> Add warning about recursive schema options

- CHANGELOG.md
- workers/unity/Packages/io.improbable.gdk.tools/MenuPriorities.cs
- workers/unity/Packages/io.improbable.gdk.tools/PortForwardingWindow.cs
- workers/unity/Packages/io.improbable.gdk.tools/PortForwardingWindow.cs.meta
Adds a UI window to complement the feature implemented in #1128. This allows users to port forward without touching the CLI.
- Validation against user input
- Little responsive UI telling you what state the connection is in.
- Assembly reloading locked while the window is up.
~**Question about the lifetime of the port forwarding: While the window is open? While Unity is open?**~
~If the latter, we will need to serialize the process `Task` _somehow_.~
Decided to tie the lifetime to the window lifetime.
Screenshots:
_entering data_
_connected successfully_
_failed attempt_
Tested the various states for connecting and the validation logic.
> Port Forwarding UI

- docs/modules/debug/require-inspector.md
- docs/projects/fps/tutorial.md
- docs/toc.md
- docs/workflows/monobehaviour/interaction/commands/component-commands.md
- docs/workflows/monobehaviour/interaction/commands/world-commands.md
- docs/workflows/monobehaviour/interaction/reader-writers/component-data-updates.md
- docs/workflows/monobehaviour/interaction/reader-writers/events.md
- docs/workflows/monobehaviour/interaction/reader-writers/lifecycle.md
- docs/workflows/monobehaviour/interaction/reader-writers/overview.md
- docs/workflows/overview.md
Link to WorldCommands.EntityQuery.Request request at the World Comands page. Also removed a link from "Reader and Writers" at the TOC to standardize the behaviour with other items.
> Link to WorldCommands.EntityQuery.Request request

- CHANGELOG.md
- workers/unity/Packages/io.improbable.gdk.buildsystem/WorkerBuilder.cs
Mac builds now include a json file telling the launcher where to find the executable to launch.
A quick fix for our release.
Build a Mac client on Windows, uploaded through the Deployment Launcher, and launched client successfully on a Mac.
> Fix mac launcher

- CHANGELOG.md
Rebase gone wrong meant the changelog for #1135 was put into the wrong place. This PR corrects that.
> Fix changelog for #1135

- workers/unity/Packages/io.improbable.gdk.buildsystem/.codegen/Source/WorkerGenerationJob.cs
- workers/unity/Packages/io.improbable.gdk.core/.codegen/Source/SingleGenerationJob.cs
- workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGeneratorOptions.cs
- workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/EntryPoint.cs
- workers/unity/Packages/io.improbable.gdk.tools/.CodeGenerator/CodeGeneration/Jobs/CodegenJob.cs
- workers/unity/Packages/io.improbable.gdk.tools/.CodeGenerator/CodeGeneration/Tests/Jobs/CodegenJobTests.cs
- workers/unity/Packages/io.improbable.gdk.tools/GenerateCode.cs
This PR removes the hard dependency between the `EntryPoint` and the code generation job by finding all types that are non-abstract, inherit from `CodegenJob`, and don't have the `IgnoreCodegenJob` attribute on them (used for tests). 
- Also makes the `CodeGenerationOptions` accessible as a singleton instance.
- Also includes a few tweaks/fixes in how we generate the `csproj`.  
Ran codegen locally, everything worked as expected.
N/A
> Find codegen jobs via reflection

- .buildkite/hooks/post-checkout
- .buildkite/hooks/pre-command
- .buildkite/premerge.steps.yaml
- ci/test.sh
This PR introduces a Buildkite plugin which will report test failures as annotations on a build:
This allows you to understand which tests are broken without diving into the logs. This feature is using the new `dag` feature from Buildkite which allows us to declare dependencies between jobs. The reporting step will only run after the tests has completed, but doesn't care about any of the other steps.
> Add test failure reporting in Buildkite

- CHANGELOG.md
- workers/unity/Packages/io.improbable.gdk.mobile/Editor/MobileLaunchConfig.cs
- workers/unity/Packages/io.improbable.gdk.mobile/Editor/MobileLauncherWindow.cs
Changed the mobile launcher config to be a serialisable struct to prevent it from resetting the `ShouldConnectLocally` variable whenever play mode gets entered or assemblies get reloaded
tested it manually by entering/exiting play mode and regenerating code
no documentation necessary
> Prevent mobile launcher from resetting

- ci/publish_packages.sh
Update package publishing script to prepare it for running it in CI.
This will:
- Grab the Worker SDK/`spot`/schema std lib
- Pack each package
- Push it to cloudsmith, overwriting any package that exists with that version (this allows us to overwrite the packages in the case where we detect a defect later in QA). 
There will be work that needs to be done in https://github.com/spatialos/gdk-for-unity-shared-ci to setup and run this script.
> update publish packages script

- CHANGELOG.md
- workers/unity/Packages/io.improbable.gdk.debug/NetStatsViewer/NetStatsTab.cs
Quick fix
When you have more components or commands to fit in the un-scaled scroll view, they would never update their data.
> Fix ScrollView display for all tabs

- ci/publish_packages.sh
Cloudsmith tool breaks on an empty extra argument when not running in dry-run mode.
This fixes this issue.
> Fix publish packages

- CHANGELOG.md
- workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/Jobs/CodegenJob.cs
Bug fix for auto-crlf issues with T4 template files.
> Codegen line endings

- CHANGELOG.md
- workers/unity/Packages/io.improbable.gdk.core/Worker/WorkerConnector.cs
Worker names for local development are no longer appended with massive GUID's, but instead have a smaller string based on the hash for the GUID.
This technically increases the chance of a clash, but considering we make so few local workers (2) it really doesn't matter.
This looks significantly better in the Profiler/Net Analyzer/Entity Debugger
> Shrink local worker names for local development

- CHANGELOG.md
- workers/unity/Packages/io.improbable.gdk.core/Subscriptions/Systems/CommandCallbackSystem.cs
Command response callbacks were registering a key with the system, but these were never cleared.
The key itself isn't actually used, since response callbacks will always clean up after sending.
This PR removes the key registration for response callbacks.
> Fix command response key leak

- docs/projects/fps/tutorial.md
- docs/workflows/monobehaviour/interaction/commands/component-commands.md
- turn off colliders in HealthPickupServerBehaviour (UTY-1977)
- fix missing schema import for `Empty` (UTY-2099)
- not regaining health anymore when pickup is disabled
- codegen broke without import, works fine now
- yes this is docs
> Quick code snippets fixes

- workers/unity/Packages/io.improbable.gdk.tools/GenerateCode.cs
- workers/unity/Packages/io.improbable.worker.sdk.mobile/Plugins/Improbable/Core/Android/arm64/libimprobable_worker.so.meta
- workers/unity/Packages/io.improbable.worker.sdk.mobile/Plugins/Improbable/Core/Android/armv7/libimprobable_worker.so.meta
- workers/unity/Packages/io.improbable.worker.sdk.mobile/Plugins/Improbable/Core/Android/x86/libimprobable_worker.so.meta
- workers/unity/Packages/io.improbable.worker.sdk.mobile/Plugins/Improbable/Core/iOS/arm/libimprobable_worker_static.a.meta
- workers/unity/Packages/io.improbable.worker.sdk.mobile/Plugins/Improbable/Core/iOS/x86_64/libimprobable_worker_static.a.meta
Mobile SDK Plugins had wrong import settings, which allowed them to clash in the editor.
This fixes the settings, and re-exports them in the new 2019.2 format.
Additionally fixes the codegenerator path to use the right casing for case-sensitive platforms.
> Mobile SDK import settings fix + CodeGen casing

- CHANGELOG.md
- test-project/Assets/Generated/Source/improbable/dependentschema/DependentComponentComponentDiffDeserializer.cs
- test-project/Assets/Generated/Source/improbable/dependentschema/DependentDataComponentComponentDiffDeserializer.cs
- test-project/Assets/Generated/Source/improbable/tests/DependencyTestChildComponentDiffDeserializer.cs
- test-project/Assets/Generated/Source/improbable/tests/DependencyTestComponentDiffDeserializer.cs
- test-project/Assets/Generated/Source/improbable/tests/DependencyTestGrandchildComponentDiffDeserializer.cs
- test-project/Assets/Generated/Source/improbable/testschema/ExhaustiveEntityComponentDiffDeserializer.cs
- test-project/Assets/Generated/Source/improbable/testschema/ExhaustiveMapKeyComponentDiffDeserializer.cs
- test-project/Assets/Generated/Source/improbable/testschema/ExhaustiveMapValueComponentDiffDeserializer.cs
- test-project/Assets/Generated/Source/improbable/testschema/ExhaustiveOptionalComponentDiffDeserializer.cs
- test-project/Assets/Generated/Source/improbable/testschema/ExhaustiveRepeatedComponentDiffDeserializer.cs
- test-project/Assets/Generated/Source/improbable/testschema/ExhaustiveSingularComponentDiffDeserializer.cs
- workers/unity/Packages/io.improbable.gdk.core/.codegen/Templates/ComponentDiffDeserializerGenerator.tt
Received component ops that don't contain any field updates, no longer trigger the OnUpdate callback.
> Events no longer trigger component updates

- CHANGELOG.md
- workers/unity/Assets/Playground/Scripts/Worker/ClientWorkerConnector.cs
- workers/unity/Assets/Playground/Scripts/Worker/MobileClientWorkerConnector.cs
- workers/unity/Packages/io.improbable.gdk.core/Worker/WorkerConnector.cs
Changed the default network type to ModularUDP (KCP) with Compression enabled.
Ran this in the Playground which shows the compression working through its worker metrics.
> Change default network type to ModularUDP with Compression

- CHANGELOG.md
- workers/unity/Packages/io.improbable.gdk.core/Systems/WorkerSystem.cs
- Expose IsConnected in WorkerSystem
- can access IsConnected field from both ECS and MonoBehaviours
- changelog on the way
> Expose `IsConnected` in WorkerSystem

- CHANGELOG.md
- workers/unity/Packages/io.improbable.gdk.deploymentlauncher/DeploymentLauncherWindow.cs
- stop saving to disk on every change
- only write unsaved changes if it's been more than 1 second since the last change
- also write to disk if the window is being closed
- feels a lot nicer
- profile before/after
probably worth adding a note in the deployment launcher docs about the save interval
> Deployment Launcher editor performance improvement

- CHANGELOG.md
- workers/unity/Packages/io.improbable.gdk.core/Config/RuntimeConfig.cs
As part of protecting the platform from DDoS attacks, we will be moving locator (xavier) behind a Google Global Load Balancer. These GLBs only support serving TLS traffic on port 443. Locator already supports serving gRPC traffic on port 443, so we can make this patch immediately, and it will be a seamless transition when the DNS for locator starts pointing to the GLB (which exposes port 443) instead of our current load balancer (which exposes port 443 and 444).
I have manually confirmed that Xavier is serving on 443 and 444 just like all other base servers. I have also confirmed that no additional steps are required to serve gRPC TLS on HTTP TLS ports for our base servers.
I have also run the QA pipeline on this branch and successfully connected to the resulting deployment: …
> CORE-1340 Change locator port 444 -> 443

- CHANGELOG.md
- workers/unity/Packages/io.improbable.gdk.core/.codegen/Templates/ComponentDiffDeserializerGenerator.tt
- UTY-2382
- Check cleared field count as well when applying update to diff
- Fixes bug introduced in #1211 
- removed 1 map element every second on server, received updated on client
- logged map count on server/client
- observed client never made it to 0 before bugfix
- correct behaviour observed after bugfix
> Cleared field bugfix of #1211

- docs/modules/build-system/build-config.md
- docs/modules/build-system/build-hooks.md
- docs/modules/build-system/cli.md
- docs/modules/build-system/editor-menu.md
- docs/toc.md
Added  page with an example using the new `WorkerBuilder.CurrentContext`.
Small linting driveby
> [DOCS] Build system hooks

- CHANGELOG.md
- workers/unity/Packages/io.improbable.gdk.querybasedinteresthelper/InterestQuery.cs
> Enable QBI frequency

- CHANGELOG.md
- workers/unity/Packages/io.improbable.gdk.core/Worker/WorkerConnector.cs
Smallest bugfix ever.
Unity provides the log location, so no need to guess.
> UTY-2381 Fix log path for port forwarding

- CHANGELOG.md
- workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/CodeWriter/Interfaces/IAnnotatable.cs
- workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/CodeWriter/Scopes/EnumBlock.cs
- workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/CodeWriter/Scopes/MethodBlock.cs
- workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/CodeWriter/Scopes/NamespaceBlock.cs
- workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/CodeWriter/Scopes/TypeBlock.cs
- IAnnotatable
- NamespaceBlock
- TypeBlock (structs/classes)
- EnumBlock
- MethodBlock
> [UTY-2390] CodeWriter v2: namespace, structs, classes, enums, methods, annotations (2/3)

- workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/CodeWriter/Scope.cs
- workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/CodeWriter/Scopes/Abstract/ScopeBody.cs
- workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/CodeWriter/Scopes/Abstract/ScopeBodyList.cs
- workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/CodeWriter/Scopes/CustomScopeBlock.cs
- workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/CodeWriter/Scopes/EnumBlock.cs
- workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/CodeWriter/Scopes/IfElseBlock.cs
- workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/CodeWriter/Scopes/LoopBlock.cs
- workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/CodeWriter/Scopes/NamespaceBlock.cs
- workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/CodeWriter/Scopes/TryCatchBlock.cs
- workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/CodeWriter/Scopes/TypeBlock.cs
allow you to pass `Func<IEnumerable<string>>` to more blocks:
- ifelse
- loop
- trycatch
- custom
- enum
- very useful when porting across gameobject creation module
- n/a
> Mimic CodeWriter methods API with enums/ifelse/trycatch/custom blocks

- CHANGELOG.md
- UPGRADE_GUIDE.md
- test-project/Assets/Generated/Improbable.Gdk.Generated.asmdef
- test-project/Assets/Generated/Source/improbable/dependentschema/DependentComponent.cs
- test-project/Assets/Generated/Source/improbable/dependentschema/DependentDataComponent.cs
- test-project/Assets/Generated/Source/improbable/tests/DependencyTest.cs
- test-project/Assets/Generated/Source/improbable/tests/DependencyTestChild.cs
- test-project/Assets/Generated/Source/improbable/tests/DependencyTestGrandchild.cs
- test-project/Assets/Generated/Source/improbable/testschema/ExhaustiveEntity.cs
- test-project/Assets/Generated/Source/improbable/testschema/ExhaustiveMapKey.cs
- test-project/Assets/Generated/Source/improbable/testschema/ExhaustiveMapValue.cs
- test-project/Assets/Generated/Source/improbable/testschema/ExhaustiveOptional.cs
- test-project/Assets/Generated/Source/improbable/testschema/ExhaustiveRepeated.cs
- test-project/Assets/Generated/Source/improbable/testschema/ExhaustiveSingular.cs
- workers/unity/Assets/Generated/Improbable.Gdk.Generated.asmdef
- workers/unity/Packages/io.improbable.gdk.core/.codegen/Source/Generators/Core/UnityComponentDataGenerator.cs
Simplify dirty bits by used a fixed array of uint's, instead of multiple code generated byte variables.
This change removes the need for switch based logic, and improves alignment of data in SpatialOS components.
> Simplified dirtybits

- CHANGELOG.md
- workers/unity/Packages/io.improbable.gdk.buildsystem/Configuration/BuildContext.cs
Tiny bug fix to the build system. Previously we would call out missing targets, but then try to build them anyway 😬
> Actually skip missing, non-required build targets.

- CHANGELOG.md
- init.ps1
- init.sh
Add support for downloading the packages through the cn-production environment in `init.sh` and `init.ps1` through the `--china` and `-china` flag respectively.
This is only needed for the maintainers of the GDK for Unity in China.
> Update init scripts for cn-production

- CHANGELOG.md
- UPGRADE_GUIDE.md
- workers/unity/Packages/io.improbable.worker.sdk.mobile/CopyLibcpp.cs
- workers/unity/Packages/io.improbable.worker.sdk.mobile/CopyLibcpp.cs.meta
The Worker SDK no longer links this library. Gradle doesn't link it properly. So we manually copy it across from the NDK. 
This is a breaking change since the NDK is required:
> Copy `libc++_shared.so` for Android builds

- CHANGELOG.md
- workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/Utils/SystemTools.cs
We no longer print schema compiler errors to stdout/stderr. Instead they are redirected to the logger.
The logger name is derived from the executable that is ran.
Fixes the known issue https://github.com/spatialos/gdk-for-unity/issues/1259
Made some bad schema. Tried to generate code. The errors appear in both the editor and the log file.
> Redirect schema compiler output to the codegen log

- .buildkite/premerge.steps.yaml
- ci/build-deployment-launcher.sh
We realised that we _weren't_ doing this and it was only getting run on our local machines & at release time. This PR adds an extra build step to build the `DeploymentLauncher.csproj` to catch any regressions.
Yes I am tests.
N/A
> Build deployment launcher in CI

- CHANGELOG.md
- packer.config.json
- test-project/Packages/io.improbable.gdk.dependencytest/package.json
- test-project/Packages/io.improbable.gdk.dependencytestchild/package.json
- test-project/Packages/io.improbable.gdk.dependencytestgrandchild/package.json
- test-project/Packages/io.improbable.worker.sdk.testschema/package.json
- workers/unity/Packages/io.improbable.gdk.buildsystem/package.json
- workers/unity/Packages/io.improbable.gdk.core/package.json
- workers/unity/Packages/io.improbable.gdk.debug/package.json
- workers/unity/Packages/io.improbable.gdk.deploymentlauncher/package.json
- workers/unity/Packages/io.improbable.gdk.gameobjectcreation/package.json
- workers/unity/Packages/io.improbable.gdk.mobile/package.json
- workers/unity/Packages/io.improbable.gdk.playerlifecycle/package.json
- workers/unity/Packages/io.improbable.gdk.querybasedinteresthelper/package.json
- workers/unity/Packages/io.improbable.gdk.testutils/package.json
- workers/unity/Packages/io.improbable.gdk.tools/package.json
- workers/unity/Packages/io.improbable.gdk.transformsynchronization/package.json
- workers/unity/Packages/io.improbable.gdk.transformsynchronization2d/package.json
- workers/unity/Packages/io.improbable.worker.sdk.mobile/package.json
- workers/unity/Packages/io.improbable.worker.sdk/package.json
Reverts spatialos/gdk-for-unity#1264, as we found a bug generating code when running QA on FPS
> Revert "Release 0.3.3 - Pre-Validation"

- workers/unity/Packages/io.improbable.gdk.tools/GenerateCode.cs
Downloaded package files are all read-only, and copying the template files kept this attribute.
This made it impossible to alter the csproj for the generators.
All copied files are now read-write.
> Fix CopyTemplate for downloaded package.

- test-project/Packages/io.improbable.gdk.dependencytest/.codegen/Source/Generators/TestProject/ModularCodegenTestGenerator.cs
- test-project/Packages/io.improbable.gdk.dependencytest/.codegen/Source/TestCodegenJob.cs
- workers/unity/Packages/io.improbable.gdk.buildsystem/.codegen/Source/Generators/BuildSystem/UnityWorkerMenuGenerator.cs
- workers/unity/Packages/io.improbable.gdk.buildsystem/.codegen/Source/WorkerGenerationJob.cs
- workers/unity/Packages/io.improbable.gdk.core/.codegen/Source/CoreCodegenJob.cs
- workers/unity/Packages/io.improbable.gdk.core/.codegen/Source/Generators/Core/CommandDiffDeserializerGenerator.cs
- workers/unity/Packages/io.improbable.gdk.core/.codegen/Source/Generators/Core/CommandDiffStorageGenerator.cs
- workers/unity/Packages/io.improbable.gdk.core/.codegen/Source/Generators/Core/CommandMetaDataStorageGenerator.cs
- workers/unity/Packages/io.improbable.gdk.core/.codegen/Source/Generators/Core/ComponentDiffDeserializerGenerator.cs
- workers/unity/Packages/io.improbable.gdk.core/.codegen/Source/Generators/Core/ComponentDiffStorageGenerator.cs
- workers/unity/Packages/io.improbable.gdk.core/.codegen/Source/Generators/Core/MetaclassGenerator.cs
- workers/unity/Packages/io.improbable.gdk.core/.codegen/Source/Generators/Core/UnityCommandPayloadGenerator.cs
- workers/unity/Packages/io.improbable.gdk.core/.codegen/Source/Generators/Core/UnityComponentDataGenerator.cs
- workers/unity/Packages/io.improbable.gdk.core/.codegen/Source/Generators/Core/UnityComponentSenderGenerator.cs
- workers/unity/Packages/io.improbable.gdk.core/.codegen/Source/Generators/Core/UnityEcsViewManagerGenerator.cs
- workers/unity/Packages/io.improbable.gdk.core/.codegen/Source/Generators/Core/UnityEnumContent.cs
- workers/unity/Packages/io.improbable.gdk.core/.codegen/Source/Generators/Core/UnityEnumGenerator.cs
- workers/unity/Packages/io.improbable.gdk.core/.codegen/Source/Generators/Core/UnityEventGenerator.cs
- workers/unity/Packages/io.improbable.gdk.core/.codegen/Source/Generators/Core/UnityReferenceTypeProviderGenerator.cs
- workers/unity/Packages/io.improbable.gdk.core/.codegen/Source/Generators/Core/UnityTypeGenerator.cs
- workers/unity/Packages/io.improbable.gdk.core/.codegen/Source/Generators/Core/ViewStorageGenerator.cs
- workers/unity/Packages/io.improbable.gdk.gameobjectcreation/.codegen/Source/GameObjectCodegenJob.cs
- workers/unity/Packages/io.improbable.gdk.gameobjectcreation/.codegen/Source/Generators/GameObjectCreation/UnityCommandSenderReceiverGenerator.cs
- workers/unity/Packages/io.improbable.gdk.gameobjectcreation/.codegen/Source/Generators/GameObjectCreation/UnityComponentReaderWriterGenerator.cs
- all top-level generators now require an argument to `Generate` of type `GeneratorInputDetails`
- tidied up methods within generators
- no change in generated code
- saving changelog for future codegen details/model PR
> [2/5] Prepare generators for new CodegenJob 

- CHANGELOG.md
- workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/CodeWriter/CodeWriter.cs
- workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/Jobs/CodegenJob.cs
- workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/Jobs/JobRunner.cs
- workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/Jobs/JobTarget.cs
- added CodeWriter constructor with just raw text
- to be used by both test project + build system module generators
- `JobTarget` class to replace the `GenerationTarget` system
- codegenjobs
- add `JobTarget` system side-by-side with current system
- no change in generated code
> [3/5] New CodegenJob model

- test-project/Packages/io.improbable.gdk.dependencytest/.codegen/Source/TestCodegenJob.cs
- workers/unity/Packages/io.improbable.gdk.buildsystem/.codegen/Source/WorkerGenerationJob.cs
- workers/unity/Packages/io.improbable.gdk.core/.codegen/Source/CoreCodegenJob.cs
- workers/unity/Packages/io.improbable.gdk.gameobjectcreation/.codegen/Source/GameObjectCodegenJob.cs
- workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/Tests/Jobs/CodegenJobTests.cs
- Port modules to new CodegenJob model
- no change in generated code
- changelog in final PR
> [4/5] Port modules to new CodegenJob model

- CHANGELOG.md
- workers/unity/Assets/Config/GdkToolsConfiguration.json
- workers/unity/Packages/io.improbable.gdk.deploymentlauncher/.DeploymentLauncher/Commands/Create.cs
- workers/unity/Packages/io.improbable.gdk.deploymentlauncher/.DeploymentLauncher/Options.cs
- workers/unity/Packages/io.improbable.gdk.deploymentlauncher/DeploymentConfigurations.cs
- workers/unity/Packages/io.improbable.gdk.tools/GdkToolsConfiguration.cs
- workers/unity/Packages/io.improbable.gdk.tools/GdkToolsConfigurationWindow.cs
- workers/unity/Packages/io.improbable.gdk.tools/LocalLaunch.cs
Added an optional override for the runtime version in the GDK Tools Configuration JSON & window. This is passed through to both `spatial local launch` and the deployment launcher. 
Also a small driveby in the `GdkToolsConfiguration` to reorganise some fields and ensure that defaults are properly set.
Commits are ordered for your reviewing pleasure 
- Ran a local deployment & cloud deployment with an override set.
- Ran a local deployment & cloud deployment w/o an override set.
> Add runtime version override

- docs/projects/blank/tutorial/1/project-walkthrough.md
- docs/projects/fps/get-started/set-up.md
The packer generated zips aren't being done correctly. We've decided to remove packer and swap to the source generated ones since we no longer sideload.
> Change zip download references to auto generated zips

- CHANGELOG.md
- workers/unity/Packages/io.improbable.gdk.buildsystem/.codegen/Source/Generators/BuildSystem/BuildSystemAssemblyGenerator.cs
- workers/unity/Packages/io.improbable.gdk.mobile/Editor/AndroidUtils.cs
Fix bug where mobile launcher wouldn't find Android devices with hyphens in their product name #1288 
+ drive-by update to build system asmdef generator
- regex101
> Fix bug where mobile launcher wouldn't find Android devices with hyphens in their product name

- CHANGELOG.md
- test-project/Assets/.schema/commands.schema
- test-project/Assets/EditmodeTests/Subscriptions/RequireablesUnlinkTests.cs
- test-project/Assets/EditmodeTests/Subscriptions/RequireablesUnlinkTests.cs.meta
Added some tests to ensure that the state of reader/writer/commandxyz objects is correctly managed when a GameObject is unlinked from an entity.
Yes these are tests.
> Add requireables <-> unlink tests

- CHANGELOG.md
- test-project/Assets/Generated/Source/improbable/dependentschema/DependentComponentComponentDiffStorage.cs
- test-project/Assets/Generated/Source/improbable/dependentschema/DependentDataComponentComponentDiffStorage.cs
- test-project/Assets/Generated/Source/improbable/tests/DependencyTestChildComponentDiffStorage.cs
- test-project/Assets/Generated/Source/improbable/tests/DependencyTestComponentDiffStorage.cs
- test-project/Assets/Generated/Source/improbable/tests/DependencyTestGrandchildComponentDiffStorage.cs
- test-project/Assets/Generated/Source/improbable/testschema/ComponentUsingNestedTypeSameNameComponentDiffStorage.cs
- test-project/Assets/Generated/Source/improbable/testschema/ExhaustiveEntityComponentDiffStorage.cs
- test-project/Assets/Generated/Source/improbable/testschema/ExhaustiveMapKeyComponentDiffStorage.cs
- test-project/Assets/Generated/Source/improbable/testschema/ExhaustiveMapValueComponentDiffStorage.cs
- test-project/Assets/Generated/Source/improbable/testschema/ExhaustiveOptionalComponentDiffStorage.cs
- test-project/Assets/Generated/Source/improbable/testschema/ExhaustiveRepeatedComponentDiffStorage.cs
- test-project/Assets/Generated/Source/improbable/testschema/ExhaustiveSingularComponentDiffStorage.cs
- test-project/Assets/Generated/Source/improbable/testschema/RecursiveComponentComponentDiffStorage.cs
- workers/unity/Packages/io.improbable.gdk.core/.codegen/Source/Generators/Core/ComponentDiffStorageGenerator.cs
- workers/unity/Packages/io.improbable.gdk.core/EntityId.cs
- workers/unity/Packages/io.improbable.gdk.core/View/DiffComponentStorage.cs
- workers/unity/Packages/io.improbable.gdk.core/View/DiffComponentStorage.cs.meta
- workers/unity/Packages/io.improbable.gdk.core/Worker/DiffStorage.cs
- workers/unity/Packages/io.improbable.gdk.core/Worker/MessagesToSend.cs
- workers/unity/Packages/io.improbable.gdk.core/Worker/ViewDiff.cs
First iteration of simplifications in the Component section of code generation.
Includes an improvement in the ViewDiff and MessagesToSend, reducing a double lookup for storage instances to a single lookup.
> Simplify components, step 1

- CHANGELOG.md
- test-project/Assets/EditmodeTests/Core.meta
- test-project/Assets/EditmodeTests/Core/ComponentDiffStorageTests.cs
- test-project/Assets/EditmodeTests/Core/ComponentDiffStorageTests.cs.meta
- test-project/Assets/EditmodeTests/DisableAutoCreationSystemsTests.cs
- test-project/Assets/Generated/Source/improbable/dependentschema/DependentDataComponentComponentDiffStorage.cs
- workers/unity/Packages/io.improbable.gdk.core/.codegen/Source/Generators/Core/ComponentDiffStorageGenerator.cs
Encountered a bug where receiving a series of ops like:
```
ComponentUpdate(eid: 100, cid: 100, fields: empty, events: list<ev>)
RemoveComponent(eid: 100, cid: 100) 
```
would leave leftover events in the `ViewDiff` for entities-components which have left your view.
This PR fixes this bug by properly marking entities as changed when we receive an event and adds some test coverage for this behaviour.
> Events also update entities!

- CHANGELOG.md
- test-project/Assets/EditmodeTests/Subscriptions/RequireablesDisableTests.cs
- test-project/Assets/EditmodeTests/Subscriptions/RequireablesDisableTests.cs.meta
- test-project/Assets/EditmodeTests/Subscriptions/RequireablesUnlinkTests.cs.meta
- test-project/Assets/Generated/Source/improbable/dependentschema/DependentComponentComponentReaderWriter.cs
- test-project/Assets/Generated/Source/improbable/dependentschema/DependentDataComponentComponentReaderWriter.cs
- test-project/Assets/Generated/Source/improbable/tests/DependencyTestChildComponentReaderWriter.cs
- test-project/Assets/Generated/Source/improbable/tests/DependencyTestComponentReaderWriter.cs
- test-project/Assets/Generated/Source/improbable/tests/DependencyTestGrandchildComponentReaderWriter.cs
- test-project/Assets/Generated/Source/improbable/testschema/ComponentUsingNestedTypeSameNameComponentReaderWriter.cs
- test-project/Assets/Generated/Source/improbable/testschema/ExhaustiveEntityComponentReaderWriter.cs
- test-project/Assets/Generated/Source/improbable/testschema/ExhaustiveMapKeyComponentReaderWriter.cs
- test-project/Assets/Generated/Source/improbable/testschema/ExhaustiveMapValueComponentReaderWriter.cs
- test-project/Assets/Generated/Source/improbable/testschema/ExhaustiveOptionalComponentReaderWriter.cs
- test-project/Assets/Generated/Source/improbable/testschema/ExhaustiveRepeatedComponentReaderWriter.cs
- test-project/Assets/Generated/Source/improbable/testschema/ExhaustiveSingularComponentReaderWriter.cs
- test-project/Assets/Generated/Source/improbable/testschema/RecursiveComponentComponentReaderWriter.cs
- workers/unity/Packages/io.improbable.gdk.core/Subscriptions/CommandSenderReceiverSubscriptionManagerBase.cs
- workers/unity/Packages/io.improbable.gdk.core/Subscriptions/RequiredSubscriptionsInjector.cs
- workers/unity/Packages/io.improbable.gdk.gameobjectcreation/.codegen/Source/Generators/GameObjectCreation/UnityComponentReaderWriterGenerator.cs
This PR makes some changes to when a field annotated with `[Require]` have `IsValid` set to `false` and the value set to `null`. 
Previously this would only happen when a GameObject was unlinked from the underlying entity, typically when the entity had left the worker's view (unless a user had some custom logic). This means that if you had a MonoBehaviour like:
```csharp
public MyBehaviour : MonoBehaviour {
[Require] public HealthReader HealthReader;
}
```
if the underlying Health component left your view, say through a QBI query the `HealthReader` field would be left injected _and_ `IsValid` would still be true. If you copied the reference or captured it in a closure, this could result in bad behaviour. 
Now, when the required field's constraints are no longer met, `HealthReader.IsValid` …
> Requireable constraint tweaks & bugfixing

- CHANGELOG.md
- workers/unity/Packages/io.improbable.gdk.deploymentlauncher/DeploymentLauncherWindow.cs
- workers/unity/Packages/io.improbable.gdk.deploymentlauncher/DeploymentLauncherWindowStyle.cs
- workers/unity/Packages/io.improbable.gdk.deploymentlauncher/DeploymentLauncherWindowStyle.cs.meta
Added a label which diplays the current runtime version & a button which opens the GDK Tools Configuration window to the deployment launcher.
> Display runtime version in deployment launcher

- .buildkite/generate-docs.definition.yaml
- .buildkite/generate-docs.steps.yaml
- ci/generate-docs.sh
This PR introduces a BuildKite pipeline for producing generated documentation and publishing it to Readme. This PR implements the first part of this. (See the TODO for the second part).
You can see an example build here - https://buildkite.com/improbable/gdk-for-unity-generate-docs/builds/9#_ where the generated docs are present in the artifacts.
> Generated Docs Pipeline

- CHANGELOG.md
- test-project/Assets/EditmodeTests/Improbable.Gdk.EditModeTests.asmdef
- test-project/Assets/EditmodeTests/Subscriptions/InjectionCriteriaTests.cs
- test-project/Assets/EditmodeTests/Subscriptions/RequireablesDisableTests.cs
- test-project/Assets/EditmodeTests/Subscriptions/RequireablesUnlinkTests.cs
- test-project/Assets/EditmodeTests/Subscriptions/WorkerTypeCriteriaTests.cs
- workers/unity/Packages/io.improbable.gdk.core/AssemblyInfo.cs
- workers/unity/Packages/io.improbable.gdk.core/Worker/ConnectionHandlers/MockConnectionHandler.cs
- workers/unity/Packages/io.improbable.gdk.testutils/Improbable.Gdk.TestUtils.asmdef
- workers/unity/Packages/io.improbable.gdk.testutils/MockBase.cs
- workers/unity/Packages/io.improbable.gdk.testutils/MockBase.cs.meta
- workers/unity/Packages/io.improbable.gdk.testutils/MockWorld.cs
- workers/unity/Packages/io.improbable.gdk.testutils/MockWorld.cs.meta
This PR condenses some of the patterns we've used in testing into a `MockWorld` class which helps you write integration tests in a fluent and easy to understand way. The goal of this was to make it very easy to spin up the full stack with a mock connection and tick through frames. This is visible in the API which looks something like:
```csharp
MockWorld.Create(new MockWorld.Options())
.Step(world => /* first frame */)
.Step(world => /* second frame */)
...
```
The `MockWorld` classes has a minimal feature set, and can be extended in the future:
- Handling the creation and management of the world & player loop. 
- Create and link GameObjects (with a given component), a future extension could be adding a `<T1, T2>` & `<T1, T2, T3>` version.
- Passing arbitrary context through 'frames' …
> The beginnings of a useful testing framework

- CHANGELOG.md
- workers/unity/Packages/io.improbable.gdk.core/Utility/CommandLineUtility.cs
While debugging an issue related to command line args, I found that we had no way of nicely printing all the arguments collected by `CommandLineArgs`.
This PR adds a method to allow you to dump all the arguments into a single string.
> Add `Dump()` method to `CommandLineArgs`

- CHANGELOG.md
- workers/unity/Assets/Playground/Config/WorkerUtils.cs
- workers/unity/Assets/Playground/Scripts/MonoBehaviours/SpawnCubeCommandReceiver.cs
- workers/unity/Packages/io.improbable.gdk.core/Systems/EntityReservationSystem.cs
- workers/unity/Packages/io.improbable.gdk.core/Systems/EntityReservationSystem.cs.meta
Create an Entity Reservation System.
This system will allow users to obtain reserved entity id's which are backed by an internal pool.
Uses awaitable tasks.
Unit tests and integrated into Playground cube spawning.
> Entity reservation system

- CHANGELOG.md
- UPGRADE_GUIDE.md
- workers/unity/Assets/Playground/Config/PlayerTemplate.cs
- workers/unity/Assets/Playground/Config/WorkerUtils.cs
- workers/unity/Packages/io.improbable.gdk.playerlifecycle/Config/PlayerLifecycleConfig.cs
- workers/unity/Packages/io.improbable.gdk.playerlifecycle/PlayerLifecycleHelper.cs
- workers/unity/Packages/io.improbable.gdk.playerlifecycle/Systems/PlayerCreation/HandleCreatePlayerRequestSystem.cs
Player spawning now uses the EntityReservationSystem to provide a known entityId.
This is added to the `CreatePlayerEntityTemplate` for use in QBI.
This is a breaking change.
Playground tested.
> PlayerLifecycle integration with the EntityReservationSystem

- CHANGELOG.md
- workers/unity/Packages/io.improbable.gdk.mobile/Editor/AndroidUtils.cs
Fix up path detection for the Android SDK when using the embedded install.
> Fix finding of Android SDK path when using the embedded Android SDK

- workers/unity/Packages/io.improbable.gdk.core/Collections/EntityRangeCollection.cs
- workers/unity/Packages/io.improbable.gdk.core/Tests/Editmode/Collections/EntityRangeCollectionTests.cs
EntityRangeCollection.Dequeue wasn't popping ranges off the queue once the first element was empty.
Added additional test for this behaviour
> Fix EntityRangeCollection.Dequeue

- CHANGELOG.md
- UPGRADE_GUIDE.md
There were a couple lurking in the changelog & upgrade guide. Will update the links in the release notes for the relevant releases.
> Update last of the old docs links

- CHANGELOG.md
- UPGRADE_GUIDE.md
- workers/unity/Packages/io.improbable.gdk.gameobjectcreation/EntityTypeExpectations.cs
- workers/unity/Packages/io.improbable.gdk.gameobjectcreation/EntityTypeExpectations.cs.meta
- workers/unity/Packages/io.improbable.gdk.gameobjectcreation/EntityTypeRegistrations.cs.meta
- workers/unity/Packages/io.improbable.gdk.gameobjectcreation/GameObjectCreatorFromMetadata.cs
- workers/unity/Packages/io.improbable.gdk.gameobjectcreation/GameObjectInitializationSystem.cs
- workers/unity/Packages/io.improbable.gdk.gameobjectcreation/IEntityGameObjectCreator.cs
- workers/unity/Packages/io.improbable.gdk.gameobjectcreation/Tests/Editmode/GameObjectCreationTests.cs
- workers/unity/Packages/io.improbable.gdk.gameobjectcreation/Tests/Editmode/MockGameObjectCreator.cs
- `EntityTypeExpectations` keeps track of entitytype -> expectedtype[] map
- ability to define a default type[] as a fallback
- gameobject initialization system will check if entity has the expected types
- if it does -> call `OnEntityCreated`
- if not, return 
> Better gameobject initialization

- CHANGELOG.md
- workers/unity/Packages/io.improbable.gdk.gameobjectcreation/GameObjectInitializationSystem.cs
Set ecs entity names in EntityDebugger when using the editor.
> Set debug names for ecs entities in editor

- CHANGELOG.md
- workers/unity/Packages/io.improbable.gdk.buildsystem/Configuration/BuildConfigEditor.cs
With our upgrade to 2019.3f, we can do headless development builds again for Linux without having it crash!
Also re-ordered the options on the GUI so that they are the same order for all platforms.
> Allow headless development builds for Linux

- CHANGELOG.md
- workers/unity/Packages/io.improbable.gdk.tools/GenerateCode.cs
Invalid JSON is now logged if there is an error parsing the codegen output
passed in json that wasn't valid
> Log invalid JSON if error parsing the codegen output

- CHANGELOG.md
- workers/unity/Packages/io.improbable.gdk.mobile/Editor/AndroidUtils.cs
- workers/unity/Packages/io.improbable.gdk.mobile/Editor/MobileLauncherWindow.cs
Only show android section of mobile launcher if android build support is installed.
> Hide Android in mobile launcher if build support not installed

- CHANGELOG.md
- workers/unity/Assets/Playground/Config/DeploymentLauncherConfig.asset
- workers/unity/Packages/io.improbable.gdk.deploymentlauncher/.DeploymentLauncher/Commands/Create.cs
- workers/unity/Packages/io.improbable.gdk.deploymentlauncher/.DeploymentLauncher/Options.cs
- workers/unity/Packages/io.improbable.gdk.deploymentlauncher/DeploymentConfigurations.cs
- workers/unity/Packages/io.improbable.gdk.deploymentlauncher/DeploymentLauncherWindow.cs
As usual, commits are ordered and self contained.
This PR adds support for choosing a specific cluster for a deployment. This is exposed to the user as a exclusive choice between a region _or_ cluster. 
The same change is applied to the `DeploymentLauncher` csproj. I chose to make the `--cluster` and `--region` flags both optional, but it will throw if neither are provided. In the case where both are provided, `--cluster` takes precedence since it is the more specific option.
This change was made in a way such that it should be backward compatible, there should be no action required upon upgrade.
Also if anyone knows a better way of aligning `GUILayout` controls with `EditorGUILayout` scopes, please let me know 😅
> Expose cluster in deployment launcher

- ci/test.sh
- test-project/Packages/manifest.json
- workers/unity/Packages/manifest.json
When running our tests, we will now output an `.xml` file with test coverage information. This will later be consumed by a service. I've also removed the Playmode tests for the `playground` project as we have none of those. I'm pretty sure that the existing Playmode tests can be ported to Editmode in the `test-project` too. This should cut down on runtime :) 
Observed artifacts in CI.
> Produce test coverage reports

- workers/unity/Packages/io.improbable.gdk.testutils/Editor/Tests/SpatialDeploymentManagerTests.cs
- workers/unity/Packages/io.improbable.gdk.testutils/Editor/Tests/SpatialdManagerTests.cs
These are flaking enough that we should disable them and potentially investigate why they flake. I considered test categories, but there doesn't seem to be support for _excluding_ a category when running tests, so every other test would need to have a category that says 'not flakey'. Would also require extra bash logic which is always undesirable. 
Going to check the test results on the MacOS agent to ensure these aren't run.
> Disable flakey tests on MacOS

- CHANGELOG.md
- test-project/Assets/EditmodeTests/Utility/EntityTemplateTests.cs
- workers/unity/Packages/io.improbable.gdk.core/Utility/EntityTemplate.cs
If you had an `ISpatialComponentSnapshot`, you couldn't interact with the `EntityTemplate` object w/o reflection or using the Dynamic API. This PR completes the set of APIs for type-erased usage of the `EntityTemplate` class.
Also driveby fixed a bug where if you added `EntityAcl.Snapshot` with write access, the snapshot wouldn't be added, but the write access would!
Yes there are tests.
> Add non-generic overloads to `EntityTemplate`

- CHANGELOG.md
- UPGRADE_GUIDE.md
- workers/unity/Assets/Playground/Scripts/Worker/ClientWorkerConnector.cs
- workers/unity/Assets/Playground/Scripts/Worker/GameLogicWorkerConnector.cs
- workers/unity/Assets/Playground/Scripts/Worker/MobileClientWorkerConnector.cs
- workers/unity/Packages/io.improbable.gdk.core/Worker/WorkerConnector.cs
`WorkerConnecter.Connect` now throws when it fails to connect. This makes the `HandleWorkerConnectionFailed` redundant and has been removed. I've also made a couple of behavioural tweaks:
- The `WorkerConnector` no longer destroys itself when it fails to connect. Only concern I have here is embedded in the WorkerConnector is this odd disposable MonoBehaviour, I _think_ the reason it destroyed itself was that it was considered "consumed" after a disconnect, but there's no reason why you can't use the same object to connect again! This feels like its tied up in a confused abstraction (where the `WorkerConnector` is both a way to connect a worker and something to represent the worker after connection).
- The WorkerConnector won't log the failure (since an unhandled exception would log, and a …
> Change up worker connector semantics slightly

- CHANGELOG.md
- workers/unity/Packages/io.improbable.gdk.deploymentlauncher/.DeploymentLauncher/ClientFactory.cs
- workers/unity/Packages/io.improbable.gdk.deploymentlauncher/.DeploymentLauncher/Commands/Create.cs
Noticed this while poking around, figured I'd just driveby it.
> Use correct platform API endpoint for DAT in Deployment Launcher

- .buildkite/premerge.steps.yaml
We've had this for a week with no problems, lets take the training wheels off
> Remove `soft_fail` from sonarscanner

- init.ps1
- init.sh
Added an override for the Worker SDK version in the `init.sh` and `init.ps1`. This allows for someone to run a Buildkite build against the GDK with a given Worker SDK version by setting the `WORKER_SDK_OVERRIDE` environment variable in the build options.
- Checked the value of `SDK_VERSION`/`$SdkVersion` with and without the environment variable set.
Not sure where to put this info... wiki maybe?
> Add worker sdk override env variables

- CHANGELOG.md
- test-project/Assets/EditmodeTests/Collections/ReferenceProviderTests.cs
- workers/unity/Packages/io.improbable.gdk.core/Worker/ConnectionHandlers/MockConnectionHandler.cs
See branch name for motivation, you can now remove components & an entity the same way you add them.
> Add convenience method to the `MockConnection` 

- workers/unity/Packages/io.improbable.gdk.core/EntityId.cs
- workers/unity/Packages/io.improbable.gdk.core/Systems/EntitySystem.cs
- workers/unity/Packages/io.improbable.gdk.debug/AssemblyInfo.cs
- workers/unity/Packages/io.improbable.gdk.debug/AssemblyInfo.cs.meta
- workers/unity/Packages/io.improbable.gdk.debug/Improbable.Gdk.Debug.asmdef
- workers/unity/Packages/io.improbable.gdk.debug/Tests.meta
- workers/unity/Packages/io.improbable.gdk.debug/Tests/Editmode.meta
- workers/unity/Packages/io.improbable.gdk.debug/Tests/Editmode/Improbable.Gdk.Debug.EditmodeTests.asmdef
- workers/unity/Packages/io.improbable.gdk.debug/Tests/Editmode/Improbable.Gdk.Debug.EditmodeTests.asmdef.meta
- workers/unity/Packages/io.improbable.gdk.debug/Tests/Editmode/WorkerInspector.meta
- workers/unity/Packages/io.improbable.gdk.debug/Tests/Editmode/WorkerInspector/EntityListDataTests.cs
- workers/unity/Packages/io.improbable.gdk.debug/Tests/Editmode/WorkerInspector/EntityListDataTests.cs.meta
- workers/unity/Packages/io.improbable.gdk.debug/Tests/Editmode/WorkerInspector/EntitySearchParametersTests.cs
- workers/unity/Packages/io.improbable.gdk.debug/Tests/Editmode/WorkerInspector/EntitySearchParametersTests.cs.meta
- workers/unity/Packages/io.improbable.gdk.debug/WorkerInspector.meta
- workers/unity/Packages/io.improbable.gdk.debug/WorkerInspector/EntityList.cs
- workers/unity/Packages/io.improbable.gdk.debug/WorkerInspector/EntityList.cs.meta
- workers/unity/Packages/io.improbable.gdk.debug/WorkerInspector/EntityListData.cs
- workers/unity/Packages/io.improbable.gdk.debug/WorkerInspector/EntityListData.cs.meta
- workers/unity/Packages/io.improbable.gdk.debug/WorkerInspector/EntitySearchParameters.cs
- workers/unity/Packages/io.improbable.gdk.debug/WorkerInspector/EntitySearchParameters.cs.meta
- workers/unity/Packages/io.improbable.gdk.debug/WorkerInspector/Templates.meta
- workers/unity/Packages/io.improbable.gdk.debug/WorkerInspector/Templates/EntityList.uxml
- workers/unity/Packages/io.improbable.gdk.debug/WorkerInspector/Templates/EntityList.uxml.meta
- workers/unity/Packages/io.improbable.gdk.debug/WorkerInspector/Templates/WorkerInspectorWindow.uss
- workers/unity/Packages/io.improbable.gdk.debug/WorkerInspector/Templates/WorkerInspectorWindow.uss.meta
- workers/unity/Packages/io.improbable.gdk.debug/WorkerInspector/Templates/WorkerInspectorWindow.uxml
- workers/unity/Packages/io.improbable.gdk.debug/WorkerInspector/Templates/WorkerInspectorWindow.uxml.meta
- workers/unity/Packages/io.improbable.gdk.debug/WorkerInspector/WorkerInspectorWindow.cs
- workers/unity/Packages/io.improbable.gdk.debug/WorkerInspector/WorkerInspectorWindow.cs.meta
This PR is the first in a series for the Worker Inspector window. In it, we find:
- The window definition itself
- A UI element for listing and selecting entities. 
- Searching over the list of entities by entity ID and entity type (metadata)
- Relatively efficient list rebuilding
- Only rebuilds when entities have been added/removed.
- With 10k SpatialOS entities in the Editor => ~2-3ms for a full rebuild
- With 100k SpatialOS entities in the Editor => ~20-30ms for a full rebuild
- (On a i7 7700k)
- Possible optimizations in the future would be to use the [`EntityManagerDiffer`](https://docs.unity3d.com/Packages/com.unity.entities@0.11/api/Unity.Entities.EntityManagerDiffer.html) to track changes, but this would require the underlying data storage to be equipped for fast …
> Worker Inspector window & Entity List

- .buildkite/hooks/pre-command
- .buildkite/premerge.steps.yaml
- .buildkite/release-qa.steps.yaml
- ci/shared-ci.pinned
- ci/sonar-scanner.sh
- ci/test.sh
Provides `ACCELERATOR_ENDPOINT` argument to agents and provides the relevant arguments to use either the local/cloud Accelerators for mac/windows agents.
Depends on https://github.com/spatialos/gdk-for-unity-shared-ci/pull/72
Ran the pipeline. Multiple times.
n/a
> Enable Accelerator

- workers/unity/Packages/io.improbable.gdk.debug/.codegen/Source/Generators/DebugExtensions/ComponentVisualElementGenerator.cs
- workers/unity/Packages/io.improbable.gdk.debug/.codegen/Source/Generators/DebugExtensions/DebugAssemblyGenerator.cs
- workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/CodeWriter/Scopes/Abstract/ScopeBody.cs
- workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/CodeWriter/Scopes/TypeBlock.cs
- workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/Model/Details/FieldTypes/ContainedType.cs
- workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/Model/Details/FieldTypes/SingularFieldType.cs
- workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/Model/Details/PropertyDetails/UnityFieldDetails.cs
- workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/Utils/Formatting.cs
This PR adds a subset of the component data rendering to the Worker Inspector. It adds support for all schema primitives (except for `Entity`) and schema enums. Later PRs will add
- user defined types
- schema collections (lists, maps, and options)
- the `Entity` schema type
Note in https://github.com/spatialos/gdk-for-unity/pull/1387/commits/f0816334405202b840b365a4ecf92eec682f7a5d I turned quite a few things public. Discussed a strategy with Paul and will raise a ticket to go back and refactor these to make using them easier in the modular codegen world. 
Eyeball test. Will conduct more exhaustive tests once all the data types are in
> Render primitive schema data & enums in the worker inspector

- workers/unity/Packages/io.improbable.gdk.debug/.codegen/Source/ComponentVisualElementJob.cs
- workers/unity/Packages/io.improbable.gdk.debug/.codegen/Source/Generators/DebugExtensions/ComponentVisualElementGenerator.cs
- workers/unity/Packages/io.improbable.gdk.debug/.codegen/Source/Generators/DebugExtensions/FieldTypeHandler.cs
- workers/unity/Packages/io.improbable.gdk.debug/.codegen/Source/Generators/DebugExtensions/TypeVisualElementGenerator.cs
- workers/unity/Packages/io.improbable.gdk.debug/WorkerInspector/Codegen/SchemaTypeVisualElement.cs
- workers/unity/Packages/io.improbable.gdk.debug/WorkerInspector/Codegen/SchemaTypeVisualElement.cs.meta
- workers/unity/Packages/io.improbable.gdk.debug/WorkerInspector/Templates/WorkerInspectorWindow.uss
- workers/unity/Packages/io.improbable.gdk.debug/WorkerInspector/Templates/WorkerInspectorWindow_Dark.uss
- workers/unity/Packages/io.improbable.gdk.debug/WorkerInspector/Templates/WorkerInspectorWindow_Light.uss
- workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/Model/Details/FieldTypes/ContainedType.cs
- workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/Model/Details/TypeDetails/UnityTypeDetails.cs
This PR adds support for rendering user-defined schema types in the Worker Inspector. 
- We generate a `VisualElement` implementation for each schema type.
- This is then used in components and other types to opaquely render the schema type.
Each type has indented labels (which does then indent the field, we can look at resolving this later, but its non-trivial). 
This PR also fixed some of the styling issues (where the fields were entirely grayed out due to an opacity setting). 
Eyeball test with nested types.
> Add rendering support for user-defined types

- workers/unity/Packages/io.improbable.gdk.debug/.codegen/Source/Generators/DebugExtensions/FieldTypeHandler.cs
- workers/unity/Packages/io.improbable.gdk.debug/WorkerInspector/Codegen/Improbable.Gdk.Debug.WorkerInspector.Codegen.asmdef
- workers/unity/Packages/io.improbable.gdk.debug/WorkerInspector/Codegen/OptionVisualElement.cs
- workers/unity/Packages/io.improbable.gdk.debug/WorkerInspector/Codegen/OptionVisualElement.cs.meta
- workers/unity/Packages/io.improbable.gdk.debug/WorkerInspector/Templates/WorkerInspectorWindow.uss
- workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/Model/Details/FieldTypes/OptionFieldType.cs
This PR adds rendering support for `Option<T>` to the Worker Inspector. 
- Add `OptionVisualElement` and `NullableVisualElement` to render `Option<T>` and `T?` respectively. (We use `T?` except for when `T` is a reference type, i.e. - string and bytes).
- Refactor `FieldTypeHandler` a bit to support the above VisualElements. 
Eyeball test of the `ExhaustiveOptional` component.
> Add Option<T> rendering to the Worker Inspector

- workers/unity/Packages/io.improbable.gdk.debug/.codegen/Source/Generators/DebugExtensions/FieldTypeHandler.cs
- workers/unity/Packages/io.improbable.gdk.debug/WorkerInspector/Codegen/AssemblyInfo.cs
- workers/unity/Packages/io.improbable.gdk.debug/WorkerInspector/Codegen/AssemblyInfo.cs.meta
- workers/unity/Packages/io.improbable.gdk.debug/WorkerInspector/Codegen/PaginatedListView.cs
- workers/unity/Packages/io.improbable.gdk.debug/WorkerInspector/Codegen/PaginatedListView.cs.meta
- workers/unity/Packages/io.improbable.gdk.debug/WorkerInspector/Codegen/SchemaTypeVisualElement.cs
- workers/unity/Packages/io.improbable.gdk.debug/WorkerInspector/Codegen/Tests.meta
- workers/unity/Packages/io.improbable.gdk.debug/WorkerInspector/Codegen/Tests/Improbable.Gdk.Debug.WorkerInspector.Codegen.EditmodeTests.asmdef
- workers/unity/Packages/io.improbable.gdk.debug/WorkerInspector/Codegen/Tests/Improbable.Gdk.Debug.WorkerInspector.Codegen.EditmodeTests.asmdef.meta
- workers/unity/Packages/io.improbable.gdk.debug/WorkerInspector/Codegen/Tests/PaginatedListViewTests.cs
- workers/unity/Packages/io.improbable.gdk.debug/WorkerInspector/Codegen/Tests/PaginatedListViewTests.cs.meta
- workers/unity/Packages/io.improbable.gdk.debug/WorkerInspector/Templates/PaginatedListView.uxml
- workers/unity/Packages/io.improbable.gdk.debug/WorkerInspector/Templates/PaginatedListView.uxml.meta
- workers/unity/Packages/io.improbable.gdk.debug/WorkerInspector/Templates/WorkerInspectorWindow.uss
- workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/Model/Details/FieldTypes/ListFieldType.cs
This PR introduces list support for the worker inspector by adding a `PaginatedListView<TElement, TData>` visual element for use in the worker inspector. This maintains a pool of `TElement` objects that it will reuse. By default, the number of elements per page is `5`, we can tweak this pretty easily. The `PaginatedListView` accepts two closures in its constructor:
- `Func<TElement> makeElement`. This is what the pool calls when it needs to create a new element.
- `Action<int, TData, TElement> bindElement`. This is what is called when the list view is updating an element. The `int` parameter is the absolute position of the element in the list (i.e. - not the position in the page). 
The pagination handles elements being removed from the list underneath you as well as additions. 
(See …
> Add list support to Worker Inspector

- CHANGELOG.md
- workers/unity/Packages/io.improbable.gdk.core/Utility/EntitySnapshot.cs
- workers/unity/Packages/io.improbable.gdk.debug/.codegen/Source/Generators/DebugExtensions/FieldTypeHandler.cs
- workers/unity/Packages/io.improbable.gdk.debug/WorkerInspector/Templates/WorkerInspectorWindow.uss
- Add Entity rendering to the Worker Inspector. This rendered through a `TextField` and presents itself as the list of components in the `EntitySnapshot`. I.e. - `EntitySnapshot: Metadata, Position, Health`
- Drive by fix on `EntitySnapshot`. There was no way to actually make one of these yourselves 😬 
- Fix text overflowing on text input fields and entity names in the Worker Inspector. (It can still happen in the listview, but its clipped and given the fixed height there's not a _ton_ I can do about this). 
- Refactored some common logic in the `FieldTypeHandler`
- `ExhaustiveEntityRenderer`
- Overflowing text in the `Metadata` (not in this PR)
> Add entity type rendering to Worker Inspector

- CHANGELOG.md
- workers/unity/Packages/io.improbable.gdk.debug/.codegen/Source/Generators/DebugExtensions/FieldTypeHandler.cs
- workers/unity/Packages/io.improbable.gdk.debug/WorkerInspector/Codegen/PaginatedMapView.cs
- workers/unity/Packages/io.improbable.gdk.debug/WorkerInspector/Codegen/PaginatedMapView.cs.meta
- workers/unity/Packages/io.improbable.gdk.debug/WorkerInspector/EntityDetail.cs
- workers/unity/Packages/io.improbable.gdk.debug/WorkerInspector/Templates/WorkerInspectorWindow.uss
- workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/Model/Details/FieldTypes/MapFieldType.cs
This PR adds support for `map<k, v>` types to the Worker Inspector. These are rendered as a list of `key-value` pairs, using the same underlying visualization as the `list<>` fields.
This PR also contains a performance optimization where components were being needlessly re-rendered every frame. This becomes apparent when you have:
- many components
- very complex components (for example - interest)
- Interest component rendering
- Some other random test components in the `schema/` directory.
> Add map support to the Worker Inspector and fix performance bug

- CHANGELOG.md
- init.ps1
- workers/unity/Packages/io.improbable.gdk.tools/LocalLaunch.cs
- workers/unity/Packages/io.improbable.gdk.tools/MenuPriorities.cs
- Added a new menu item to the SpatialOS menu that opens inspector v2
- Update android SDK versions in `init.ps1` script to match those in `init.sh`
Manually tested that inspector v2 opens in browser
None
Added to changelog
> [UTY-2631] Add new menu item to open inspector v2

- ci/publish_packages.sh
The sibling of https://github.com/spatialos/gdk-for-unity-shared-ci/pull/76, here we actually do the npm push.
Ran it on my local machine & a GCE buildkite agent canary.
- Wiki paging incoming
> Push packages to the China registry.

- CHANGELOG.md
- workers/unity/Packages/io.improbable.gdk.deploymentlauncher/DeploymentLauncherWindow.cs
- workers/unity/Packages/io.improbable.gdk.tools/GdkToolsConfiguration.cs
- workers/unity/Packages/io.improbable.gdk.tools/GdkToolsConfigurationProvider.cs
- workers/unity/Packages/io.improbable.gdk.tools/GdkToolsConfigurationProvider.cs.meta
For [UTY-2419](https://improbableio.atlassian.net/browse/UTY-2419)
- Ported `GdkToolsConfiguration` setting window to the Unity SettingsProvider
- Enabled Project settings search functionality for GdkToolsConfiguration
The settings changes now save when `Project Settings` window is closed or  switched away from the Gdk Tools Configuration page (+ Only if changes are made to the settings)
Manually tested that the `GdkToolsConfiguration.json` file represented the changes made in the Project Settings view
> Port Gdk Tools Configuration to Unity Project Settings

- CHANGELOG.md
- UPGRADE_GUIDE.md
- init.ps1
- workers/unity/Assets/Playground/Config/BuildConfiguration.asset
- workers/unity/Packages/io.improbable.gdk.buildsystem/Configuration/BuildConfigEditor.cs
- workers/unity/Packages/io.improbable.gdk.buildsystem/Configuration/BuildConfigEditorStyle.cs
- workers/unity/Packages/io.improbable.gdk.buildsystem/Configuration/BuildContext.cs
- workers/unity/Packages/io.improbable.gdk.buildsystem/Configuration/BuildTargetConfig.cs
- workers/unity/Packages/io.improbable.gdk.buildsystem/WorkerBuilder.cs
For [UTY-1818](https://improbableio.atlassian.net/browse/UTY-1818)
Added the option to choose the scripting implementation (backend) in the build configuration UI
Manually tested that scripting backend was changed using the UI
- Updated v0.3.8 docs to have `Scripting Backend` option in Build Configuration UI
- Some in-code documentation, see (workers/unity/Packages/io.improbable.gdk.buildsystem/Configuration/BuildTargetConfig.cs)
> Scripting Implementation option in Build config UI

- CHANGELOG.md
- workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/Model/Details/FieldTypes/ContainedType.cs
- workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/Model/Details/TypeDetails/UnityEnumDetails.cs
Shifted all C# enum definition to start from 0 to ensure no invalid enums are generated by default constructors. Serialization is done by `value + min_val` and Deserialization `value - min_val`. A warning is also generated to advice users to redefine the schema enums to start from 0.
Change the playground schema for `Color` (sorted and unsorted, sequential and non-sequential) and ran the code generator to ensure the enum definition, serialization and deserialization function in `ColorData` is what's expected.
Yes
> UTY-1970: invalid enum definition

- CHANGELOG.md
- ci/perf-test.sh
- ci/perftest-configs.json
- workers/unity/Packages/io.improbable.gdk.testutils/package.json
- workers/unity/Packages/manifest.json
This should also reduce our machine usage on premerge builds significantly
- Configure branch filters for the various perf testing targets:
- only .net 2.0/burst enabled/Mono target is allowed for playmode/editmode on pre-merge
- all targets run on master/develop
- Moved test framework/perftest package dependency to testutils instead of playground manifest
- only run the csproj/sln initialization if there are any matching targets
- Ran locally, only subset ran
- Run in buildkite, only subset should run
- Ran with branch variable set to master/develop, it iterates through all expected targets
-  [x] internal changelog about adding dependencies to testutils package
If your change will take a long time to review, you can name at most two primary reviewers who are ultimately responsible for …
> Limit perftest targets + package dependency fix

- CHANGELOG.md
- workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/CodeWriter/Text.cs
Standardizes newlines before replacing
Ran codegen with the changes in fps-starter-project where bug was observed
None
> UTY-2643: fix codegen indentation

- CHANGELOG.md
- workers/unity/Packages/io.improbable.gdk.debug/.codegen/Source/Generators/DebugExtensions/ComponentVisualElementGenerator.cs
- workers/unity/Packages/io.improbable.gdk.debug/WorkerInspector/Codegen/ComponentVisualElement.cs
- workers/unity/Packages/io.improbable.gdk.debug/WorkerInspector/Codegen/PaginatedListView.cs
- workers/unity/Packages/io.improbable.gdk.debug/WorkerInspector/Templates/WorkerInspectorWindow.uss
- workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/Model/Details/DetailsStore.cs
- workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/Model/Details/TypeDetails/GeneratorInputDetails.cs
- workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/Model/Details/TypeDetails/UnityComponentDetails.cs
- workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/Model/Details/TypeDetails/UnityEnumDetails.cs
- workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/Model/Details/TypeDetails/UnityTypeDetails.cs
Component details in the worker inspector window now has a new button. Clicking on it will print component ID and filepath to log.
Play sample scene and click on new button next to component name in the worker inspector
> UTY-2640: Add component info

- CHANGELOG.md
- workers/unity/Assets/Tests/EditmodeTests/Correctness/Subscriptions/RequireablesReenableTests.cs
- workers/unity/Assets/Tests/EditmodeTests/Correctness/Subscriptions/RequireablesReenableTests.cs.meta
- workers/unity/Packages/io.improbable.gdk.core/Subscriptions/CommandSenderReceiverSubscriptionManagerBase.cs
If you have a behaviour that looks like:
```csharp
public class MyBehaviour : MonoBehaviour 
{
[Require] private ComponentCommandSender sender;
[Require] private OtherComponentCommandReceiver receiver;
}
```
If this behaviour is disabled due to `OtherComponent` losing authority, `receiver` will be set to `null` and the underlying object has `IsValid` set to `false`. 
If then the behaviour is re-enabled due to `OtherComponent` gaining authority, `receiver` will be re-injected, but `IsValid` will not be set to true. 
This is the same bug as https://github.com/spatialos/gdk-for-unity/pull/1326, but for the sender rather than the readers. The fix is to have everything implement `IRequireable`. This is a consequence of https://github.com/spatialos/gdk-for-unity/pull/1297 where we changed the …
> Fix bug where CommandSender would not reenable after being disabled

- CHANGELOG.md
- workers/unity/Packages/io.improbable.gdk.buildsystem/Configuration/BuildContext.cs
We added the concept of a deprecated target in https://github.com/spatialos/gdk-for-unity/pull/1421 but missing changing this reference from `targetConfigs` to `supportedTargets`
> Correctly skip builds which are not marked as required

- CHANGELOG.md
- workers/unity/Packages/io.improbable.gdk.core/Representation/Editor/PrefabPreprocessor.cs
We broke this in by #1393 as we forgot to change the string when we re-named it. I've changed it to a `typeof()` to avoid this in the future.
- Removed a behaviour and re-added it. Hit play and checked the prefab to make sure it was disabled.
> Fix the `PrefabPreprocessor`

- CHANGELOG.md
- workers/unity/Packages/io.improbable.gdk.buildsystem/Configuration/BuildConfigEditor.cs
This PR is two bug fixes combined in one! 
The first commit is a driveby where selecting the 'Cloud Build Options' and then the 'Local Build Options' and then selecting the `iOS` target would throw errors. TL;DR - We built a cache and forget to clear it when its invalidated.
The second is the fix for the associated ticket, if the editor pref isn't set, we look to ensure that the default location for the Android SDK installed by Unity is present. 
Put my build configuration in a configuration that would give me the missing Android SDK error (even though it was installed), then applied the code changes and checked that it correctly identifies it as installed.
> Fix Android support check

- CHANGELOG.md
- workers/unity/Packages/io.improbable.gdk.tools/LocalLaunch.cs
We use `osascript` for launching a local deployment with `spatial`. This has some particular rules around quotation, especially as we are running the script inline from a shell. 
This resulted in errors when paths had spaces in them. To handle these, I've used the built-in quoting abilities in `osascript` rather than trying to escape them manually twice (once for shell and once for osascript!). 
- Renamed `gdk-for-unity` to `gdk for unity` on my local machine to test launching a deployment & standalone client.
> Fix MacOS local launch errors when there are spaces in paths

- CHANGELOG.md
- workers/unity/Packages/io.improbable.gdk.transformsynchronization/Systems/DefaultApplyLatestTransformSystem.cs
- workers/unity/Packages/io.improbable.gdk.transformsynchronization/Systems/DefaultUpdateLatestTransformSystem.cs
- workers/unity/Packages/io.improbable.gdk.transformsynchronization/Systems/ResetForAuthorityGainedSystem.cs
- workers/unity/Packages/io.improbable.gdk.transformsynchronization/Systems/SetKinematicFromAuthoritySystem.cs
- workers/unity/Packages/io.improbable.gdk.transformsynchronization/TransformUtils.cs
We had two different bugs that revealed themselves when we removed the `AuthorityLossImminent` state in #1451 
- The `SetKinematicFromAuthoritySystem` was grabbing the _first_ authority change received in that frame to use as the authority change. In the case where you got `AuthorityLossImminent` and then `NotAuthoritative` in the same frame, it would grab `AuthorityLossImminent` (incorrectly).
- The query returned by `ConstructEntityQueryDesc<T>` would have an `Exclude<TransformInternal.HasAuthority>` filter on it. This meant that we would never even attempt to reset the kinematic authority set when you become 'not authoritative'. 
These two bugs combined meant that the kinematic state would never be by the system ever. In the playground, this seemed not to matter so we never noticed it …
> Fix `Set Kinematic When Not Authoritative` not being applied correctly.

- .buildkite/premerge.steps.yaml
- .buildkite/release-qa.steps.yaml
- CHANGELOG.md
- UPGRADE_GUIDE.md
- workers/unity/.gitignore
- workers/unity/Packages/io.improbable.gdk.debug/WorkerInspector/EntityList.cs
- workers/unity/Packages/manifest.json
- workers/unity/ProjectSettings/PackageManagerSettings.asset
- workers/unity/ProjectSettings/ProjectSettings.asset
- workers/unity/ProjectSettings/ProjectVersion.txt
- workers/unity/ProjectSettings/VersionControlSettings.asset
This PR upgrades the GDK for Unity to 2020.1 as the minimum Unity version. There will be follow up PRs for:
- https://github.com/spatialos/gdk-for-unity-fps-starter-project/pull/291
- Blank
Most of this was auto-generated or performed by Unity on upgrade, except for the changes in `EntityList` where there was a deprecation.
> Unity 2020.1 Upgrade

- workers/unity/Packages/io.improbable.gdk.debug/WorkerInspector/Templates/WorkerInspectorWindow.uss
Fixes a regression introduced in #1459 noticed by @paulbalaji.
Seems that the default styles changed which caused an overflow: 
Removing `width: auto` fixes the issue.
> Fix search bar overflow in worker inspector

- CHANGELOG.md
- workers/unity/Assets/Tests/EditmodeTests/Correctness/Core/OpOrderingTests.cs
- workers/unity/Assets/Tests/EditmodeTests/Correctness/Core/OpOrderingTests.cs.meta
- workers/unity/Packages/io.improbable.gdk.core/UpdatesAndEvents/AuthorityComparer.cs
- workers/unity/Packages/io.improbable.gdk.core/UpdatesAndEvents/ComponentUpdateToSend.cs
- workers/unity/Packages/io.improbable.gdk.core/UpdatesAndEvents/UpdateComparer.cs
- workers/unity/Packages/io.improbable.gdk.core/Worker/ConnectionHandlers/MockConnectionHandler.cs
- workers/unity/Packages/io.improbable.gdk.core/Worker/OpListConverter.cs
- workers/unity/Packages/io.improbable.gdk.core/Worker/ViewDiff.cs
- workers/unity/Packages/io.improbable.gdk.transformsynchronization/Systems/SetKinematicFromAuthoritySystem.cs
Authority changes were stored in reverse order (newest to oldest, rather than oldest to newest). This meant that if you iterated through the `MessageSpan<AuthorityChangeReceived>` changes assuming it would be oldest to newest, the state could end up in correct.
This PR rectifies this issue by ensuring they are ordered in the way we receive them.
> Fix authority changes ordering problem

- CHANGELOG.md
- ci/perf-test.sh
- workers/unity/Packages/io.improbable.gdk.core/package.json
Upgrade to latest burst to fix broken performance test compiles in CI
> Upgrade to Burst 1.3.5 to fix broken compile for performance tests

- workers/unity/Packages/io.improbable.gdk.core/Worker/SerializedMessagesToSend.cs
There was a race whereby if the Worker SDK consumed and cleared the serialized data before we tried to read the data, we would hard crash.
- Ran it a bunch and couldn't repro.
- None required as this regression was unreleased.
> Fix regression introduced in #1454

- CHANGELOG.md
- workers/unity/Packages/io.improbable.gdk.debug/WorkerInspector/EntityListData.cs
- workers/unity/Packages/io.improbable.gdk.debug/WorkerInspector/Templates/WorkerInspectorWindow.uss
This PR removes the outline and background around the component info button in the Worker Inspector.
Before: 
After:
There is also a driveby that stops exceptions from being thrown if you stop playing in the Editor with the Worker Inspector open. (Probably introduced in #1463). 
N/A
> Remove outline around component info button in Worker Inspector

- CHANGELOG.md
- workers/unity/Packages/io.improbable.gdk.tools/GdkToolsConfigurationProvider.cs
Add tooltips for the GDK tools configuration. Text copied from the [upcoming docs page](https://documentation.improbable.io/gdk-for-unity/v0.4.0/docs/gdk-tools-configuration)
https://improbableio.atlassian.net/browse/UTY-2471
Tooltips work
> Tools config tooltips

- workers/unity/Assets/Tests/EditmodeTests/Correctness/SceneAuthoring.meta
- workers/unity/Assets/Tests/EditmodeTests/Correctness/SceneAuthoring/PositionFromGameObjectTests.cs
- workers/unity/Assets/Tests/EditmodeTests/Correctness/SceneAuthoring/PositionFromGameObjectTests.cs.meta
- workers/unity/Assets/Tests/EditmodeTests/Improbable.Gdk.EditmodeTests.asmdef
- workers/unity/Packages/io.improbable.gdk.core/SceneAuthoring/AuthoringComponents.meta
- workers/unity/Packages/io.improbable.gdk.core/SceneAuthoring/AuthoringComponents/Improbable.Gdk.Core.SceneAuthoring.AuthoringComponents.asmdef
- workers/unity/Packages/io.improbable.gdk.core/SceneAuthoring/AuthoringComponents/Improbable.Gdk.Core.SceneAuthoring.AuthoringComponents.asmdef.meta
- workers/unity/Packages/io.improbable.gdk.core/SceneAuthoring/AuthoringComponents/PositionFromGameObjectAuthoringComponent.cs
- workers/unity/Packages/io.improbable.gdk.core/SceneAuthoring/AuthoringComponents/PositionFromGameObjectAuthoringComponent.cs.meta
Add a simple authoring component that uses the GameObject position as the `Position` component. These need to go in their own `asmdef` as they need to reference generated code.
> Add `PositionFromGameObject` authoring component

- workers/unity/Packages/io.improbable.gdk.core/AssemblyInfo.cs
- workers/unity/Packages/io.improbable.gdk.core/Editor/SceneAuthoring.meta
- workers/unity/Packages/io.improbable.gdk.core/Editor/SceneAuthoring/ConvertToSingleEntityEditor.cs
- workers/unity/Packages/io.improbable.gdk.core/Editor/SceneAuthoring/ConvertToSingleEntityEditor.cs.meta
- workers/unity/Packages/io.improbable.gdk.core/SceneAuthoring/ConvertToSingleEntity.cs
- workers/unity/Packages/io.improbable.gdk.core/SceneAuthoring/ConvertToSingleEntity.cs.meta
Following on from #1466, this implements the `IConvertGameObjectToSpatialOsEntity` interface for a 1:1 mapping between a GameObject and SpatialOS entity.
This PR also includes a custom editor for a more intuitive user experience when filling out optional parameters (desired entity ID).
- More complete integration tests to be written once more components are in place.
> One-to-one GameObject converter

- workers/unity/Packages/io.improbable.worker.sdk/CEventTrace.cs
There was a bug introduced in #1440 and slipped by unnoticed in #1452 where the `TraceCallback` callback not provide the expected value for the `ItemType` property in the callbacks `responseItem`. It only happened for an `Event` but not for a `Span`.
This PR resolves the issue by adding the type of `byte` to the internal `ItemType` enum.
Manually verified that both callbacks for `Event` and `Span` provides the correct data.
None
> Fix Event Tracing ItemType Conversion

- CHANGELOG.md
- workers/unity/Assets/Playground/Editor/SnapshotGenerator/SnapshotGenerator.cs
- workers/unity/Assets/Tests/EditmodeTests/Correctness/Utility/SnapshotTests.cs
- workers/unity/Assets/Tests/EditmodeTests/Correctness/Utility/SnapshotTests.cs.meta
- workers/unity/Packages/io.improbable.gdk.core/Utility/Snapshot.cs
In `Snapshot` class:
- Added method to check if `EntityId` is valid
- Improve search for next available `EntityId`
- Added warning when overwriting entities
- Added unit tests for Snapshot class
> UTY-2661: Improve snapshot api

- CHANGELOG.md
- workers/unity/Packages/io.improbable.worker.sdk.mobile/BuildPostProcessXCode.cs
This PR changes the xcode post-process step to grab the GUID using the `GetUnityFrameworkTargetGuid` method.
Building and launching Simulator in 2020.1 works. Simulator client could connect to a local deployment.
> Fix Xcode project modification for iOS Simulator

- CHANGELOG.md
- workers/unity/Packages/io.improbable.gdk.core/Commands/CommandSender.cs
- workers/unity/Packages/io.improbable.gdk.core/Commands/CommandSender.cs.meta
- workers/unity/Packages/io.improbable.gdk.core/Subscriptions/CommandSenderReceiverSubscriptionManagerBase.cs
- workers/unity/Packages/io.improbable.gdk.core/Subscriptions/StandardSubscriptionManagers/WorldCommands.cs
- workers/unity/Packages/io.improbable.gdk.gameobjectcreation/.codegen/Source/Generators/GameObjectCreation/UnityCommandSenderReceiverGenerator.cs
The code between the generated command senders and the `WorldCommandSender` drifted apart over time and so bugs that had been fixed weren't fixed in the `WorldCommandSender`.
Re-unified the generated & world command senders by using a common base and thus fixed the bug.
Split from #1491
> Fix `WorldCommandSender` 

- CHANGELOG.md
- workers/unity/Packages/io.improbable.gdk.core/Tests/Editmode/Connection/ReceptionistFlowTests.cs
- workers/unity/Packages/io.improbable.gdk.testutils/Editor/SpatialDeploymentManager.cs
- workers/unity/Packages/io.improbable.gdk.testutils/Editor/Tests/SpatialDeploymentManagerTests.cs
This was missed way back when the runtime version was a required parameter.
Split from #1491
> SpatialDeploymentManager requires runtime version

- workers/unity/Assets/Playground/Editor/SnapshotGenerator/SnapshotGenerator.cs
- workers/unity/Assets/Playground/Scripts/OneTimeInitialisation.cs
- workers/unity/Packages/io.improbable.gdk.playerlifecycle/Config/PlayerLifecycleConfig.cs
- workers/unity/Packages/io.improbable.gdk.playerlifecycle/Systems/PlayerCreation/SendCreatePlayerRequestSystem.cs
Entity queries cannot have component level permissions in v15, so this system should not use them otherwise we require clients to have full query permissions over the deployment.
I additionally refactored the system to move all the stateful parts into a separate class, this makes it easier to reason about (imo).
> Remove entity query loop from `SendCreatePlayerRequestSystem`. 

- workers/unity/Packages/io.improbable.gdk.buildsystem/package.json
- workers/unity/Packages/io.improbable.gdk.core/package.json
- workers/unity/Packages/io.improbable.gdk.debug/package.json
- workers/unity/Packages/io.improbable.gdk.deploymentlauncher/package.json
- workers/unity/Packages/io.improbable.gdk.gameobjectcreation/package.json
- workers/unity/Packages/io.improbable.gdk.loadbalancing/package.json
- workers/unity/Packages/io.improbable.gdk.mobile/package.json
- workers/unity/Packages/io.improbable.gdk.playerlifecycle/package.json
- workers/unity/Packages/io.improbable.gdk.querybasedinteresthelper/package.json
- workers/unity/Packages/io.improbable.gdk.testutils/package.json
- workers/unity/Packages/io.improbable.gdk.tools/package.json
- workers/unity/Packages/io.improbable.gdk.transformsynchronization/package.json
- workers/unity/Packages/io.improbable.gdk.transformsynchronization2d/package.json
- workers/unity/Packages/io.improbable.worker.sdk.mobile/package.json
- workers/unity/Packages/io.improbable.worker.sdk/package.json
Update minimum Unity version in packages to 2020.1
https://docs.unity3d.com/2020.1/Documentation/Manual/upm-manifestPkg.html
- opened unity
- not required as we already document that 2020.1 is the minimum version required
> Update minimum Unity version in packages to 2020.1
